 "correspondance_dict = {\n",
    "    'GDP CQOQ Index': 'GDP US Chained Dollars QoQ SAA (GDP)',\n",
    "    'GDP CYOY Index':'GDP US Chained Dollars YoY SA (GDP)',\n",
    "    'GDP CURY Index': 'US GDP Nominal Dollars YoY SA (GDP)',\n",
    "    \"GDP PIQQ Index\": \"US GDP Price Index QoQ SAAR (GDP)\",\n",
    "    'USURTOT Index': 'U-3 US Unemployment Rate Total (Employment)',\n",
    "    'NFP TCH Index':'US Employees on Nonfarm Payrol (Employment)',\n",
    "    'ADP CHNG Index':'ADP National Employment Report (Employment)',\n",
    "    'LEI WKIJ Index':'Conference Board US Leading In (Employment)',\n",
    "    'USHEYOY Index':'US Avg Hourly Earnings Private (Inflation)',\n",
    "    'CPI XYOY Index':'US CPI Urban Consumers Less Fo (Inflation)',\n",
    "    'PCE CYOY Index':'US Personal Consumption Expend (Inflation)',\n",
    "    'PPI XYOY Index': 'US PPI Finished Goods Less Foo (Inflation)',\n",
    "    'IP  YOY Index':'US Industrial Production YOY S (Economic Dynamic)',\n",
    "    'CPTICHNG Index':'US Capacity Utilization % of T (Economic Dynamic)',\n",
    "    'DGNOYOY Index':'US Durable Goods New Orders To (Economic Dynamic)',\n",
    "    'MPMIUSCA Index':'US Composite PMI SA (Business Conditions)',\n",
    "    'NAPMPMI Index': 'ISM Manufacturing PMI SA (Business Conditions)',\n",
    "    'MPMIUSMA Index':'US Manufacturing PMI SA (Business Conditions)',\n",
    "    'MPMIUSSA Index': 'US Services PMI Business Activ (Business Conditions)',\n",
    "    'NAPMNMI Index':'ISM Services PMI (Business Conditions)',\n",
    "    'CFNAI Index':'Chicago Fed National Activity (Business Conditions)',\n",
    "    'OUTFGAF Index':'Philadelphia Fed Business Outl (Business Conditions)',\n",
    "    'EMPRGBCI Index':'US Empire State Manufacturing (Business Conditions)',\n",
    "    'RCHSINDX Index':'Richmond Manufacturing Survey (Business Conditions)',\n",
    "    'CHPMINDX Index':'Market News International Chic (Business Conditions)',\n",
    "    'LEI YOY Index': 'Conference Board US Leading In (Business Conditions)',\n",
    "    'NHSPATOT Index':'Private Housing Authorized by (Housing)',\n",
    "    'ETSLTOTL Index':'US NAR Total Existing Homes Sa (Housing)',\n",
    "    'RSTAXMOM Index':'Adjusted Retail Sales Less Aut MoM (Details selling)',\n",
    "    'RSTAXYOY Index':'Adjusted Retail Sales Less Aut YoY (Details selling)',\n",
    "    'SAARTOTL Index':'US Auto Sales Total Annualized (Details selling)',\n",
    "    'PITLYOY Index':'US Personal Income YoY SA (Household)',\n",
    "    'PCE CHY% Index':'US Personal Consumption Expend % (Household)',\n",
    "    'PCE CHNC Index':'US Personal Consumption Expend (Household)',\n",
    "    'CONCCONF Index':'Conference Board Consumer Conf (Customer Trust)',\n",
    "    'CONSSENT Index':'University of Michigan Consume (Customer Trust)',\n",
    "    'SPX INDEX': 'S&P 500 (Stock Index)',\n",
    "    'MXWO INDEX': 'MSCI world (Stock Index)',\n",
    "    'CCMP Index':'NASDAQ (Stock Index)',\n",
    "    'FED FUNDS': 'FED FUNDS (FED)',\n",
    "    'XAU Curncy':'Gold Spot   $/Oz (Materials)',\n",
    "    'CL1 Comdty':\"Generic 1st 'CL' Future (Materials)\",\n",
    "    'ISIX62IU Index': 'Iron Ore Spot Price Index 62% (Materials)',\n",
    "    'LMCADS03 Comdty':'LME COPPER    3MO ($) (Materials)',\n",
    "    'RTY Index':'RUSSELL 2000 INDEX (Stock Index)',\n",
    "    'BITCOIN Index':'BBG BTC Index (Crypto)',\n",
    "    'ETHEREUM Index':'BBG ETH Index (Crypto)',\n",
    "    'S5FINL Index  (R1)':'Financial (Sub S&P500 Indicator)',\n",
    "    \"S5INFT Index  (R2)\":'Information Technologie (Sub S&P500 Indicator)',\n",
    "    'S5HLTH Index  (L1)':'Santé (Sub S&P500 Indicator)',\n",
    "    'S5COND Index  (L1)':'Consommation discrétionnaire (Sub S&P500 Indicator)',\n",
    "    'S5TELS Index  (R1)':'Communication (Sub S&P500 Indicator)',\n",
    "    'S5INDU Index  (L1)':'Industrie (Sub S&P500 Indicator)',\n",
    "    'S5CONS Index  (L1)':'Consommation de base (Sub S&P500 Indicator)',\n",
    "    'S5ENRS Index  (L1)':'Energie (Sub S&P500 Indicator)',\n",
    "    'S5UTIL Index  (R1)':'Utilities (Sub S&P500 Indicator)',\n",
    "    'S5MATR Index  (R1)':'Matières premières (Sub S&P500 Indicator)',\n",
    "    'S5RLST Index  (R1)':'Immobilier (Sub S&P500 Indicator)'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "list_of_categories = ['(GDP)', '(Employment)', '(Inflation)', '(Economic Dynamic)', '(Business Conditions)', '(Housing)', '(Details selling)', '(Household)', '(Customer Trust)', '(Stock Index)', '(FED)', '(Materials)', '(Crypto)', '(Sub S&P500 Indicator)']"
   ]
