correspondance_dict = {
    'GDP CQOQ Index': 'GDP US Chained Dollars QoQ SAA (GDP)',
    'GDP CYOY Index': 'GDP US Chained Dollars YoY SA (GDP)',
    'GDP CURY Index': 'US GDP Nominal Dollars YoY SA (GDP)',
    'GDP PIQQ Index': 'US GDP Price Index QoQ SAAR (GDP)',
    'USURTOT Index': 'U-3 US Unemployment Rate Total (Employment)',
    'NFP TCH Index': 'US Employees on Nonfarm Payrol (Employment)',
    'ADP CHNG Index': 'ADP National Employment Report (Employment)',
    'LEI WKIJ Index': 'Conference Board US Leading In (Employment)',
    'USHEYOY Index': 'US Avg Hourly Earnings Private (Inflation)',
    'CPI XYOY Index': 'US CPI Urban Consumers Less Fo (Inflation)',
    'PCE CYOY Index': 'US Personal Consumption Expend (Inflation)',
    'PPI XYOY Index': 'US PPI Finished Goods Less Foo (Inflation)',
    'IP  YOY Index': 'US Industrial Production YOY S (Economic Dynamic)',
    'CPTICHNG Index': 'US Capacity Utilization % of T (Economic Dynamic)',
    'DGNOYOY Index': 'US Durable Goods New Orders To (Economic Dynamic)',
    'MPMIUSCA Index': 'US Composite PMI SA (Business Conditions)',
    'NAPMPMI Index': 'ISM Manufacturing PMI SA (Business Conditions)',
    'MPMIUSMA Index': 'US Manufacturing PMI SA (Business Conditions)',
    'MPMIUSSA Index': 'US Services PMI Business Activ (Business Conditions)',
    'NAPMNMI Index': 'ISM Services PMI (Business Conditions)',
    'CFNAI Index': 'Chicago Fed National Activity (Business Conditions)',
    'OUTFGAF Index': 'Philadelphia Fed Business Outl (Business Conditions)',
    'EMPRGBCI Index': 'US Empire State Manufacturing (Business Conditions)',
    'RCHSINDX Index': 'Richmond Manufacturing Survey (Business Conditions)',
    'CHPMINDX Index': 'Market News International Chic (Business Conditions)',
    'LEI YOY Index': 'Conference Board US Leading In (Business Conditions)',
    'NHSPATOT Index': 'Private Housing Authorized by (Housing)',
    'ETSLTOTL Index': 'US NAR Total Existing Homes Sa (Housing)',
    'RSTAXMOM Index': 'Adjusted Retail Sales Less Aut MoM (Details selling)',
    'RSTAXYOY Index': 'Adjusted Retail Sales Less Aut YoY (Details selling)',
    'SAARTOTL Index': 'US Auto Sales Total Annualized (Details selling)',
    'PITLYOY Index': 'US Personal Income YoY SA (Household)',
    'PCE CHY% Index': 'US Personal Consumption Expend % (Household)',
    'PCE CHNC Index': 'US Personal Consumption Expend (Household)',
    'CONCCONF Index': 'Conference Board Consumer Conf (Customer Trust)',
    'CONSSENT Index': 'University of Michigan Consume (Customer Trust)',
    'SPX INDEX': 'S&P 500 (Stock Index)',
    'MXWO INDEX': 'MSCI world (Stock Index)',
    'CCMP Index': 'NASDAQ (Stock Index)',
    'FED FUNDS': 'FED FUNDS (FED)',
    'XAU Curncy': 'Gold Spot   $/Oz (Materials)',
    'CL1 Comdty': "Generic 1st 'CL' Future (Materials)",
    'ISIX62IU Index': 'Iron Ore Spot Price Index 62% (Materials)',
    'LMCADS03 Comdty': 'LME COPPER    3MO ($) (Materials)',
    'RTY Index': 'RUSSELL 2000 INDEX (Stock Index)',
    'BITCOIN Index': 'BBG BTC Index (Crypto)',
    'ETHEREUM Index': 'BBG ETH Index (Crypto)',
    'S5FINL Index  (R1)': 'Financial (Sub S&P500 Indicator)',
    'S5INFT Index  (R2)': 'Information Technologie (Sub S&P500 Indicator)',
    'S5HLTH Index  (L1)': 'Santé (Sub S&P500 Indicator)',
    'S5COND Index  (L1)': 'Consommation discrétionnaire (Sub S&P500 Indicator)',
    'S5TELS Index  (R1)': 'Communication (Sub S&P500 Indicator)',
    'S5INDU Index  (L1)': 'Industrie (Sub S&P500 Indicator)',
    'S5CONS Index  (L1)': 'Consommation de base (Sub S&P500 Indicator)',
    'S5ENRS Index  (L1)': 'Energie (Sub S&P500 Indicator)',
    'S5UTIL Index  (R1)': 'Utilities (Sub S&P500 Indicator)',
    'S5MATR Index  (R1)': 'Matières premières (Sub S&P500 Indicator)',
    'S5RLST Index  (R1)': 'Immobilier (Sub S&P500 Indicator)'
}

list_of_categories = [
    '(GDP)',
    '(Employment)',
    '(Inflation)',
    '(Economic Dynamic)',
    '(Business Conditions)',
    '(Housing)',
    '(Details selling)',
    '(Household)',
    '(Customer Trust)',
    '(Stock Index)',
    '(FED)',
    '(Materials)',
    '(Crypto)',
    '(Sub S&P500 Indicator)'
]
