"def show_rolling_corr(dataframe, window=105, folder_name='correlation_plots', image_format='png'):\n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    column_names = dataframe.columns\n",
    "    compared_pairs = set()  # Set to store already compared pairs\n",
    "\n",
    "    for i in range(len(column_names)):\n",
    "        for j in range(i + 1, len(column_names)):\n",
    "            pair = (column_names[i], column_names[j])\n",
    "            if pair not in compared_pairs:\n",
    "                rolling_corr = dataframe[column_names[i]].rolling(window=window).corr(dataframe[column_names[j]])\n",
    "\n",
    "                plt.figure(figsize=(10, 6))\n",
    "                plt.plot(rolling_corr, label='Rolling Correlation')\n",
    "                plt.title(f'Rolling Correlation between {column_names[i]} and {column_names[j]} over time')\n",
    "                plt.xlabel('Date')\n",
    "                plt.ylabel('Value of Correlation')\n",
    "                plt.legend()\n",
    "\n",
    "                # Automatically determine the best x-tick locations with a higher density\n",
    "                ax = plt.gca()  # Get the current axis\n",
    "\n",
    "                # Set major ticks to every 2 years\n",
    "                ax.xaxis.set_major_locator(mdates.YearLocator(2))  # Set the interval to 2 years\n",
    "\n",
    "                # Set date formatting for better readability\n",
    "                ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))\n",
    "\n",
    "                # Rotate x-tick labels for better readability\n",
    "                plt.xticks(rotation=75)\n",
    "\n",
    "                # Save the plot with tight bounding box to avoid cut-off issues\n",
    "                file_name = f\"{column_names[i]}_{column_names[j]}.{image_format}\"\n",
    "                file_path = os.path.join(folder_name, file_name)\n",
    "                plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "                plt.close()  # Close the plot to free up memory\n",
    "\n",
    "                compared_pairs.add(pair)\n",
    "\n",
    "    return f\"Plots successfully saved in the '{folder_name}' folder.\"\n",
    "\n",
    "#show_rolling_corr(df4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### AVERAGE VALUES OF THE CORRELATIONS OVER TWO YEARS\n",
    "Find the average value of the correlations over two years"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "def value_rolling_corr(dataframe, window=105, save_excel='no', excel_name='Rolling Correlation', cell_width=75):\n",
    "    column_names = list(dataframe.columns)  # Fetch column names directly from the dataframe\n",
    "    compared_pairs = set()  # Set to store already compared pairs\n",
    "    results = []  # List to store results\n",
    "\n",
    "    for i in range(len(column_names)):\n",
    "        for j in range(i + 1, len(column_names)):\n",
    "            pair = (column_names[i], column_names[j])\n",
    "            if pair not in compared_pairs:\n",
    "                rolling_corr = dataframe[column_names[i]].rolling(window=window).corr(dataframe[column_names[j]])\n",
    "                avg_roll_corr_over_2_years = rolling_corr.mean()\n",
    "                result_string = f\"Average rolling correlation over {window} periods between {column_names[i]} and {column_names[j]}: {avg_roll_corr_over_2_years}\"\n",
    "                results.append(result_string)\n",
    "\n",
    "                compared_pairs.add(pair)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Rolling Correlation Results'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, result in enumerate(results, start=1):\n",
    "            ws[f'A{i}'] = result\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return results\n",
    "\n",
    "#value_rolling_corr(df4, save_excel='no')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "def filter_2year_correlations_above_threshold(dataframe, window=105, threshold_small=0.5, save_excel='no', excel_name='Filtered Rolling Correlation', cell_width=75):\n",
    "    results = value_rolling_corr(dataframe, window=window)\n",
    "    filtered_results = []\n",
    "\n",
    "    for result in results:\n",
    "        corr_value = float(result.split(\":\")[-1].strip())\n",
    "        if corr_value > threshold_small or corr_value < -threshold_small:\n",
    "            filtered_results.append(result)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Filtered Rolling Correlation Results'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, result in enumerate(filtered_results, start=1):\n",
    "            ws[f'A{i}'] = result\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return filtered_results\n",
    "\n",
    "#filter_2year_correlations_above_threshold(df4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**GDP CQOQ Index and GDP CYOY Index**\n",
    "\n",
    "Average correlation over two years is ≈ 56%\n",
    "\n",
    "Global correlation over the dataset is ≈ 49%"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**GDP CYOY Index and GDP CURY Index**\n",
    "\n",
    "Average correlation over two years is ≈ 88%\n",
    "\n",
    "Global correlation over the dataset is ≈ 68%"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**LEI YoY Index and IP YoY Index**\n",
    "\n",
    "Average correlation over two years is ≈ 71%\n",
    "\n",
    "Global correlation over the dataset is ≈ 77%\n",
    "\n",
    "Overall graphs tend to have the same shape\n",
    "\n",
    "The LEI YoY Index is the precursor by about a year"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**CPTICHNG Index and IP YoY Index**\n",
    "\n",
    "Average correlation over two years is ≈ 62%\n",
    "\n",
    "Global correlation over the dataset is ≈ 64%\n",
    "\n",
    "Graphs fluctuate a bit but tend to have the same shapes\n",
    "\n",
    "The YoY Index has historically shown to be a bit precursive, though they have been really close since covid"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**LEI WKIJ Index and CPTICHNG Index**\n",
    "\n",
    "Average correlation over two years is ≈ -0.62%\n",
    "\n",
    "Global correlation over the dataset is ≈ -0.42%\n",
    "\n",
    "When the LEI Index goes up, the CPTICHNG Index tends to go down, whereas when the CPTICHNG Index goes up, the other tends to have a plateau or drop slightly"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Put them all in a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "def list_all_correlation_values_above_threshold_same_dates(window=105, threshold_small=0.5, save_excel='no', excel_name='Filtered Rolling Correlation', cell_width=75):\n",
    "    x = []\n",
    "    for i in range(len(dict_of_df)+1):\n",
    "        df_name = f\"df{i}\"\n",
    "        if df_name in globals():  #check if the dataframe variable exists in global scope\n",
    "            df = globals()[df_name]  #fetch the dataframe using globals()\n",
    "            x += filter_2year_correlations_above_threshold(df, window=window, threshold_small=threshold_small)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Filtered Rolling Correlation Results'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, result in enumerate(x, start=1):\n",
    "            ws[f'A{i}'] = result\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return x\n",
    "\n",
    "#list_all_correlation_values_above_threshold_same_dates()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_pairs_from_results_corr(window=105, threshold_small=0.5, save_excel='no', excel_name='Pairs', cell_width=75):\n",
    "    results = list_all_correlation_values_above_threshold_same_dates(window=window, threshold_small=threshold_small)\n",
    "    pairs = []\n",
    "    for result in results:\n",
    "        parts = result.split('between')[1].strip().split('and')\n",
    "        pair = (parts[0].strip(), parts[1].strip().split(':')[0].strip())\n",
    "        pairs.append(pair)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Pairs'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, pair in enumerate(pairs, start=1):\n",
    "            ws[f'A{i}'] = pair[0]\n",
    "            ws[f'B{i}'] = pair[1]\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return pairs\n",
    "\n",
    "#get_pairs_from_results(save_excel='yes')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "def retrieve_matrix_correlations_for_pairs(window=105, threshold_small=0.5, save_excel='no', excel_name='Matrix Correlations', cell_width=75):\n",
    "    pairs = get_pairs_from_results_corr(window=window, threshold_small=threshold_small)\n",
    "    pair_correlations = {}  #initialize outside the loop to accumulate results\n",
    "    for i in range(1, len(dict_of_df)+1):\n",
    "        df_name = f\"df{i}\"\n",
    "        if df_name in globals():  #check if the dataframe variable exists in global scope\n",
    "            df = globals()[df_name]\n",
    "            corr_matrix = df.corr()\n",
    "            for pair in pairs:\n",
    "                if pair[0] in df.columns and pair[1] in df.columns:\n",
    "                    pair_correlations[pair] = corr_matrix.loc[pair[0], pair[1]]\n",
    "    \n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Matrix Correlations'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, (pair, correlation) in enumerate(pair_correlations.items(), start=1):\n",
    "            ws[f'A{i}'] = pair[0]\n",
    "            ws[f'B{i}'] = pair[1]\n",
    "            ws[f'C{i}'] = correlation\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return pair_correlations\n",
    "\n",
    "\n",
    "#retrieve_matrix_correlations_for_pairs(save_excel='yes')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Compare correlation value over two years with the value in the correlation matrix for correlation values greater than 0.5 over two years"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "def collect_correlations_above_threshold(window=105, threshold_small=0.5, threshold_big = 0.7, save_excel='no', excel_name='Filtered Correlations', cell_width=75):\n",
    "    x = list_all_correlation_values_above_threshold_same_dates(window=window, threshold_small=threshold_small)\n",
    "    y = retrieve_matrix_correlations_for_pairs(window=window, threshold_small=threshold_small)\n",
    "    \n",
    "    #extracting the numeric parts from x and creating a list of tuples\n",
    "    grouped_values = []\n",
    "    for i in range(len(x)):\n",
    "        #assuming the format of x is \"title number\"\n",
    "        x_parts = x[i].split()\n",
    "        x_number = float(x_parts[-1])  #assuming the number is at the end\n",
    "        \n",
    "        #assuming y is a dictionary with tuples as keys and numbers as values\n",
    "        tuple_key = list(y.keys())[i]\n",
    "        tuple_key_str = ', '.join(map(str, tuple_key))  # Convert tuple key to comma-separated string\n",
    "\n",
    "        y_value = float(list(y.values())[i])  # Convert y value to float\n",
    "        \n",
    "        #create tuple string and append to grouped_values\n",
    "        tuple_string = f\"{tuple_key_str}: \"\n",
    "        grouped_values.append((tuple_string, x_number, y_value))\n",
    "\n",
    "    #create DataFrame with appropriate columns\n",
    "    df = pd.DataFrame(grouped_values, columns=['Variables being compared', 'Average correlation value over two years', 'Value in the correlation matrix'])\n",
    "\n",
    "    #set 'Variables being compared' column as index\n",
    "    df.set_index('Variables being compared', inplace=True)\n",
    "    df = df.transpose()\n",
    "\n",
    "    columns_to_keep = df.columns[df.iloc[1] >= threshold_big]\n",
    "    filtered_df = df[columns_to_keep]\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        filtered_df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return filtered_df\n",
    "\n",
    "#collect_correlations_above_threshold(save_excel='yes')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Isolate the ones  which have the least difference between the two (0.15 or less, you can choose how big the difference is)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_smallest_correlation_difference(number=1, window=105, threshold_small=0.5, threshold_big = 0.7, decimal = 3, save_excel='no', excel_name='Filtered Correlations', cell_width=75):\n",
    "    dfx = collect_correlations_above_threshold(window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "    columns_to_drop = []\n",
    "    \n",
    "    for col in dfx.columns:\n",
    "        if abs(dfx[col].diff().iloc[1]) >= number:\n",
    "            columns_to_drop.append(col)\n",
    "    \n",
    "    dfx.drop(columns=columns_to_drop, inplace=True)\n",
    "    dfx = dfx.round(decimal)\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Filtered Correlations'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, column in enumerate(dfx.columns, start=1):\n",
    "            ws[f'A{i}'] = column\n",
    "            for j, value in enumerate(dfx[column], start=2):\n",
    "                ws[f'{get_column_letter(i+1)}{j}'] = value\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    \n",
    "    return dfx\n",
    "\n",
    "#compute_smallest_correlation_difference()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Plot them against each other"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_close_corr_variable_pairs(number=1, window=105, threshold_small=0.5, threshold_big = 0.7, decimal = 3, save_excel='no', excel_name='Pairs above threshold corr difference', cell_width=75):\n",
    "    df = compute_smallest_correlation_difference(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    variable_pairs = []\n",
    "    \n",
    "    for col in df.columns:\n",
    "        # Split the column name by ', ' and add the resulting pair to the list\n",
    "        pair = col.split(', ')\n",
    "        pair[1] = pair[1].rstrip(': ')\n",
    "        variable_pairs.append((pair[0], pair[1]))\n",
    "\n",
    "    if save_excel ==\"yes\":\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Pairs above threshold corr difference'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, (var1, var2) in enumerate(variable_pairs, start=1):\n",
    "            ws[f'A{i}'] = var1\n",
    "            ws[f'B{i}'] = var2\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    \n",
    "    return variable_pairs\n",
    "\n",
    "#extract_close_corr_variable_pairs()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_close_corr_variable_pairs(number=1, window=105, threshold_small=0.5, threshold_big=0.7, decimal=3, folder_name='close_correlation_plots', image_format='png'):\n",
    "    variable_pairs = extract_close_corr_variable_pairs(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    dfx = collect_correlations_above_threshold(window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "\n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    for x, y in variable_pairs:\n",
    "        plotted = False\n",
    "        for df_name in dict_of_df:\n",
    "            if df_name in globals():  # Check if the dataframe variable exists in global scope\n",
    "                df = globals()[df_name]\n",
    "                if x in df.columns and y in df.columns:\n",
    "                    merged_df = df[[x, y]].dropna()\n",
    "                    merged_df.interpolate(method='time', inplace=True)\n",
    "                    common_index = merged_df.index\n",
    "                    if len(common_index) > 0:\n",
    "                        min_idx = common_index.min()\n",
    "                        max_idx = common_index.max()\n",
    "\n",
    "                        fig, ax1 = plt.subplots(figsize=(20, 10))\n",
    "\n",
    "                        ax1.set_xlabel('Time')\n",
    "                        ax1.set_ylabel(f'{x}', color='blue')\n",
    "                        ax1.plot(merged_df.index, merged_df[x], color='blue', label=f'{x}')\n",
    "                        ax1.tick_params(axis='y', labelcolor='blue')\n",
    "\n",
    "                        ax2 = ax1.twinx()\n",
    "                        ax2.set_ylabel(f'{y}', color='red')\n",
    "                        ax2.plot(merged_df.index, merged_df[y], color='red', label=f'{y}')\n",
    "                        ax2.tick_params(axis='y', labelcolor='red')\n",
    "\n",
    "                        ax1.set_xlim(min_idx, max_idx)\n",
    "\n",
    "                        # Set major ticks with a defined number of ticks\n",
    "                        ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=27))\n",
    "                        ax1.tick_params(axis='x', rotation=20)\n",
    "\n",
    "                        pair_key = f\"{x}, {y}: \"\n",
    "                        if pair_key in dfx.columns:\n",
    "                            avg_corr_value = dfx[pair_key]['Average correlation value over two years']\n",
    "                            matrix_corr_value = dfx[pair_key]['Value in the correlation matrix']\n",
    "                            annotation_text = f\"Avg Corr (2 years) ≈ {avg_corr_value:.{decimal}f}\\nMatrix Corr ≈ {matrix_corr_value:.{decimal}f}\"\n",
    "\n",
    "                            ax1.annotate(annotation_text, xy=(0.05, 0.95), xycoords='axes fraction',\n",
    "                                        fontsize=12, bbox=dict(boxstyle=\"round,pad=0.3\", edgecolor='black', facecolor='white'))\n",
    "\n",
    "                        plt.title(f'{x} and {y} over time')\n",
    "\n",
    "                        # Save the plot instead of showing it\n",
    "                        file_name = f\"{x}_{y}.{image_format}\"  # Create a filename based on variable names\n",
    "                        file_path = os.path.join(folder_name, file_name)\n",
    "                        plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "                        plt.close()  # Close the plot to free up memory\n",
    "                        plotted = True\n",
    "\n",
    "        if not plotted:\n",
    "            print(f\"Variables {x} and {y} not found in any dataframe.\")\n",
    "\n",
    "    return f\"Plots successfully saved in the '{folder_name}' folder.\"\n",
    "\n",
    "#plot_close_corr_variable_pairs()"
