"def show_rolling_cov(dataframe, window=105, folder_name='covariance_plots', image_format='png'):\n",
    "    column_names = return_column_names(dataframe)\n",
    "    compared_pairs = set()  # Set to store already compared pairs\n",
    "\n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    for i in range(len(column_names)):\n",
    "        for j in range(i + 1, len(column_names)):\n",
    "            pair = (column_names[i], column_names[j])\n",
    "            if pair not in compared_pairs:\n",
    "                rolling_cov = dataframe[column_names[i]].rolling(window=window).cov(dataframe[column_names[j]])\n",
    "\n",
    "                plt.figure(figsize=(10, 6))\n",
    "                plt.plot(rolling_cov, label='Rolling Covariance', color='blue')\n",
    "                plt.title(f'Rolling Covariance between {column_names[i]} and {column_names[j]} over time')\n",
    "                plt.xlabel('Date')\n",
    "                plt.ylabel('Value of Covariance')\n",
    "                plt.legend()\n",
    "                plt.tight_layout()\n",
    "\n",
    "                # Automatically determine the best x-tick positions\n",
    "                xtick_positions = rolling_cov.index[::100]  # Adjust the step value to your preference\n",
    "                xtick_labels = [date.strftime('%Y-%m-%d') for date in xtick_positions]  # Customize date format as needed\n",
    "                plt.xticks(ticks=xtick_positions, labels=xtick_labels, rotation=75)  # Rotate labels for better readability\n",
    "\n",
    "                # Save the plot instead of showing it\n",
    "                file_name = f\"{column_names[i]}_{column_names[j]}_cov.{image_format}\"  # Create a filename based on variable names\n",
    "                file_path = os.path.join(folder_name, file_name)\n",
    "                plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "                plt.close()  # Close the plot to free up memory\n",
    "\n",
    "                compared_pairs.add(pair)  # Add the pair to the set of compared pairs\n",
    "\n",
    "    return f\"Covariance plots successfully saved in the '{folder_name}' folder.\"\n",
    "\n",
    "#show_rolling_cov(df4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### AVERAGE VALUES OF THE COVARIANCES OVER TWO YEARS\n",
    "Find the average value of the covariancses over two years"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "def value_rolling_cov(dataframe, window=105):\n",
    "    column_names = list(dataframe.columns)  # Fetch column names directly from the dataframe\n",
    "    compared_pairs = set()  # Set to store already compared pairs\n",
    "    results = []  # List to store results\n",
    "\n",
    "    for i in range(len(column_names)):\n",
    "        for j in range(i + 1, len(column_names)):\n",
    "            pair = (column_names[i], column_names[j])\n",
    "            if pair not in compared_pairs:\n",
    "                rolling_cov = dataframe[column_names[i]].rolling(window=window).cov(dataframe[column_names[j]])\n",
    "                avg_roll_cov_over_2_years = rolling_cov.mean()\n",
    "                result_string = f\"Average rolling covariance over {window} periods between {column_names[i]} and {column_names[j]}: {avg_roll_cov_over_2_years}\"\n",
    "                results.append(result_string)\n",
    "\n",
    "                compared_pairs.add(pair)\n",
    "\n",
    "    return results\n",
    "\n",
    "#value_rolling_cov(df4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "def filter_2year_covariances_above_threshold(dataframe, window=105, threshold_small=0.5, save_excel='no', excel_name='Filtered Rolling Covariance', cell_width=75):\n",
    "    results = value_rolling_cov(dataframe, window=window)\n",
    "    filtered_results = []\n",
    "\n",
    "    for result in results:\n",
    "        cov_value = float(result.split(\":\")[-1].strip())\n",
    "        if cov_value > threshold_small or cov_value < -threshold_small:\n",
    "            filtered_results.append(result)\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Filtered Rolling Covariance Results'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, result in enumerate(filtered_results, start=1):\n",
    "            ws[f'A{i}'] = result\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "    return filtered_results\n",
    "\n",
    "#filter_covariances_above_threshold(df4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### PUT THEM ALL IN A LIST"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "def list_all_covariance_values_above_threshold_same_dates(window=105, threshold_small=0.5, save_excel='no', excel_name='Filtered Rolling Covariance', cell_width=75):\n",
    "    x = []\n",
    "    for i in range(len(dict_of_df)+1):\n",
    "        df_name = f\"df{i}\"\n",
    "        if df_name in globals():  # check if the dataframe variable exists in global scope\n",
    "            df = globals()[df_name]  # fetch the dataframe using globals()\n",
    "            x += filter_2year_covariances_above_threshold(df, window=window, threshold_small=threshold_small)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Filtered Rolling Covariance Results'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, result in enumerate(x, start=1):\n",
    "            ws[f'A{i}'] = result\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return x\n",
    "\n",
    "#list_all_covariance_values_above_threshold_same_dates()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_pairs_from_results_cov(window=105, threshold_small=0.5, save_excel='no', excel_name='Pairs', cell_width=75):\n",
    "    results = list_all_covariance_values_above_threshold_same_dates(window=window, threshold_small=threshold_small)\n",
    "    pairs = []\n",
    "    for result in results:\n",
    "        parts = result.split('between')[1].strip().split('and')\n",
    "        pair = (parts[0].strip(), parts[1].strip().split(':')[0].strip())\n",
    "        pairs.append(pair)\n",
    "    if save_excel == 'yes':\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Pairs'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, pair in enumerate(pairs, start=1):\n",
    "            ws[f'A{i}'] = pair[0]\n",
    "            ws[f'B{i}'] = pair[1]\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return pairs\n",
    "\n",
    "#get_pairs_from_results_cov(window=105, save_excel='no')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "def retrieve_matrix_covariances_for_pairs(window=105, threshold_small=0.5):\n",
    "    pairs = get_pairs_from_results_cov(list_all_covariance_values_above_threshold_same_dates(window=window, threshold_small=threshold_small))\n",
    "    pair_covariances = {}  # initialize outside the loop to accumulate results\n",
    "    for i in range(1, len(dict_of_df)+1):\n",
    "        df_name = f\"df{i}\"\n",
    "        if df_name in globals():  # check if the dataframe variable exists in global scope\n",
    "            df = globals()[df_name]\n",
    "            cov_matrix = df.cov()\n",
    "            for pair in pairs:\n",
    "                if pair[0] in df.columns and pair[1] in df.columns:\n",
    "                    pair_covariances[pair] = cov_matrix.loc[pair[0], pair[1]]\n",
    "    return pair_covariances\n",
    "\n",
    "#retrieve_matrix_covariances_for_pairs()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### COMPARE COVARIANCES VALUES OVER TWO YEARS WITH THE VALUES IN THE CORRELATION MATRIX FOR CORRELATION VALUES GREATER THAN 0.5 OVER TWO YEARS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "def collect_covariances_above_threshold(window=105, threshold_small=0.5, threshold_big=0.7):\n",
    "    x = list_all_covariance_values_above_threshold_same_dates(window=window, threshold_small=threshold_small)\n",
    "    cov_pairs = get_pairs_from_results_cov(x)\n",
    "    y = retrieve_matrix_covariances_for_pairs(cov_pairs)\n",
    "    \n",
    "    # extracting the numeric parts from x and creating a list of tuples\n",
    "    grouped_values = []\n",
    "    for i in range(len(x)):\n",
    "        # assuming the format of x is \"title number\"\n",
    "        x_parts = x[i].split()\n",
    "        x_number = float(x_parts[-1])  # assuming the number is at the end\n",
    "        \n",
    "        # assuming y is a dictionary with tuples as keys and numbers as values\n",
    "        tuple_key = list(y.keys())[i]\n",
    "        tuple_key_str = ', '.join(map(str, tuple_key))  # Convert tuple key to comma-separated string\n",
    "\n",
    "        y_value = float(list(y.values())[i])  # Convert y value to float\n",
    "        \n",
    "        # create tuple string and append to grouped_values\n",
    "        tuple_string = f\"{tuple_key_str}: \"\n",
    "        grouped_values.append((tuple_string, x_number, y_value))\n",
    "\n",
    "    # create DataFrame with appropriate columns\n",
    "    df = pd.DataFrame(grouped_values, columns=['Variables being compared', 'Average covariance value over two years', 'Value in the covariance matrix'])\n",
    "\n",
    "    # set 'Variables being compared' column as index\n",
    "    df.set_index('Variables being compared', inplace=True)\n",
    "    df = df.transpose()\n",
    "\n",
    "    columns_to_keep = df.columns[df.iloc[1] >= threshold_big]\n",
    "    filtered_df = df[columns_to_keep]\n",
    "\n",
    "    return filtered_df\n",
    "\n",
    "#collect_covariances_above_threshold()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_smallest_covariance_difference(number=1, window=105, threshold_small=0.5, threshold_big = 0.7):\n",
    "    dfx = collect_covariances_above_threshold(window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "    columns_to_drop = []\n",
    "    \n",
    "    for col in dfx.columns:\n",
    "        if abs(dfx[col].diff().iloc[1]) >= number:\n",
    "            columns_to_drop.append(col)\n",
    "    \n",
    "    dfx.drop(columns=columns_to_drop, inplace=True)\n",
    "    \n",
    "    return dfx\n",
    "\n",
    "#compute_smallest_covariance_difference(number=100000000000000000000000000000000000000)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### PLOT THEM AGAINST EACH OTHER"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_close_cov_variable_pairs(number=1, window=105, threshold_small=0.5, threshold_big = 0.7):\n",
    "    df = compute_smallest_covariance_difference(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "    variable_pairs = []\n",
    "    \n",
    "    for col in df.columns:\n",
    "        # Split the column name by ', ' and add the resulting pair to the list\n",
    "        pair = col.split(', ')\n",
    "        pair[1] = pair[1].rstrip(': ')\n",
    "        variable_pairs.append((pair[0], pair[1]))\n",
    "    \n",
    "    return variable_pairs\n",
    "\n",
    "#extract_close_cov_variable_pairs(number=10000000000000000000000000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_close_cov_variable_pairs(number=1, window=105, threshold_small=0.5, threshold_big=0.7, decimal=3, folder_name='close_covariance_plots', image_format='png'):\n",
    "    variable_pairs = extract_close_cov_variable_pairs(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "    dfx = collect_covariances_above_threshold(window=window, threshold_small=threshold_small, threshold_big=threshold_big)\n",
    "\n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    for x, y in variable_pairs:\n",
    "        plotted = False\n",
    "        for df_name in dict_of_df:\n",
    "            if df_name in globals():  # Check if the dataframe variable exists in global scope\n",
    "                df = globals()[df_name]\n",
    "                if x in df.columns and y in df.columns:\n",
    "                    merged_df = df[[x, y]].dropna()\n",
    "                    merged_df.interpolate(method='time', inplace=True)\n",
    "                    common_index = merged_df.index\n",
    "                    if len(common_index) > 0:\n",
    "                        min_idx = common_index.min()\n",
    "                        max_idx = common_index.max()\n",
    "\n",
    "                        fig, ax1 = plt.subplots(figsize=(20, 10))\n",
    "\n",
    "                        ax1.set_xlabel('Time')\n",
    "                        ax1.set_ylabel(f'{x}', color='blue')\n",
    "                        ax1.plot(merged_df.index, merged_df[x], color='blue', label=f'{x}')\n",
    "                        ax1.tick_params(axis='y', labelcolor='blue')\n",
    "\n",
    "                        ax2 = ax1.twinx()\n",
    "                        ax2.set_ylabel(f'{y}', color='red')\n",
    "                        ax2.plot(merged_df.index, merged_df[y], color='red', label=f'{y}')\n",
    "                        ax2.tick_params(axis='y', labelcolor='red')\n",
    "\n",
    "                        ax1.set_xlim(min_idx, max_idx)\n",
    "                        ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=27))\n",
    "                        ax1.tick_params(axis='x', rotation=20)\n",
    "\n",
    "                        pair_key = f\"{x}, {y}: \"\n",
    "                        if pair_key in dfx.columns:\n",
    "                            avg_cov_value = dfx[pair_key]['Average covariance value over two years']\n",
    "                            matrix_cov_value = dfx[pair_key]['Value in the covariance matrix']\n",
    "                            annotation_text = f\"Avg Cov (2 years) ≈ {avg_cov_value:.{decimal}f}\\nMatrix Cov ≈ {matrix_cov_value:.{decimal}f}\"\n",
    "\n",
    "                            ax1.annotate(annotation_text, xy=(0.05, 0.95), xycoords='axes fraction',\n",
    "                                        fontsize=12, bbox=dict(boxstyle=\"round,pad=0.3\", edgecolor='black', facecolor='white'))\n",
    "\n",
    "                        plt.title(f'{x} and {y} over time')\n",
    "\n",
    "                        # Save the plot instead of showing it\n",
    "                        file_name = f\"{x}_{y}_cov.{image_format}\"  # Create a filename based on variable names\n",
    "                        file_path = os.path.join(folder_name, file_name)\n",
    "                        plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "                        plt.close()  # Close the plot to free up memory\n",
    "                        plotted = True\n",
    "\n",
    "        if not plotted:\n",
    "            print(f\"Variables {x} and {y} not found in any dataframe.\")\n",
    "\n",
    "    return f\"Covariance plots successfully saved in the '{folder_name}' folder.\"\n",
    "\n",
    "#plot_close_cov_variable_pairs(window=1)"
