 "current_directory = os.getcwd()\n",
    "\n",
    "def load_and_preview_csv(file_name):\n",
    "    # Get the current working directory\n",
    "    \n",
    "    # Construct the full file path\n",
    "    file_path = os.path.join(current_directory, file_name)\n",
    "    \n",
    "    # Read the CSV file with the specified delimiter\n",
    "    df = pd.read_csv(file_path, delimiter=';', low_memory=False)\n",
    "    \n",
    "    # Return the first few rows of the dataframe\n",
    "    return df\n",
    "global df\n",
    "df = load_and_preview_csv(\"Data_in_value.csv\")"
