"def rename_columns(df):\n",
    "    \"\"\"\n",
    "    Renames the columns of the given DataFrame based on the provided correspondence dictionary.\n",
    "\n",
    "    Parameters:\n",
    "    df (pd.DataFrame): The DataFrame whose columns need to be renamed.\n",
    "    correspondance_dict (dict): A dictionary where keys are original column names and values are the new column names.\n",
    "\n",
    "    Returns:\n",
    "    pd.DataFrame: The DataFrame with updated column names.\n",
    "    \"\"\"\n",
    "    # Initialize an empty list to store the new column names\n",
    "    new_columns = []\n",
    "    \n",
    "    # Iterate over the columns of the DataFrame\n",
    "    for col in df.columns:\n",
    "        # If the column name is in the dictionary, use the corresponding new name\n",
    "        if col in correspondance_dict:\n",
    "            new_columns.append(correspondance_dict[col])\n",
    "        else:\n",
    "            # Otherwise, keep the original column name\n",
    "            new_columns.append(col)\n",
    "    \n",
    "    # Assign the new column names to the DataFrame\n",
    "    df.columns = new_columns\n",
    "    \n",
    "    # Return the DataFrame with the updated column names\n",
    "    return df\n",
    "\n",
    "rename_columns(df=df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def correct_and_save_columns(df, output_file_name):\n",
    "    \"\"\"\n",
    "    Swaps every two adjacent columns and updates their names according to a specific pattern,\n",
    "    then saves the corrected DataFrame to a CSV file.\n",
    "\n",
    "    Parameters:\n",
    "    df (pd.DataFrame): The DataFrame whose columns need to be corrected.\n",
    "    output_file (str): The name of the output CSV file to save the corrected DataFrame.\n",
    "\n",
    "    Returns:\n",
    "    pd.DataFrame: The DataFrame with corrected column names.\n",
    "    \"\"\"\n",
    "    # Get the original column names as a list\n",
    "    original_columns = df.columns.tolist()\n",
    "    \n",
    "    # Create a copy of the original column names to modify\n",
    "    corrected_columns = original_columns.copy()\n",
    "    \n",
    "    # Swap every two adjacent column names\n",
    "    for i in range(0, len(original_columns), 2):\n",
    "        if i + 1 < len(original_columns):\n",
    "            corrected_columns[i], corrected_columns[i + 1] = original_columns[i + 1], original_columns[i]\n",
    "    \n",
    "    # Update the names of every two adjacent columns\n",
    "    for i in range(0, len(corrected_columns), 2):\n",
    "        if i + 1 < len(corrected_columns):\n",
    "            corrected_columns[i] = f'Dates for {corrected_columns[i + 1]}'\n",
    "    \n",
    "    # Set the corrected column names to the DataFrame\n",
    "    df.columns = corrected_columns\n",
    "    \n",
    "    # Save the corrected DataFrame to a new CSV file\n",
    "    df.to_csv(f\"{output_file_name}.csv\", index=False)\n",
    "    return df\n",
    "\n",
    "df = correct_and_save_columns(df=df, output_file_name=\"corrected_file\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Dates for GDP US Chained Dollars QoQ SAA (GDP)</th>\n",
       "      <th>GDP US Chained Dollars QoQ SAA (GDP)</th>\n",
       "      <th>Dates for GDP US Chained Dollars YoY SA (GDP)</th>\n",
       "      <th>GDP US Chained Dollars YoY SA (GDP)</th>\n",
       "      <th>Dates for US GDP Nominal Dollars YoY SA (GDP)</th>\n",
       "      <th>US GDP Nominal Dollars YoY SA (GDP)</th>\n",
       "      <th>Dates for US GDP Price Index QoQ SAAR (GDP)</th>\n",
       "      <th>US GDP Price Index QoQ SAAR (GDP)</th>\n",
       "      <th>Dates for U-3 US Unemployment Rate Total (Employment)</th>\n",
       "      <th>U-3 US Unemployment Rate Total (Employment)</th>\n",
       "      <th>...</th>\n",
       "      <th>Dates for Energie (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Energie (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Utilities (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Utilities (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Matières premières (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Matières premières (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Immobilier (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Immobilier (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Unnamed: 116</th>\n",
       "      <th>Unnamed: 116</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>31/03/1970</td>\n",
       "      <td>-0.6</td>\n",
       "      <td>31/03/1970</td>\n",
       "      <td>0.3</td>\n",
       "      <td>31/03/1970</td>\n",
       "      <td>5.8</td>\n",
       "      <td>31/03/1970</td>\n",
       "      <td>5.6</td>\n",
       "      <td>31/01/1970</td>\n",
       "      <td>3.9</td>\n",
       "      <td>...</td>\n",
       "      <td>29/09/1989</td>\n",
       "      <td>82.42</td>\n",
       "      <td>29/09/1989</td>\n",
       "      <td>95.71</td>\n",
       "      <td>29/09/1989</td>\n",
       "      <td>78.80</td>\n",
       "      <td>31/12/2001</td>\n",
       "      <td>97.15</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>30/06/1970</td>\n",
       "      <td>0.6</td>\n",
       "      <td>30/06/1970</td>\n",
       "      <td>0.2</td>\n",
       "      <td>30/06/1970</td>\n",
       "      <td>5.8</td>\n",
       "      <td>30/06/1970</td>\n",
       "      <td>5.9</td>\n",
       "      <td>28/02/1970</td>\n",
       "      <td>4.2</td>\n",
       "      <td>...</td>\n",
       "      <td>29/12/1989</td>\n",
       "      <td>91.62</td>\n",
       "      <td>29/12/1989</td>\n",
       "      <td>103.76</td>\n",
       "      <td>29/12/1989</td>\n",
       "      <td>78.08</td>\n",
       "      <td>29/03/2002</td>\n",
       "      <td>96.29</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>30/09/1970</td>\n",
       "      <td>3.7</td>\n",
       "      <td>30/09/1970</td>\n",
       "      <td>0.4</td>\n",
       "      <td>30/09/1970</td>\n",
       "      <td>5.4</td>\n",
       "      <td>30/09/1970</td>\n",
       "      <td>3.3</td>\n",
       "      <td>31/03/1970</td>\n",
       "      <td>4.4</td>\n",
       "      <td>...</td>\n",
       "      <td>30/03/1990</td>\n",
       "      <td>90.07</td>\n",
       "      <td>30/03/1990</td>\n",
       "      <td>95.70</td>\n",
       "      <td>30/03/1990</td>\n",
       "      <td>73.57</td>\n",
       "      <td>28/06/2002</td>\n",
       "      <td>97.62</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>31/12/1970</td>\n",
       "      <td>-4.2</td>\n",
       "      <td>31/12/1970</td>\n",
       "      <td>-0.2</td>\n",
       "      <td>31/12/1970</td>\n",
       "      <td>4.9</td>\n",
       "      <td>31/12/1970</td>\n",
       "      <td>5.3</td>\n",
       "      <td>30/04/1970</td>\n",
       "      <td>4.6</td>\n",
       "      <td>...</td>\n",
       "      <td>29/06/1990</td>\n",
       "      <td>89.83</td>\n",
       "      <td>29/06/1990</td>\n",
       "      <td>94.69</td>\n",
       "      <td>29/06/1990</td>\n",
       "      <td>72.67</td>\n",
       "      <td>30/09/2002</td>\n",
       "      <td>83.37</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>31/03/1971</td>\n",
       "      <td>11.3</td>\n",
       "      <td>31/03/1971</td>\n",
       "      <td>2.7</td>\n",
       "      <td>31/03/1971</td>\n",
       "      <td>8.0</td>\n",
       "      <td>31/03/1971</td>\n",
       "      <td>6.2</td>\n",
       "      <td>31/05/1970</td>\n",
       "      <td>4.8</td>\n",
       "      <td>...</td>\n",
       "      <td>28/09/1990</td>\n",
       "      <td>93.06</td>\n",
       "      <td>28/09/1990</td>\n",
       "      <td>88.08</td>\n",
       "      <td>28/09/1990</td>\n",
       "      <td>61.51</td>\n",
       "      <td>31/12/2002</td>\n",
       "      <td>82.48</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13828</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13829</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13830</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13831</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13832</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>13833 rows × 118 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Dates for GDP US Chained Dollars QoQ SAA (GDP)  \\\n",
       "0                                         31/03/1970   \n",
       "1                                         30/06/1970   \n",
       "2                                         30/09/1970   \n",
       "3                                         31/12/1970   \n",
       "4                                         31/03/1971   \n",
       "...                                              ...   \n",
       "13828                                            NaN   \n",
       "13829                                            NaN   \n",
       "13830                                            NaN   \n",
       "13831                                            NaN   \n",
       "13832                                            NaN   \n",
       "\n",
       "       GDP US Chained Dollars QoQ SAA (GDP)  \\\n",
       "0                                      -0.6   \n",
       "1                                       0.6   \n",
       "2                                       3.7   \n",
       "3                                      -4.2   \n",
       "4                                      11.3   \n",
       "...                                     ...   \n",
       "13828                                   NaN   \n",
       "13829                                   NaN   \n",
       "13830                                   NaN   \n",
       "13831                                   NaN   \n",
       "13832                                   NaN   \n",
       "\n",
       "      Dates for GDP US Chained Dollars YoY SA (GDP)  \\\n",
       "0                                        31/03/1970   \n",
       "1                                        30/06/1970   \n",
       "2                                        30/09/1970   \n",
       "3                                        31/12/1970   \n",
       "4                                        31/03/1971   \n",
       "...                                             ...   \n",
       "13828                                           NaN   \n",
       "13829                                           NaN   \n",
       "13830                                           NaN   \n",
       "13831                                           NaN   \n",
       "13832                                           NaN   \n",
       "\n",
       "       GDP US Chained Dollars YoY SA (GDP)  \\\n",
       "0                                      0.3   \n",
       "1                                      0.2   \n",
       "2                                      0.4   \n",
       "3                                     -0.2   \n",
       "4                                      2.7   \n",
       "...                                    ...   \n",
       "13828                                  NaN   \n",
       "13829                                  NaN   \n",
       "13830                                  NaN   \n",
       "13831                                  NaN   \n",
       "13832                                  NaN   \n",
       "\n",
       "      Dates for US GDP Nominal Dollars YoY SA (GDP)  \\\n",
       "0                                        31/03/1970   \n",
       "1                                        30/06/1970   \n",
       "2                                        30/09/1970   \n",
       "3                                        31/12/1970   \n",
       "4                                        31/03/1971   \n",
       "...                                             ...   \n",
       "13828                                           NaN   \n",
       "13829                                           NaN   \n",
       "13830                                           NaN   \n",
       "13831                                           NaN   \n",
       "13832                                           NaN   \n",
       "\n",
       "       US GDP Nominal Dollars YoY SA (GDP)  \\\n",
       "0                                      5.8   \n",
       "1                                      5.8   \n",
       "2                                      5.4   \n",
       "3                                      4.9   \n",
       "4                                      8.0   \n",
       "...                                    ...   \n",
       "13828                                  NaN   \n",
       "13829                                  NaN   \n",
       "13830                                  NaN   \n",
       "13831                                  NaN   \n",
       "13832                                  NaN   \n",
       "\n",
       "      Dates for US GDP Price Index QoQ SAAR (GDP)  \\\n",
       "0                                      31/03/1970   \n",
       "1                                      30/06/1970   \n",
       "2                                      30/09/1970   \n",
       "3                                      31/12/1970   \n",
       "4                                      31/03/1971   \n",
       "...                                           ...   \n",
       "13828                                         NaN   \n",
       "13829                                         NaN   \n",
       "13830                                         NaN   \n",
       "13831                                         NaN   \n",
       "13832                                         NaN   \n",
       "\n",
       "       US GDP Price Index QoQ SAAR (GDP)  \\\n",
       "0                                    5.6   \n",
       "1                                    5.9   \n",
       "2                                    3.3   \n",
       "3                                    5.3   \n",
       "4                                    6.2   \n",
       "...                                  ...   \n",
       "13828                                NaN   \n",
       "13829                                NaN   \n",
       "13830                                NaN   \n",
       "13831                                NaN   \n",
       "13832                                NaN   \n",
       "\n",
       "      Dates for U-3 US Unemployment Rate Total (Employment)  \\\n",
       "0                                             31/01/1970      \n",
       "1                                             28/02/1970      \n",
       "2                                             31/03/1970      \n",
       "3                                             30/04/1970      \n",
       "4                                             31/05/1970      \n",
       "...                                                  ...      \n",
       "13828                                                NaN      \n",
       "13829                                                NaN      \n",
       "13830                                                NaN      \n",
       "13831                                                NaN      \n",
       "13832                                                NaN      \n",
       "\n",
       "       U-3 US Unemployment Rate Total (Employment)  ...  \\\n",
       "0                                              3.9  ...   \n",
       "1                                              4.2  ...   \n",
       "2                                              4.4  ...   \n",
       "3                                              4.6  ...   \n",
       "4                                              4.8  ...   \n",
       "...                                            ...  ...   \n",
       "13828                                          NaN  ...   \n",
       "13829                                          NaN  ...   \n",
       "13830                                          NaN  ...   \n",
       "13831                                          NaN  ...   \n",
       "13832                                          NaN  ...   \n",
       "\n",
       "      Dates for Energie (Sub S&P500 Indicator)  \\\n",
       "0                                   29/09/1989   \n",
       "1                                   29/12/1989   \n",
       "2                                   30/03/1990   \n",
       "3                                   29/06/1990   \n",
       "4                                   28/09/1990   \n",
       "...                                        ...   \n",
       "13828                                      NaN   \n",
       "13829                                      NaN   \n",
       "13830                                      NaN   \n",
       "13831                                      NaN   \n",
       "13832                                      NaN   \n",
       "\n",
       "       Energie (Sub S&P500 Indicator)  \\\n",
       "0                               82.42   \n",
       "1                               91.62   \n",
       "2                               90.07   \n",
       "3                               89.83   \n",
       "4                               93.06   \n",
       "...                               ...   \n",
       "13828                             NaN   \n",
       "13829                             NaN   \n",
       "13830                             NaN   \n",
       "13831                             NaN   \n",
       "13832                             NaN   \n",
       "\n",
       "      Dates for Utilities (Sub S&P500 Indicator)  \\\n",
       "0                                     29/09/1989   \n",
       "1                                     29/12/1989   \n",
       "2                                     30/03/1990   \n",
       "3                                     29/06/1990   \n",
       "4                                     28/09/1990   \n",
       "...                                          ...   \n",
       "13828                                        NaN   \n",
       "13829                                        NaN   \n",
       "13830                                        NaN   \n",
       "13831                                        NaN   \n",
       "13832                                        NaN   \n",
       "\n",
       "       Utilities (Sub S&P500 Indicator)  \\\n",
       "0                                 95.71   \n",
       "1                                103.76   \n",
       "2                                 95.70   \n",
       "3                                 94.69   \n",
       "4                                 88.08   \n",
       "...                                 ...   \n",
       "13828                               NaN   \n",
       "13829                               NaN   \n",
       "13830                               NaN   \n",
       "13831                               NaN   \n",
       "13832                               NaN   \n",
       "\n",
       "      Dates for Matières premières (Sub S&P500 Indicator)  \\\n",
       "0                                             29/09/1989    \n",
       "1                                             29/12/1989    \n",
       "2                                             30/03/1990    \n",
       "3                                             29/06/1990    \n",
       "4                                             28/09/1990    \n",
       "...                                                  ...    \n",
       "13828                                                NaN    \n",
       "13829                                                NaN    \n",
       "13830                                                NaN    \n",
       "13831                                                NaN    \n",
       "13832                                                NaN    \n",
       "\n",
       "       Matières premières (Sub S&P500 Indicator)  \\\n",
       "0                                          78.80   \n",
       "1                                          78.08   \n",
       "2                                          73.57   \n",
       "3                                          72.67   \n",
       "4                                          61.51   \n",
       "...                                          ...   \n",
       "13828                                        NaN   \n",
       "13829                                        NaN   \n",
       "13830                                        NaN   \n",
       "13831                                        NaN   \n",
       "13832                                        NaN   \n",
       "\n",
       "      Dates for Immobilier (Sub S&P500 Indicator)  \\\n",
       "0                                      31/12/2001   \n",
       "1                                      29/03/2002   \n",
       "2                                      28/06/2002   \n",
       "3                                      30/09/2002   \n",
       "4                                      31/12/2002   \n",
       "...                                           ...   \n",
       "13828                                         NaN   \n",
       "13829                                         NaN   \n",
       "13830                                         NaN   \n",
       "13831                                         NaN   \n",
       "13832                                         NaN   \n",
       "\n",
       "       Immobilier (Sub S&P500 Indicator) Dates for Unnamed: 116  Unnamed: 116  \n",
       "0                                  97.15                    NaN           NaN  \n",
       "1                                  96.29                    NaN           NaN  \n",
       "2                                  97.62                    NaN           NaN  \n",
       "3                                  83.37                    NaN           NaN  \n",
       "4                                  82.48                    NaN           NaN  \n",
       "...                                  ...                    ...           ...  \n",
       "13828                                NaN                    NaN           NaN  \n",
       "13829                                NaN                    NaN           NaN  \n",
       "13830                                NaN                    NaN           NaN  \n",
       "13831                                NaN                    NaN           NaN  \n",
       "13832                                NaN                    NaN           NaN  \n",
       "\n",
       "[13833 rows x 118 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Some excel functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def adjust_dimensions(wb, max_column_width=50):\n",
    "    # Adjust column widths\n",
    "    for ws in wb.worksheets:\n",
    "        # Freeze the first row and the first column\n",
    "        ws.freeze_panes = ws['B2']  # Freezes everything above and to the left of B2 (i.e., row 1 and column 1)\n",
    "        \n",
    "        column_lengths = {}\n",
    "        for row in ws.iter_rows():\n",
    "            for cell in row:\n",
    "                if cell.value is not None:\n",
    "                    # Center align the cell content and enable text wrapping\n",
    "                    cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)\n",
    "                    \n",
    "                    column_letter = get_column_letter(cell.column)\n",
    "                    if column_letter not in column_lengths:\n",
    "                        column_lengths[column_letter] = 0\n",
    "                    cell_length = len(str(cell.value))\n",
    "                    if cell_length > column_lengths[column_letter]:\n",
    "                        column_lengths[column_letter] = cell_length\n",
    "\n",
    "        for col, length in column_lengths.items():\n",
    "            # Set the width but cap it at the max_column_width\n",
    "            if length + 2 > max_column_width:\n",
    "                ws.column_dimensions[col].width = max_column_width\n",
    "            else:\n",
    "                ws.column_dimensions[col].width = length + 2  # Add buffer for padding\n",
    "\n",
    "        # Adjust row heights considering text wrapping\n",
    "        row_heights = {}\n",
    "        for row in ws.iter_rows():\n",
    "            row_number = row[0].row\n",
    "            max_height = 0\n",
    "            for cell in row:\n",
    "                if cell.value is not None:\n",
    "                    cell_value = str(cell.value)\n",
    "                    # Estimate the number of lines after wrapping\n",
    "                    wrapped_text = cell_value.splitlines()\n",
    "                    line_count = 0\n",
    "                    for line in wrapped_text:\n",
    "                        # Calculate how many lines this piece of text would occupy\n",
    "                        wrapped_lines = max(1, (len(line) // max_column_width) + 1)\n",
    "                        line_count += wrapped_lines\n",
    "                    if line_count > max_height:\n",
    "                        max_height = line_count\n",
    "            row_heights[row_number] = max_height * 15  # Approximate row height based on line count\n",
    "\n",
    "        for row_number, height in row_heights.items():\n",
    "            ws.row_dimensions[row_number].height = height"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Group them by dates - have all values with contiguous dates be grouped together"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Convert all date columns to date formats"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Dates for GDP US Chained Dollars QoQ SAA (GDP)</th>\n",
       "      <th>GDP US Chained Dollars QoQ SAA (GDP)</th>\n",
       "      <th>Dates for GDP US Chained Dollars YoY SA (GDP)</th>\n",
       "      <th>GDP US Chained Dollars YoY SA (GDP)</th>\n",
       "      <th>Dates for US GDP Nominal Dollars YoY SA (GDP)</th>\n",
       "      <th>US GDP Nominal Dollars YoY SA (GDP)</th>\n",
       "      <th>Dates for US GDP Price Index QoQ SAAR (GDP)</th>\n",
       "      <th>US GDP Price Index QoQ SAAR (GDP)</th>\n",
       "      <th>Dates for U-3 US Unemployment Rate Total (Employment)</th>\n",
       "      <th>U-3 US Unemployment Rate Total (Employment)</th>\n",
       "      <th>...</th>\n",
       "      <th>Dates for Energie (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Energie (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Utilities (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Utilities (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Matières premières (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Matières premières (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Immobilier (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Immobilier (Sub S&amp;P500 Indicator)</th>\n",
       "      <th>Dates for Unnamed: 116</th>\n",
       "      <th>Unnamed: 116</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1970-03-31</td>\n",
       "      <td>-0.6</td>\n",
       "      <td>1970-03-31</td>\n",
       "      <td>0.3</td>\n",
       "      <td>1970-03-31</td>\n",
       "      <td>5.8</td>\n",
       "      <td>1970-03-31</td>\n",
       "      <td>5.6</td>\n",
       "      <td>1970-01-31</td>\n",
       "      <td>3.9</td>\n",
       "      <td>...</td>\n",
       "      <td>1989-09-29</td>\n",
       "      <td>82.42</td>\n",
       "      <td>1989-09-29</td>\n",
       "      <td>95.71</td>\n",
       "      <td>1989-09-29</td>\n",
       "      <td>78.80</td>\n",
       "      <td>2001-12-31</td>\n",
       "      <td>97.15</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1970-06-30</td>\n",
       "      <td>0.6</td>\n",
       "      <td>1970-06-30</td>\n",
       "      <td>0.2</td>\n",
       "      <td>1970-06-30</td>\n",
       "      <td>5.8</td>\n",
       "      <td>1970-06-30</td>\n",
       "      <td>5.9</td>\n",
       "      <td>1970-02-28</td>\n",
       "      <td>4.2</td>\n",
       "      <td>...</td>\n",
       "      <td>1989-12-29</td>\n",
       "      <td>91.62</td>\n",
       "      <td>1989-12-29</td>\n",
       "      <td>103.76</td>\n",
       "      <td>1989-12-29</td>\n",
       "      <td>78.08</td>\n",
       "      <td>2002-03-29</td>\n",
       "      <td>96.29</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1970-09-30</td>\n",
       "      <td>3.7</td>\n",
       "      <td>1970-09-30</td>\n",
       "      <td>0.4</td>\n",
       "      <td>1970-09-30</td>\n",
       "      <td>5.4</td>\n",
       "      <td>1970-09-30</td>\n",
       "      <td>3.3</td>\n",
       "      <td>1970-03-31</td>\n",
       "      <td>4.4</td>\n",
       "      <td>...</td>\n",
       "      <td>1990-03-30</td>\n",
       "      <td>90.07</td>\n",
       "      <td>1990-03-30</td>\n",
       "      <td>95.70</td>\n",
       "      <td>1990-03-30</td>\n",
       "      <td>73.57</td>\n",
       "      <td>2002-06-28</td>\n",
       "      <td>97.62</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1970-12-31</td>\n",
       "      <td>-4.2</td>\n",
       "      <td>1970-12-31</td>\n",
       "      <td>-0.2</td>\n",
       "      <td>1970-12-31</td>\n",
       "      <td>4.9</td>\n",
       "      <td>1970-12-31</td>\n",
       "      <td>5.3</td>\n",
       "      <td>1970-04-30</td>\n",
       "      <td>4.6</td>\n",
       "      <td>...</td>\n",
       "      <td>1990-06-29</td>\n",
       "      <td>89.83</td>\n",
       "      <td>1990-06-29</td>\n",
       "      <td>94.69</td>\n",
       "      <td>1990-06-29</td>\n",
       "      <td>72.67</td>\n",
       "      <td>2002-09-30</td>\n",
       "      <td>83.37</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1971-03-31</td>\n",
       "      <td>11.3</td>\n",
       "      <td>1971-03-31</td>\n",
       "      <td>2.7</td>\n",
       "      <td>1971-03-31</td>\n",
       "      <td>8.0</td>\n",
       "      <td>1971-03-31</td>\n",
       "      <td>6.2</td>\n",
       "      <td>1970-05-31</td>\n",
       "      <td>4.8</td>\n",
       "      <td>...</td>\n",
       "      <td>1990-09-28</td>\n",
       "      <td>93.06</td>\n",
       "      <td>1990-09-28</td>\n",
       "      <td>88.08</td>\n",
       "      <td>1990-09-28</td>\n",
       "      <td>61.51</td>\n",
       "      <td>2002-12-31</td>\n",
       "      <td>82.48</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13828</th>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13829</th>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13830</th>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13831</th>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13832</th>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaT</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>13833 rows × 118 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Dates for GDP US Chained Dollars QoQ SAA (GDP)  \\\n",
       "0                                         1970-03-31   \n",
       "1                                         1970-06-30   \n",
       "2                                         1970-09-30   \n",
       "3                                         1970-12-31   \n",
       "4                                         1971-03-31   \n",
       "...                                              ...   \n",
       "13828                                            NaT   \n",
       "13829                                            NaT   \n",
       "13830                                            NaT   \n",
       "13831                                            NaT   \n",
       "13832                                            NaT   \n",
       "\n",
       "       GDP US Chained Dollars QoQ SAA (GDP)  \\\n",
       "0                                      -0.6   \n",
       "1                                       0.6   \n",
       "2                                       3.7   \n",
       "3                                      -4.2   \n",
       "4                                      11.3   \n",
       "...                                     ...   \n",
       "13828                                   NaN   \n",
       "13829                                   NaN   \n",
       "13830                                   NaN   \n",
       "13831                                   NaN   \n",
       "13832                                   NaN   \n",
       "\n",
       "      Dates for GDP US Chained Dollars YoY SA (GDP)  \\\n",
       "0                                        1970-03-31   \n",
       "1                                        1970-06-30   \n",
       "2                                        1970-09-30   \n",
       "3                                        1970-12-31   \n",
       "4                                        1971-03-31   \n",
       "...                                             ...   \n",
       "13828                                           NaT   \n",
       "13829                                           NaT   \n",
       "13830                                           NaT   \n",
       "13831                                           NaT   \n",
       "13832                                           NaT   \n",
       "\n",
       "       GDP US Chained Dollars YoY SA (GDP)  \\\n",
       "0                                      0.3   \n",
       "1                                      0.2   \n",
       "2                                      0.4   \n",
       "3                                     -0.2   \n",
       "4                                      2.7   \n",
       "...                                    ...   \n",
       "13828                                  NaN   \n",
       "13829                                  NaN   \n",
       "13830                                  NaN   \n",
       "13831                                  NaN   \n",
       "13832                                  NaN   \n",
       "\n",
       "      Dates for US GDP Nominal Dollars YoY SA (GDP)  \\\n",
       "0                                        1970-03-31   \n",
       "1                                        1970-06-30   \n",
       "2                                        1970-09-30   \n",
       "3                                        1970-12-31   \n",
       "4                                        1971-03-31   \n",
       "...                                             ...   \n",
       "13828                                           NaT   \n",
       "13829                                           NaT   \n",
       "13830                                           NaT   \n",
       "13831                                           NaT   \n",
       "13832                                           NaT   \n",
       "\n",
       "       US GDP Nominal Dollars YoY SA (GDP)  \\\n",
       "0                                      5.8   \n",
       "1                                      5.8   \n",
       "2                                      5.4   \n",
       "3                                      4.9   \n",
       "4                                      8.0   \n",
       "...                                    ...   \n",
       "13828                                  NaN   \n",
       "13829                                  NaN   \n",
       "13830                                  NaN   \n",
       "13831                                  NaN   \n",
       "13832                                  NaN   \n",
       "\n",
       "      Dates for US GDP Price Index QoQ SAAR (GDP)  \\\n",
       "0                                      1970-03-31   \n",
       "1                                      1970-06-30   \n",
       "2                                      1970-09-30   \n",
       "3                                      1970-12-31   \n",
       "4                                      1971-03-31   \n",
       "...                                           ...   \n",
       "13828                                         NaT   \n",
       "13829                                         NaT   \n",
       "13830                                         NaT   \n",
       "13831                                         NaT   \n",
       "13832                                         NaT   \n",
       "\n",
       "       US GDP Price Index QoQ SAAR (GDP)  \\\n",
       "0                                    5.6   \n",
       "1                                    5.9   \n",
       "2                                    3.3   \n",
       "3                                    5.3   \n",
       "4                                    6.2   \n",
       "...                                  ...   \n",
       "13828                                NaN   \n",
       "13829                                NaN   \n",
       "13830                                NaN   \n",
       "13831                                NaN   \n",
       "13832                                NaN   \n",
       "\n",
       "      Dates for U-3 US Unemployment Rate Total (Employment)  \\\n",
       "0                                             1970-01-31      \n",
       "1                                             1970-02-28      \n",
       "2                                             1970-03-31      \n",
       "3                                             1970-04-30      \n",
       "4                                             1970-05-31      \n",
       "...                                                  ...      \n",
       "13828                                                NaT      \n",
       "13829                                                NaT      \n",
       "13830                                                NaT      \n",
       "13831                                                NaT      \n",
       "13832                                                NaT      \n",
       "\n",
       "       U-3 US Unemployment Rate Total (Employment)  ...  \\\n",
       "0                                              3.9  ...   \n",
       "1                                              4.2  ...   \n",
       "2                                              4.4  ...   \n",
       "3                                              4.6  ...   \n",
       "4                                              4.8  ...   \n",
       "...                                            ...  ...   \n",
       "13828                                          NaN  ...   \n",
       "13829                                          NaN  ...   \n",
       "13830                                          NaN  ...   \n",
       "13831                                          NaN  ...   \n",
       "13832                                          NaN  ...   \n",
       "\n",
       "      Dates for Energie (Sub S&P500 Indicator)  \\\n",
       "0                                   1989-09-29   \n",
       "1                                   1989-12-29   \n",
       "2                                   1990-03-30   \n",
       "3                                   1990-06-29   \n",
       "4                                   1990-09-28   \n",
       "...                                        ...   \n",
       "13828                                      NaT   \n",
       "13829                                      NaT   \n",
       "13830                                      NaT   \n",
       "13831                                      NaT   \n",
       "13832                                      NaT   \n",
       "\n",
       "       Energie (Sub S&P500 Indicator)  \\\n",
       "0                               82.42   \n",
       "1                               91.62   \n",
       "2                               90.07   \n",
       "3                               89.83   \n",
       "4                               93.06   \n",
       "...                               ...   \n",
       "13828                             NaN   \n",
       "13829                             NaN   \n",
       "13830                             NaN   \n",
       "13831                             NaN   \n",
       "13832                             NaN   \n",
       "\n",
       "      Dates for Utilities (Sub S&P500 Indicator)  \\\n",
       "0                                     1989-09-29   \n",
       "1                                     1989-12-29   \n",
       "2                                     1990-03-30   \n",
       "3                                     1990-06-29   \n",
       "4                                     1990-09-28   \n",
       "...                                          ...   \n",
       "13828                                        NaT   \n",
       "13829                                        NaT   \n",
       "13830                                        NaT   \n",
       "13831                                        NaT   \n",
       "13832                                        NaT   \n",
       "\n",
       "       Utilities (Sub S&P500 Indicator)  \\\n",
       "0                                 95.71   \n",
       "1                                103.76   \n",
       "2                                 95.70   \n",
       "3                                 94.69   \n",
       "4                                 88.08   \n",
       "...                                 ...   \n",
       "13828                               NaN   \n",
       "13829                               NaN   \n",
       "13830                               NaN   \n",
       "13831                               NaN   \n",
       "13832                               NaN   \n",
       "\n",
       "      Dates for Matières premières (Sub S&P500 Indicator)  \\\n",
       "0                                             1989-09-29    \n",
       "1                                             1989-12-29    \n",
       "2                                             1990-03-30    \n",
       "3                                             1990-06-29    \n",
       "4                                             1990-09-28    \n",
       "...                                                  ...    \n",
       "13828                                                NaT    \n",
       "13829                                                NaT    \n",
       "13830                                                NaT    \n",
       "13831                                                NaT    \n",
       "13832                                                NaT    \n",
       "\n",
       "       Matières premières (Sub S&P500 Indicator)  \\\n",
       "0                                          78.80   \n",
       "1                                          78.08   \n",
       "2                                          73.57   \n",
       "3                                          72.67   \n",
       "4                                          61.51   \n",
       "...                                          ...   \n",
       "13828                                        NaN   \n",
       "13829                                        NaN   \n",
       "13830                                        NaN   \n",
       "13831                                        NaN   \n",
       "13832                                        NaN   \n",
       "\n",
       "      Dates for Immobilier (Sub S&P500 Indicator)  \\\n",
       "0                                      2001-12-31   \n",
       "1                                      2002-03-29   \n",
       "2                                      2002-06-28   \n",
       "3                                      2002-09-30   \n",
       "4                                      2002-12-31   \n",
       "...                                           ...   \n",
       "13828                                         NaT   \n",
       "13829                                         NaT   \n",
       "13830                                         NaT   \n",
       "13831                                         NaT   \n",
       "13832                                         NaT   \n",
       "\n",
       "       Immobilier (Sub S&P500 Indicator) Dates for Unnamed: 116  Unnamed: 116  \n",
       "0                                  97.15                    NaT           NaN  \n",
       "1                                  96.29                    NaT           NaN  \n",
       "2                                  97.62                    NaT           NaN  \n",
       "3                                  83.37                    NaT           NaN  \n",
       "4                                  82.48                    NaT           NaN  \n",
       "...                                  ...                    ...           ...  \n",
       "13828                                NaN                    NaT           NaN  \n",
       "13829                                NaN                    NaT           NaN  \n",
       "13830                                NaN                    NaT           NaN  \n",
       "13831                                NaN                    NaT           NaN  \n",
       "13832                                NaN                    NaT           NaN  \n",
       "\n",
       "[13833 rows x 118 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Iterate through the dataframe columns\n",
    "def convert_date_columns(df):\n",
    "    for i in range(0, len(df.columns), 2):  # Starting from 0 for zero-based indexing, step by 2 for odd columns\n",
    "        column = df.columns[i]\n",
    "        df[column] = pd.to_datetime(df[column], dayfirst= True)\n",
    "    return df\n",
    "df = convert_date_columns(df)\n",
    "\n",
    "df"
   ]
  }
