
  {
   "cell_type": "code",
   "execution_count": 124,
   "metadata": {},
   "outputs": [],
   "source": [
    "def put_all_in_dataframe_for_eco_cycle(smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W', sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes', save_excel = 'no', excel_name = 'all in dataframe for economic cycle', cell_width = 50):\n",
    "    df = combine_cycles_and_stds_trend()\n",
    "    if smooth_filter == 'yes':\n",
    "        if smooth_both_columns == 'no':\n",
    "            smoothed_df = df.copy()\n",
    "            smoothed_values = savgol_filter(df[df.columns[index_which_column_to_smooth]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[index_which_column_to_smooth]] = smoothed_values\n",
    "            df = smoothed_df\n",
    "        elif smooth_both_columns == 'yes':\n",
    "            smoothed_df = pd.DataFrame(index=df.index)\n",
    "            smoothed_values_1 = savgol_filter(df[df.columns[0]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[0]] = smoothed_values_1\n",
    "            smoothed_values_2 = savgol_filter(df[df.columns[1]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[1]] = smoothed_values_2\n",
    "            df = smoothed_df\n",
    "    economy_df = pd.DataFrame(list(numerical_dict_of_recessions_and_expansions_periods.items()), columns=['Date', 'Value'])\n",
    "    economy_df['Date'] = pd.to_datetime(economy_df['Date'])\n",
    "    economy_df['Value'] = pd.to_numeric(economy_df['Value'])\n",
    "    economy_df.rename(columns={\"Value\":\"Economic cycle\"}, inplace=True)\n",
    "    economy_df.set_index('Date', inplace=True)\n",
    "    if smooth_economic_cycle == 'yes':\n",
    "        smooth_economy = economy_df.copy()\n",
    "        smooth_values = savgol_filter(smooth_economy[smooth_economy.columns[0]], svgal_eco_cycle, eco_poly)\n",
    "        smooth_economy[smooth_economy.columns[0]] = smooth_values\n",
    "        economy_df = smooth_economy\n",
    "    \n",
    "    for i in range(len(dict_of_df)):\n",
    "        df_name = f'df{i+1}'\n",
    "        if df_name in globals():\n",
    "            our_df = globals()[df_name]\n",
    "            if \"FED FUNDS (FED)\" in our_df:\n",
    "                fed_df = our_df[[\"FED FUNDS (FED)\"]]\n",
    "            if \"S&P 500 (Stock Index)\" in our_df:\n",
    "                sp500_df = our_df[[\"S&P 500 (Stock Index)\"]]\n",
    "            if \"MSCI world (Stock Index)\" in our_df:\n",
    "                msci_df = our_df[[\"MSCI world (Stock Index)\"]]\n",
    "            if \"NASDAQ (Stock Index)\" in our_df:\n",
    "                nasdaq_df = our_df[[\"NASDAQ (Stock Index)\"]]\n",
    "            if \"Financial (Sub S&P500 Indicator)\" in our_df:\n",
    "                financial_sub_sp_ind = our_df[[\"Financial (Sub S&P500 Indicator)\"]]\n",
    "            if \"Information Technologie (Sub S&P500 Indicator)\" in our_df:\n",
    "                info_tech_sub_sp_ind = our_df[[\"Information Technologie (Sub S&P500 Indicator)\"]]\n",
    "            if \"Santé (Sub S&P500 Indicator)\" in our_df:\n",
    "                sante_sub_sp_ind = our_df[[\"Santé (Sub S&P500 Indicator)\"]]\n",
    "            if \"Consommation discrétionnaire (Sub S&P500 Indicator)\" in our_df:\n",
    "                conso_disc_sb_sp_ind = our_df[[\"Consommation discrétionnaire (Sub S&P500 Indicator)\"]]\n",
    "            if \"Communication (Sub S&P500 Indicator)\" in our_df:\n",
    "                commu_sub_sp_ind = our_df[[\"Communication (Sub S&P500 Indicator)\"]]\n",
    "            if \"Industrie (Sub S&P500 Indicator)\" in our_df:\n",
    "                industry_sub_sp_ind = our_df[[\"Industrie (Sub S&P500 Indicator)\"]]\n",
    "            if \"Consommation de base (Sub S&P500 Indicator)\" in our_df:\n",
    "                basic_conso_sub_sp_ind = our_df[[\"Consommation de base (Sub S&P500 Indicator)\"]]\n",
    "            if \"Energie (Sub S&P500 Indicator)\" in our_df:\n",
    "                energy_sub_sp_ind = our_df[[\"Energie (Sub S&P500 Indicator)\"]]\n",
    "            if \"Utilities (Sub S&P500 Indicator)\" in our_df:\n",
    "                utilities_sub_sp_ind = our_df[[\"Utilities (Sub S&P500 Indicator)\"]]\n",
    "            if \"Matières premières (Sub S&P500 Indicator)\" in our_df:\n",
    "                primary_materials_sub_sp_ind = our_df[[\"Matières premières (Sub S&P500 Indicator)\"]]\n",
    "            if \"Immobilier (Sub S&P500 Indicator)\" in our_df:\n",
    "                housing_sub_sp_ind = our_df[[\"Immobilier (Sub S&P500 Indicator)\"]]\n",
    "            \n",
    "    if sp_sub_ind_as_pctg == 'yes':\n",
    "        financial_sub_sp_ind = financial_sub_sp_ind.pct_change()*100\n",
    "        info_tech_sub_sp_ind = info_tech_sub_sp_ind.pct_change()*100\n",
    "        sante_sub_sp_ind = sante_sub_sp_ind.pct_change()*100\n",
    "        conso_disc_sb_sp_ind = conso_disc_sb_sp_ind.pct_change()*100\n",
    "        commu_sub_sp_ind = commu_sub_sp_ind.pct_change()*100\n",
    "        industry_sub_sp_ind = industry_sub_sp_ind.pct_change()*100\n",
    "        basic_conso_sub_sp_ind = basic_conso_sub_sp_ind.pct_change()*100\n",
    "        energy_sub_sp_ind = energy_sub_sp_ind.pct_change()*100\n",
    "        utilities_sub_sp_ind = utilities_sub_sp_ind.pct_change()*100\n",
    "        primary_materials_sub_sp_ind = primary_materials_sub_sp_ind.pct_change()*100\n",
    "        housing_sub_sp_ind = housing_sub_sp_ind.pct_change()*100\n",
    "        \n",
    "        financial_sub_sp_ind = financial_sub_sp_ind.dropna()\n",
    "        info_tech_sub_sp_ind = info_tech_sub_sp_ind.dropna()\n",
    "        sante_sub_sp_ind = sante_sub_sp_ind.dropna()\n",
    "        conso_disc_sb_sp_ind = conso_disc_sb_sp_ind.dropna()\n",
    "        commu_sub_sp_ind = commu_sub_sp_ind.dropna()\n",
    "        industry_sub_sp_ind = industry_sub_sp_ind.dropna()\n",
    "        basic_conso_sub_sp_ind = basic_conso_sub_sp_ind.dropna()\n",
    "        energy_sub_sp_ind = energy_sub_sp_ind.dropna()\n",
    "        utilities_sub_sp_ind = utilities_sub_sp_ind.dropna()\n",
    "        primary_materials_sub_sp_ind = primary_materials_sub_sp_ind.dropna()\n",
    "        housing_sub_sp_ind = housing_sub_sp_ind.dropna()\n",
    "    \n",
    "    if smooth_sp_sub_ind == 'yes':\n",
    "        smoothing_financial_sub_sp_ind = financial_sub_sp_ind.copy()\n",
    "        smoothed_financial_values = savgol_filter(smoothing_financial_sub_sp_ind[\"Financial (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_financial_sub_sp_ind[\"Financial (Sub S&P500 Indicator)\"] = smoothed_financial_values\n",
    "        financial_sub_sp_ind = smoothing_financial_sub_sp_ind\n",
    "\n",
    "        # Smoothing for info_tech_sub_sp_ind\n",
    "        smoothing_info_tech_sub_sp_ind = info_tech_sub_sp_ind.copy()\n",
    "        smoothed_info_tech_values = savgol_filter(smoothing_info_tech_sub_sp_ind[\"Information Technologie (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_info_tech_sub_sp_ind[\"Information Technologie (Sub S&P500 Indicator)\"] = smoothed_info_tech_values\n",
    "        info_tech_sub_sp_ind = smoothing_info_tech_sub_sp_ind\n",
    "\n",
    "        # Smoothing for sante_sub_sp_ind\n",
    "        smoothing_sante_sub_sp_ind = sante_sub_sp_ind.copy()\n",
    "        smoothed_sante_values = savgol_filter(smoothing_sante_sub_sp_ind[\"Santé (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_sante_sub_sp_ind[\"Santé (Sub S&P500 Indicator)\"] = smoothed_sante_values\n",
    "        sante_sub_sp_ind = smoothing_sante_sub_sp_ind\n",
    "\n",
    "        # Smoothing for conso_disc_sb_sp_ind\n",
    "        smoothing_conso_disc_sb_sp_ind = conso_disc_sb_sp_ind.copy()\n",
    "        smoothed_conso_disc_values = savgol_filter(smoothing_conso_disc_sb_sp_ind[\"Consommation discrétionnaire (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_conso_disc_sb_sp_ind[\"Consommation discrétionnaire (Sub S&P500 Indicator)\"] = smoothed_conso_disc_values\n",
    "        conso_disc_sb_sp_ind = smoothing_conso_disc_sb_sp_ind\n",
    "\n",
    "        # Smoothing for commu_sub_sp_ind\n",
    "        smoothing_commu_sub_sp_ind = commu_sub_sp_ind.copy()\n",
    "        smoothed_commu_values = savgol_filter(smoothing_commu_sub_sp_ind[\"Communication (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_commu_sub_sp_ind[\"Communication (Sub S&P500 Indicator)\"] = smoothed_commu_values\n",
    "        commu_sub_sp_ind = smoothing_commu_sub_sp_ind\n",
    "\n",
    "        # Smoothing for industry_sub_sp_ind\n",
    "        smoothing_industry_sub_sp_ind = industry_sub_sp_ind.copy()\n",
    "        smoothed_industry_values = savgol_filter(smoothing_industry_sub_sp_ind[\"Industrie (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_industry_sub_sp_ind[\"Industrie (Sub S&P500 Indicator)\"] = smoothed_industry_values\n",
    "        industry_sub_sp_ind = smoothing_industry_sub_sp_ind\n",
    "\n",
    "        # Smoothing for basic_conso_sub_sp_ind\n",
    "        smoothing_basic_conso_sub_sp_ind = basic_conso_sub_sp_ind.copy()\n",
    "        smoothed_basic_conso_values = savgol_filter(smoothing_basic_conso_sub_sp_ind[\"Consommation de base (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_basic_conso_sub_sp_ind[\"Consommation de base (Sub S&P500 Indicator)\"] = smoothed_basic_conso_values\n",
    "        basic_conso_sub_sp_ind = smoothing_basic_conso_sub_sp_ind\n",
    "\n",
    "        # Smoothing for energy_sub_sp_ind\n",
    "        smoothing_energy_sub_sp_ind = energy_sub_sp_ind.copy()\n",
    "        smoothed_energy_values = savgol_filter(smoothing_energy_sub_sp_ind[\"Energie (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_energy_sub_sp_ind[\"Energie (Sub S&P500 Indicator)\"] = smoothed_energy_values\n",
    "        energy_sub_sp_ind = smoothing_energy_sub_sp_ind\n",
    "\n",
    "        # Smoothing for utilities_sub_sp_ind\n",
    "        smoothing_utilities_sub_sp_ind = utilities_sub_sp_ind.copy()\n",
    "        smoothed_utilities_values = savgol_filter(smoothing_utilities_sub_sp_ind[\"Utilities (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_utilities_sub_sp_ind[\"Utilities (Sub S&P500 Indicator)\"] = smoothed_utilities_values\n",
    "        utilities_sub_sp_ind = smoothing_utilities_sub_sp_ind\n",
    "\n",
    "        # Smoothing for primary_materials_sub_sp_ind\n",
    "        smoothing_primary_materials_sub_sp_ind = primary_materials_sub_sp_ind.copy()\n",
    "        smoothed_primary_materials_values = savgol_filter(smoothing_primary_materials_sub_sp_ind[\"Matières premières (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_primary_materials_sub_sp_ind[\"Matières premières (Sub S&P500 Indicator)\"] = smoothed_primary_materials_values\n",
    "        primary_materials_sub_sp_ind = smoothing_primary_materials_sub_sp_ind\n",
    "\n",
    "        # Smoothing for housing_sub_sp_ind\n",
    "        smoothing_housing_sub_sp_ind = housing_sub_sp_ind.copy()\n",
    "        smoothed_housing_values = savgol_filter(smoothing_housing_sub_sp_ind[\"Immobilier (Sub S&P500 Indicator)\"], indices_window, indices_order)\n",
    "        smoothing_housing_sub_sp_ind[\"Immobilier (Sub S&P500 Indicator)\"] = smoothed_housing_values\n",
    "        housing_sub_sp_ind = smoothing_housing_sub_sp_ind\n",
    "\n",
    "    if fed_as_pctg == 'yes':\n",
    "        fed_df = fed_df.pct_change()*100\n",
    "        fed_df = fed_df.dropna()\n",
    "    if smooth_fed == 'yes':\n",
    "        smoothing_fed = fed_df.copy()\n",
    "        smooth_fed_values = savgol_filter(smoothing_fed[smoothing_fed.columns[0]], svgal_fed_cycle, fed_poly)\n",
    "        smoothing_fed[smoothing_fed.columns[0]] = smooth_fed_values\n",
    "        fed_df = smoothing_fed\n",
    "    \n",
    "    if sp_as_pctg == 'yes':\n",
    "        sp500_df = sp500_df.pct_change()*100\n",
    "        sp500_df = sp500_df.dropna()\n",
    "    if smooth_sp500 == 'yes':\n",
    "        smoothing_sp500 = sp500_df.copy()\n",
    "        smoothed_sp500_values = savgol_filter(smoothing_sp500[\"S&P 500 (Stock Index)\"], indices_window, indices_order)\n",
    "        smoothing_sp500[\"S&P 500 (Stock Index)\"] = smoothed_sp500_values\n",
    "        sp500_df = smoothing_sp500\n",
    "\n",
    "    if msci_as_pctg == 'yes':\n",
    "        msci_df = msci_df.pct_change()*100\n",
    "        msci_df = msci_df.dropna()\n",
    "    if smooth_msci == 'yes':\n",
    "        smoothing_msci = msci_df.copy()\n",
    "        smoothed_msci_values = savgol_filter(smoothing_msci[\"MSCI world (Stock Index)\"], indices_window, indices_order)\n",
    "        smoothing_msci[\"MSCI world (Stock Index)\"] = smoothed_msci_values\n",
    "        msci_df = smoothing_msci\n",
    "\n",
    "    if nasdaq_as_pctg == 'yes':\n",
    "        nasdaq_df = nasdaq_df.pct_change()*100\n",
    "        nasdaq_df = nasdaq_df.dropna()\n",
    "    if smooth_nasdaq == 'yes':\n",
    "        smoothing_nasdaq = nasdaq_df.copy()\n",
    "        smoothed_nasdaq_values = savgol_filter(smoothing_nasdaq[\"NASDAQ (Stock Index)\"], indices_window, indices_order)\n",
    "        smoothing_nasdaq[\"NASDAQ (Stock Index)\"] = smoothed_nasdaq_values\n",
    "        nasdaq_df = smoothing_nasdaq\n",
    "\n",
    "    strict_dfs_list = [df, fed_df, sp500_df, msci_df, nasdaq_df]\n",
    "    strict_dfs_list = [df.sort_index() for df in strict_dfs_list]\n",
    "    \n",
    "    # Create a common date range covering all indices from all DataFrames\n",
    "    max_end_date = max(df.index.max() for df in strict_dfs_list)\n",
    "    common_date_range = pd.date_range(start=df.index.min(), end=max_end_date, freq=freq)\n",
    "    \n",
    "    # Initialize combined DataFrame with the first DataFrame in the list\n",
    "    combined_strict_df = strict_dfs_list[0]#.reindex(common_date_range)\n",
    "    \n",
    "    # Merge the rest of the DataFrames using outer join\n",
    "    for dfs in strict_dfs_list[1:]:\n",
    "        dfs = dfs.reindex(common_date_range)\n",
    "        combined_strict_df = combined_strict_df.join(dfs, how='outer', rsuffix='_r')\n",
    "    \n",
    "    # Forward fill and backward fill missing values\n",
    "    combined_strict_df = combined_strict_df.ffill().bfill()\n",
    "\n",
    "    combined_strict_df = combined_strict_df.resample(freq).asfreq()\n",
    "\n",
    "\n",
    "    # List of dataframes for outer join\n",
    "    flexible_dfs_list = [economy_df, financial_sub_sp_ind, info_tech_sub_sp_ind, sante_sub_sp_ind, conso_disc_sb_sp_ind, commu_sub_sp_ind, industry_sub_sp_ind, basic_conso_sub_sp_ind, energy_sub_sp_ind, utilities_sub_sp_ind, primary_materials_sub_sp_ind, housing_sub_sp_ind]\n",
    "\n",
    "    for flexible_df in flexible_dfs_list:\n",
    "        flexible_df = flexible_df.reindex(common_date_range)\n",
    "        combined_strict_df = combined_strict_df.join(flexible_df, how='outer')\n",
    "\n",
    "    interpolated_df = combined_strict_df.interpolate(method='linear')\n",
    "\n",
    "    def fill_discrete_values(date, value_df):\n",
    "        # Find the latest value from value_df that is on or before the date\n",
    "        relevant_values = value_df[value_df.index <= date]\n",
    "        if not relevant_values.empty:\n",
    "            return relevant_values.iloc[-1]['Economic cycle']\n",
    "        else:\n",
    "            return None\n",
    "\n",
    "    interpolated_df['Economic cycle'] = interpolated_df.index.to_series().apply(lambda date: fill_discrete_values(date, economy_df))\n",
    "\n",
    "    # If you still want to drop rows with NaN values after interpolation\n",
    "    #interpolated_df.dropna(inplace=True)\n",
    "    if save_excel == 'yes':\n",
    "        # Save to Excel\n",
    "        interpolated_df.to_excel(f\"{excel_name}.xlsx\", index=False)\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    \n",
    "    return interpolated_df\n",
    "#put_all_in_dataframe_for_eco_cycle(smooth_economic_cycle='no')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "metadata": {},
   "outputs": [],
   "source": [
    "def statistics_of_economic_cycles(smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W', save_excel = 'no', excel_name = 'statistics of economic cycles', cell_width = 50):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, smooth_economic_cycle=smooth_economic_cycle, svgal_eco_cycle=svgal_eco_cycle, eco_poly=eco_poly, smooth_fed=smooth_fed, fed_as_pctg=fed_as_pctg, svgal_fed_cycle=svgal_fed_cycle, fed_poly=fed_poly, sp_as_pctg=sp_as_pctg, smooth_sp500=smooth_sp500, msci_as_pctg=msci_as_pctg, smooth_msci=smooth_msci, nasdaq_as_pctg=nasdaq_as_pctg, smooth_nasdaq=smooth_nasdaq, indices_window=indices_window, indices_order=indices_order, freq=freq)\n",
    "    levels = [-2, -1, 1, 2]\n",
    "\n",
    "    def categorize_level(value):\n",
    "        return min(levels, key=lambda x: abs(x - value))\n",
    "    df['Economic cycle'] = df['Economic cycle'].apply(categorize_level)\n",
    "\n",
    "    statistics_ = {level: {} for level in levels}\n",
    "    for level in levels:\n",
    "        subset = df[df['Economic cycle'] == level]\n",
    "        statistics_[level]['count'] = subset.shape[0]\n",
    "        statistics_[level]['mean'] = subset.mean()\n",
    "        statistics_[level]['median'] = subset.median()\n",
    "        statistics_[level]['std'] = subset.std()\n",
    "        statistics_[level]['min'] = subset.min()\n",
    "        statistics_[level]['max'] = subset.max()\n",
    "    stats_df = pd.DataFrame(statistics_)\n",
    "    stats_df.rename(columns={-2: \"Récession\", -1:\"Ralentissement\", 1:\"Croissance\", 2:\"Forte Croissance\"}, inplace=True)\n",
    "    if save_excel == 'yes':\n",
    "        # Save to Excel\n",
    "        stats_df.to_excel(f\"{excel_name}.xlsx\", index=False)\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return stats_df\n",
    "#statistics_of_economic_cycles(smooth_economic_cycle='no')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Analysis of the 6 months preceding a change in an economic cycle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Economic cycle\n",
    "\n",
    "def six_months_before_eco_cycle_change(smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W', save_excel = 'no', excel_name = '6 months before economic cycle change', cell_width = 50):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth, smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly, smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly, sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci, nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window, indices_order = indices_order, freq = freq)\n",
    "    alternations = []\n",
    "    last_alternation_index = 0\n",
    "    \n",
    "    for i in range(1, len(df)):\n",
    "        if df['Economic cycle'].iloc[i] != df['Economic cycle'].iloc[i-1]:\n",
    "            alternation_type = f\"{df['Economic cycle'].iloc[i-1]} to {df['Economic cycle'].iloc[i]}\"\n",
    "            end_date = df.index[i]\n",
    "            start_date = end_date - pd.DateOffset(months=6)\n",
    "            \n",
    "            # Adjust start_date if there was another alternation within the last 6 months\n",
    "            if df.index[last_alternation_index] > start_date:\n",
    "                start_date = df.index[last_alternation_index]\n",
    "            \n",
    "            prior_data = df[(df.index >= start_date) & (df.index < end_date)]\n",
    "            \n",
    "            stats = {}\n",
    "            for column in df.columns:\n",
    "                if column != 'Economic cycle':\n",
    "                    if not prior_data.empty:\n",
    "                        stats[f'Average for: {column}'] = prior_data[column].mean()\n",
    "                        stats[f'Median for: {column}'] = prior_data[column].median()\n",
    "                        stats[f'Max for: {column}'] = prior_data[column].max()\n",
    "                        stats[f'Min for: {column}'] = prior_data[column].min()\n",
    "                        stats[f'Standard deviation for: {column}'] = prior_data[column].std()\n",
    "\n",
    "                        mean_value = prior_data[column].mean()\n",
    "                        # Calculate the absolute deviations from the mean\n",
    "                        absolute_deviations = (prior_data[column] - mean_value).abs()\n",
    "                        # Calculate the mean of these absolute deviations\n",
    "                        mad_value = absolute_deviations.mean()\n",
    "                        # Store the result in the stats dictionary\n",
    "                        stats[f'Mean absolute difference for: {column}'] = mad_value\n",
    "\n",
    "                        stats[f'Difference between first and last for: {column}'] = prior_data[column].iloc[-1] - prior_data[column].iloc[0]\n",
    "                    else:\n",
    "                        stats[f'Average for: {column}'] = np.nan\n",
    "                        stats[f'Median for: {column}'] = np.nan\n",
    "                        stats[f'Max for: {column}'] = np.nan\n",
    "                        stats[f'Min for: {column}'] = np.nan\n",
    "                        stats[f'Standard deviation for: {column}'] = np.nan\n",
    "                        stats[f'Mean absolute deviation for: {column}'] = np.nan\n",
    "                        stats[f'Difference between first and last for: {column}'] = np.nan\n",
    "            \n",
    "            alternations.append({\n",
    "                'alternation_type': alternation_type,\n",
    "                'alternation_date': end_date,\n",
    "                **stats\n",
    "            })\n",
    "            last_alternation_index = i\n",
    "    \n",
    "    df_alternations = pd.DataFrame(alternations)\n",
    "\n",
    "    #df_alternations.set_index(\"alternation_type\", inplace = True)\n",
    "    #df_alternations = df_alternations.sort_index()\n",
    "    #df_alternations.to_excel(\"6 mois avant changement cycle éco.xlsx\")\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Save to Excel\n",
    "        df_alternations.to_excel(f\"{excel_name}.xlsx\", index=False)\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "\n",
    "    return df_alternations\n",
    "\n",
    "#six_months_before_eco_cycle_change()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_confidence_interval_t_distribution(group, confidence=0.95):\n",
    "    n = len(group)\n",
    "    mean = np.mean(group)\n",
    "    sem = np.std(group, ddof=1) / np.sqrt(n)\n",
    "    h = sem * t.ppf((1 + confidence) / 2, n-1)\n",
    "    return mean, mean - h, mean + h"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'def occurences():\\n    df = six_months_before_eco_cycle_change()\\n    df.set_index(\"alternation_type\", inplace=True)\\n    df.rename(index={\\n    \"-2 to -2\": \"Récession à Récession\",\\n    \"-2 to -1\": \"Récession à Ralentissement\",\\n    \"-2 to 1\": \"Récession à Croissance modérée\",\\n    \"-2 to 2\": \"Récession à Forte croissance\",\\n    \"-1 to -2\": \"Ralentissement à Récession\",\\n    \"-1 to -1\": \"Ralentissement à Ralentissement\",\\n    \"-1 to 1\": \"Ralentissement à Croissance modérée\",\\n    \"-1 to 2\": \"Ralentissement à Forte croissance\",\\n    \"1 to -2\": \"Croissance modérée à Récession\",\\n    \"1 to -1\": \"Croissance modérée à Ralentissement\",\\n    \"1 to 1\": \"Croissance modérée à Croissance modérée\",\\n    \"1 to 2\": \"Croissance modérée à Forte croissance\",\\n    \"2 to -2\": \"Forte croissance à Récession\",\\n    \"2 to -1\": \"Forte croissance à Ralentissement\",\\n    \"2 to 1\": \"Forte croissance à Croissance modérée\",\\n    \"2 to 2\": \"Forte croissance à Forte croissance\"\\n    }, inplace=True)\\n    c = df.index.value_counts()\\n    return c\\n\\noccurences()'"
      ]
     },
     "execution_count": 128,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"def occurences():\n",
    "    df = six_months_before_eco_cycle_change()\n",
    "    df.set_index(\"alternation_type\", inplace=True)\n",
    "    df.rename(index={\n",
    "    \"-2 to -2\": \"Récession à Récession\",\n",
    "    \"-2 to -1\": \"Récession à Ralentissement\",\n",
    "    \"-2 to 1\": \"Récession à Croissance modérée\",\n",
    "    \"-2 to 2\": \"Récession à Forte croissance\",\n",
    "    \"-1 to -2\": \"Ralentissement à Récession\",\n",
    "    \"-1 to -1\": \"Ralentissement à Ralentissement\",\n",
    "    \"-1 to 1\": \"Ralentissement à Croissance modérée\",\n",
    "    \"-1 to 2\": \"Ralentissement à Forte croissance\",\n",
    "    \"1 to -2\": \"Croissance modérée à Récession\",\n",
    "    \"1 to -1\": \"Croissance modérée à Ralentissement\",\n",
    "    \"1 to 1\": \"Croissance modérée à Croissance modérée\",\n",
    "    \"1 to 2\": \"Croissance modérée à Forte croissance\",\n",
    "    \"2 to -2\": \"Forte croissance à Récession\",\n",
    "    \"2 to -1\": \"Forte croissance à Ralentissement\",\n",
    "    \"2 to 1\": \"Forte croissance à Croissance modérée\",\n",
    "    \"2 to 2\": \"Forte croissance à Forte croissance\"\n",
    "    }, inplace=True)\n",
    "    c = df.index.value_counts()\n",
    "    return c\n",
    "\n",
    "occurences()\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 129,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_the_confidence_intervals_t_distribution(name_of_excel, send_to_excel ='no', confidence = 0.95, smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W'):\n",
    "    df_original = six_months_before_eco_cycle_change(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth, smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly, smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly, sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci, nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window, indices_order = indices_order, freq = freq)\n",
    "    intervals = []\n",
    "    grouped = df_original.groupby(\"alternation_type\")\n",
    "    \n",
    "    for name, group in grouped:\n",
    "        for column in group.select_dtypes(include=np.number).columns:\n",
    "            mean, lower, upper = calculate_confidence_interval_t_distribution(group[column], confidence=confidence)\n",
    "            intervals.append({\n",
    "                'alternation_type': name,\n",
    "                'column': column,\n",
    "                'mean': mean,\n",
    "                f'{confidence*100}% CI Lower': lower,\n",
    "                f'{confidence*100}% CI Upper': upper\n",
    "            })\n",
    "\n",
    "    result_df = pd.DataFrame(intervals)\n",
    "    result_df.set_index(\"alternation_type\", inplace=True)\n",
    "    result_df.rename(index={\n",
    "    \"-2 to -2\": \"Récession à Récession\",\n",
    "    \"-2 to -1\": \"Récession à Ralentissement\",\n",
    "    \"-2 to 1\": \"Récession à Croissance modérée\",\n",
    "    \"-2 to 2\": \"Récession à Forte croissance\",\n",
    "    \"-1 to -2\": \"Ralentissement à Récession\",\n",
    "    \"-1 to -1\": \"Ralentissement à Ralentissement\",\n",
    "    \"-1 to 1\": \"Ralentissement à Croissance modérée\",\n",
    "    \"-1 to 2\": \"Ralentissement à Forte croissance\",\n",
    "    \"1 to -2\": \"Croissance modérée à Récession\",\n",
    "    \"1 to -1\": \"Croissance modérée à Ralentissement\",\n",
    "    \"1 to 1\": \"Croissance modérée à Croissance modérée\",\n",
    "    \"1 to 2\": \"Croissance modérée à Forte croissance\",\n",
    "    \"2 to -2\": \"Forte croissance à Récession\",\n",
    "    \"2 to -1\": \"Forte croissance à Ralentissement\",\n",
    "    \"2 to 1\": \"Forte croissance à Croissance modérée\",\n",
    "    \"2 to 2\": \"Forte croissance à Forte croissance\"\n",
    "    }, inplace=True)\n",
    "\n",
    "    #result_df = result_df.transpose()\n",
    "\n",
    "    if send_to_excel =='yes':\n",
    "        result_df.to_excel(f\"{name_of_excel}.xlsx\")\n",
    "        \n",
    "        wb = load_workbook(f\"{name_of_excel}.xlsx\")\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb)\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{name_of_excel}.xlsx\")\n",
    "\n",
    "    return result_df\n",
    "\n",
    "#return_the_confidence_intervals_t_distribution(confidence=0.75, name_of_excel=f'conf0.75', send_to_excel='yes')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Predicting the values of the economic cycle and market indices"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_confidence_interval(predictions, residuals, confidence_level=0.8):\n",
    "    \"\"\"\n",
    "    Compute the confidence interval for the predictions based on the residuals.\n",
    "    \n",
    "    Parameters:\n",
    "    - predictions: Array of predictions.\n",
    "    - residuals: Array of residuals from the test set.\n",
    "    - confidence_level: Desired confidence level (default is 0.8).\n",
    "    \n",
    "    Returns:\n",
    "    - lower_bound: Lower bound of the confidence interval.\n",
    "    - upper_bound: Upper bound of the confidence interval.\n",
    "    \"\"\"\n",
    "    residuals = np.abs(residuals)\n",
    "    lower_bound = np.percentile(residuals, (1 - confidence_level) / 2 * 100)\n",
    "    upper_bound = np.percentile(residuals, (1 + confidence_level) / 2 * 100)\n",
    "    \n",
    "    return predictions - upper_bound, predictions + upper_bound"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Model 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 131,
   "metadata": {},
   "outputs": [],
   "source": [
    "def model_1_prediction(plot_perfs = 'no', save_model = 'yes', what_to_predict = 'Economic cycle', help_to_predict1 = 'Sum of standard deviation values',help_to_predict2 = 'Sum of recession/expansion values', smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W', sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes'):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth, smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly, smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly, sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci, nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window, indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "    X = df[[help_to_predict1, help_to_predict2]]\n",
    "    y = df[what_to_predict]\n",
    "\n",
    "    # Create polynomial features\n",
    "    poly = PolynomialFeatures(degree=3, interaction_only=False, include_bias=False)\n",
    "    X_poly = poly.fit_transform(X)\n",
    "\n",
    "    # Feature scaling\n",
    "    scaler = StandardScaler()\n",
    "    X_poly_scaled = scaler.fit_transform(X_poly)\n",
    "\n",
    "    # Split the data\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X_poly_scaled, y, test_size=0.2, random_state=42)\n",
    "\n",
    "    # Define the parameter grid for Randomized Search\n",
    "    param_grid = {\n",
    "        'n_estimators': [50, 100, 200, 300],\n",
    "        'max_depth': [None, 10, 20, 30, 40],\n",
    "        'min_samples_split': [2, 5, 10, 15],\n",
    "        'min_samples_leaf': [1, 2, 4, 6],\n",
    "        'max_features': [None, 'sqrt', 'log2']\n",
    "    }\n",
    "\n",
    "    # Create a Random Forest Regressor\n",
    "    rf_model = RandomForestRegressor(random_state=42)\n",
    "\n",
    "    # Create the RandomizedSearchCV object\n",
    "    random_search = RandomizedSearchCV(estimator=rf_model, param_distributions=param_grid,\n",
    "                                    n_iter=100, cv=5, n_jobs=-1, scoring='neg_mean_squared_error', random_state=42)\n",
    "\n",
    "    # Fit the random search to the data\n",
    "    random_search.fit(X_train, y_train)\n",
    "\n",
    "    # Get the best parameters and best model\n",
    "    best_rf_model = random_search.best_estimator_\n",
    "\n",
    "    # Save the best model, polynomial features transformer, and scaler\n",
    "    if save_model == 'yes':\n",
    "        model_dir = f'model_1_for_{what_to_predict}'\n",
    "        os.makedirs(model_dir, exist_ok=True)\n",
    "        joblib.dump(best_rf_model, os.path.join(model_dir, f'model_1_for_{what_to_predict}.pkl'))\n",
    "        joblib.dump(poly, os.path.join(model_dir, 'poly_transformer.pkl'))\n",
    "        joblib.dump(scaler, os.path.join(model_dir, 'scaler.pkl'))\n",
    "\n",
    "    # Evaluate the model\n",
    "    y_pred = best_rf_model.predict(X_test)\n",
    "    mse = mean_squared_error(y_test, y_pred)\n",
    "    r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "    if plot_perfs == 'yes':\n",
    "\n",
    "        print(f'Improved Mean Squared Error: {mse}')\n",
    "        print(f'Improved R-squared: {r2}')\n",
    "\n",
    "        # Plot the predictions\n",
    "        plt.figure(figsize=(12, 6))\n",
    "        plt.plot(y_test.values, label='Actual', marker='o')\n",
    "        plt.plot(y_pred, label='Predicted', marker='x')\n",
    "        plt.legend()\n",
    "        plt.show()\n",
    "\n",
    "    return best_rf_model, poly\n",
    "\n",
    "# Train the model and save it\n",
    "#model_1_prediction(plot_perfs='yes')"
   ]
  }

 {
   "cell_type": "code",
   "execution_count": 132,
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_values_model_1(new_model='no', what_to_predict='Economic cycle', help_to_predict1='Sum of standard deviation values',\n",
    "                           help_to_predict2='Sum of recession/expansion values', plot='yes', return_predictions='yes', \n",
    "                           return_dataframe='no', confidence_level=0.8, smooth_filter='yes', svgal_window=50, polyorder=3, \n",
    "                           smooth_both_columns='no', index_which_column_to_smooth=1, smooth_economic_cycle='no', svgal_eco_cycle=75, \n",
    "                           eco_poly=6, smooth_fed='yes', fed_as_pctg='yes', svgal_fed_cycle=150, fed_poly=3, sp_as_pctg='yes', \n",
    "                           smooth_sp500='yes', msci_as_pctg='yes', smooth_msci='yes', nasdaq_as_pctg='yes', smooth_nasdaq='yes', \n",
    "                           indices_window=500, indices_order=5, freq='W', sp_sub_ind_as_pctg='yes', smooth_sp_sub_ind='yes',\n",
    "                           save_excel='no', excel_name='predictions_model_1', cell_width=50):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, \n",
    "                                            smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, \n",
    "                                            smooth_economic_cycle=smooth_economic_cycle, svgal_eco_cycle=svgal_eco_cycle, eco_poly=eco_poly, \n",
    "                                            smooth_fed=smooth_fed, fed_as_pctg=fed_as_pctg, svgal_fed_cycle=svgal_fed_cycle, fed_poly=fed_poly, \n",
    "                                            sp_as_pctg=sp_as_pctg, smooth_sp500=smooth_sp500, msci_as_pctg=msci_as_pctg, smooth_msci=smooth_msci, \n",
    "                                            nasdaq_as_pctg=nasdaq_as_pctg, smooth_nasdaq=smooth_nasdaq, indices_window=indices_window, \n",
    "                                            indices_order=indices_order, freq=freq, sp_sub_ind_as_pctg=sp_sub_ind_as_pctg, smooth_sp_sub_ind=smooth_sp_sub_ind)\n",
    "\n",
    "    model_dir = f'model_1_for_{what_to_predict}'\n",
    "    model_path = os.path.join(model_dir, f'model_1_for_{what_to_predict}.pkl')\n",
    "    \n",
    "    if not os.path.exists(model_path) or new_model == 'yes':\n",
    "        model_1_prediction(save_model='yes', what_to_predict=what_to_predict, help_to_predict1=help_to_predict1, help_to_predict2=help_to_predict2, \n",
    "                           smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, \n",
    "                           index_which_column_to_smooth=index_which_column_to_smooth, smooth_economic_cycle=smooth_economic_cycle, \n",
    "                           svgal_eco_cycle=svgal_eco_cycle, eco_poly=eco_poly, smooth_fed=smooth_fed, fed_as_pctg=fed_as_pctg, svgal_fed_cycle=svgal_fed_cycle, \n",
    "                           fed_poly=fed_poly, sp_as_pctg=sp_as_pctg, smooth_sp500=smooth_sp500, msci_as_pctg=msci_as_pctg, smooth_msci=smooth_msci, \n",
    "                           nasdaq_as_pctg=nasdaq_as_pctg, smooth_nasdaq=smooth_nasdaq, indices_window=indices_window, indices_order=indices_order, \n",
    "                           freq=freq, sp_sub_ind_as_pctg=sp_sub_ind_as_pctg, smooth_sp_sub_ind=smooth_sp_sub_ind)\n",
    "    \n",
    "    # Load the model and transformers from the specified directory\n",
    "    best_rf_model = joblib.load(os.path.join(model_dir, f'model_1_for_{what_to_predict}.pkl'))\n",
    "    poly = joblib.load(os.path.join(model_dir, 'poly_transformer.pkl'))\n",
    "    scaler = joblib.load(os.path.join(model_dir, 'scaler.pkl'))\n",
    "    \n",
    "    # Ensure the DataFrame contains the necessary columns\n",
    "    if not {help_to_predict1, help_to_predict2}.issubset(df.columns):\n",
    "        raise ValueError(f\"DataFrame must contain '{help_to_predict1}' and '{help_to_predict2}' columns.\")\n",
    "    \n",
    "    # Transform the data using the polynomial features transformer\n",
    "    new_X_poly = poly.transform(df[[help_to_predict1, help_to_predict2]])\n",
    "    \n",
    "    # Scale the polynomial features\n",
    "    new_X_scaled = scaler.transform(new_X_poly)\n",
    "    \n",
    "    # Make predictions with the loaded model\n",
    "    new_predictions = best_rf_model.predict(new_X_scaled)\n",
    "    \n",
    "    # Get the residuals from the training phase\n",
    "    X = df[[help_to_predict1, help_to_predict2]]\n",
    "    y = df[what_to_predict]\n",
    "    \n",
    "    X_poly = poly.fit_transform(X)\n",
    "    X_poly_scaled = scaler.fit_transform(X_poly)\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X_poly_scaled, y, test_size=0.2, random_state=42)\n",
    "    \n",
    "    best_rf_model.fit(X_train, y_train)\n",
    "    y_pred = best_rf_model.predict(X_test)\n",
    "    residuals = y_test - y_pred\n",
    "    \n",
    "    # Compute confidence intervals\n",
    "    lower_bound, upper_bound = compute_confidence_interval(new_predictions, residuals, confidence_level)\n",
    "    \n",
    "    df_with_predictions = df.copy()\n",
    "    df_with_predictions['Predictions'] = new_predictions\n",
    "    df_with_predictions['Lower Bound'] = lower_bound\n",
    "    df_with_predictions['Upper Bound'] = upper_bound\n",
    "    \n",
    "    if plot == 'yes':\n",
    "        plt.figure(figsize=(12, 6))\n",
    "        sns.lineplot(x=df_with_predictions.index, y=help_to_predict1, data=df_with_predictions, label=help_to_predict1)\n",
    "        sns.lineplot(x=df_with_predictions.index, y=help_to_predict2, data=df_with_predictions, label=help_to_predict2)\n",
    "        sns.lineplot(x=df_with_predictions.index, y='Predictions', data=df_with_predictions, label=f'Predictions for {what_to_predict}')\n",
    "        sns.lineplot(x=df_with_predictions.index, y=what_to_predict, data=df_with_predictions, label=f'Actual value for {what_to_predict}')\n",
    "        plt.fill_between(df_with_predictions.index, df_with_predictions['Lower Bound'], df_with_predictions['Upper Bound'], color='gray', alpha=0.2, label='Confidence Interval')\n",
    "        plt.xlabel('Index')\n",
    "        plt.ylabel('Values')\n",
    "        plt.legend()\n",
    "        plt.title('Predictions, Actual Values, and Confidence Interval')\n",
    "        plt.show()\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Save to Excel\n",
    "        df_with_predictions.to_excel(f\"{excel_name}.xlsx\", index=False)\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    \n",
    "    if return_predictions == 'yes' and return_dataframe == 'yes':\n",
    "        return new_predictions, df_with_predictions\n",
    "    elif return_predictions == 'yes':\n",
    "        return new_predictions\n",
    "    elif return_dataframe == 'yes':\n",
    "        return df_with_predictions\n",
    "    else:\n",
    "        return None\n",
    "\n",
    "# Example usage\n",
    "#predict_values_model_1(plot='no', return_predictions='no', return_dataframe='yes')"
   ]
  }
