{
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [],
   "source": [
    "pivot_values_dict = {\n",
    "    \"Chicago Fed National Activity (Business Conditions)\":0,\n",
    "    \"Conference Board US Leading In (Business Conditions)\":0,\n",
    "    \"ISM Manufacturing PMI SA (Business Conditions)\":50,\n",
    "    \"ISM Services PMI (Business Conditions)\":50,\n",
    "    \"Market News International Chic (Business Conditions)\":0,\n",
    "    \"Philadelphia Fed Business Outl (Business Conditions)\":0,\n",
    "    \"Richmond Manufacturing Survey (Business Conditions)\":0,\n",
    "    \"US Composite PMI SA (Business Conditions)\":50,\n",
    "    \"US Empire State Manufacturing (Business Conditions)\":50,\n",
    "    \"US Manufacturing PMI SA (Business Conditions)\":50,\n",
    "    \"US Services PMI Business Activ (Business Conditions)\":50,\n",
    "    \"Conference Board Consumer Conf (Customer Trust)\":'avg',\n",
    "    \"University of Michigan Consume (Customer Trust)\":'avg',\n",
    "    \"Adjusted Retail Sales Less Aut MoM (Details selling)\":0,\n",
    "    \"Adjusted Retail Sales Less Aut YoY (Details selling)\":0,\n",
    "    \"US Auto Sales Total Annualized (Details selling)\":'avg',\n",
    "    \"US Capacity Utilization % of T (Economic Dynamic)\":'avg',\n",
    "    \"US Durable Goods New Orders To (Economic Dynamic)\":0,\n",
    "    \"US Industrial Production YOY S (Economic Dynamic)\":0,\n",
    "    \"ADP National Employment Report (Employment)\":'avg',\n",
    "    \"Conference Board US Leading In (Employment)\":'avg',\n",
    "    \"U-3 US Unemployment Rate Total (Employment)\":'avg',\n",
    "    \"US Employees on Nonfarm Payrol (Employment)\":'avg',\n",
    "    \"GDP US Chained Dollars QoQ SAA (GDP)\":0,\n",
    "    \"GDP US Chained Dollars YoY SA (GDP)\":0,\n",
    "    \"US GDP Nominal Dollars YoY SA (GDP)\":0,\n",
    "    \"US GDP Price Index QoQ SAAR (GDP)\":2,\n",
    "    \"US Personal Consumption Expend % (Household)\":0,\n",
    "    \"US Personal Consumption Expend (Household)\":0,\n",
    "    \"US Personal Income YoY SA (Household)\":0,\n",
    "    \"Private Housing Authorized by (Housing)\":'avg',\n",
    "    \"US NAR Total Existing Homes Sa (Housing)\":'avg',\n",
    "    \"US Avg Hourly Earnings Private (Inflation)\":'avg',\n",
    "    \"US CPI Urban Consumers Less Fo (Inflation)\":2,\n",
    "    \"US PPI Finished Goods Less Foo (Inflation)\":3,\n",
    "    \"US Personal Consumption Expend (Inflation)\":2\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_cycles():\n",
    "    dataframe_cycles_list = []\n",
    "    for i in range(len(dict_of_df)):\n",
    "        df_name = f'df{i+1}'\n",
    "        if df_name in globals():\n",
    "            df = globals()[df_name]\n",
    "            global_average = df.mean()\n",
    "            monthly_average = df.resample('ME').mean()\n",
    "            monthly_average = monthly_average.to_period('M').to_timestamp()\n",
    "            modified_columns = []\n",
    "            for column, threshold in pivot_values_dict.items():\n",
    "                if column in monthly_average.columns:\n",
    "                    if threshold == 'avg':\n",
    "                        threshold_value = global_average[column]\n",
    "                    else:\n",
    "                        threshold_value = threshold\n",
    "                    monthly_average[column] = monthly_average[column].apply(lambda x: 1 if x > threshold_value else -1)\n",
    "                    modified_columns.append(column) \n",
    "            if modified_columns:\n",
    "                monthly_average = monthly_average[modified_columns]\n",
    "                dataframe_cycles_list.append(monthly_average)\n",
    "    return dataframe_cycles_list\n",
    "\n",
    "#find_cycles()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_cycles_and_find_trend():\n",
    "    sums_list = []\n",
    "    cycles_df = find_cycles()\n",
    "    for df in cycles_df:\n",
    "        sums = df.sum(axis=1)\n",
    "        sums_list.append(sums)\n",
    "    for i in range(1, len(sums_list)):\n",
    "        union_index = sums_list[0].index.union(sums_list[i].index)\n",
    "        reindexed_series_0 = sums_list[0].reindex(union_index, fill_value=0)\n",
    "        reindexed_series_i = sums_list[i].reindex(union_index, fill_value=0)\n",
    "        sums_list[0] = reindexed_series_0.add(reindexed_series_i, fill_value=0)\n",
    "    final_series = sums_list[0]\n",
    "    final_series.index.name = 'Trend of each month for the values'\n",
    "    return final_series\n",
    "\n",
    "#sum_cycles_and_find_trend()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Merge the stds with the values"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Small filtering"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [],
   "source": [
    "def combine_cycles_and_stds_trend(save_excel='no', cell_width=50, excel_name=\"Combined Cycles and Stds\"):\n",
    "    cycles = sum_cycles_and_find_trend()\n",
    "    stds = sum_combined_1_and_2_stds()\n",
    "    df = pd.DataFrame({'Sum of recession/expansion values':cycles, 'Sum of standard deviation values':stds})\n",
    "    df = df.fillna(0)\n",
    "    #the 2011-12-01 row (index 502) was causing issues in the smoothing (later) as the sum of standard deviation values was +1, so we set it equal to zero\n",
    "    df.loc['2011-12-01', 'Sum of standard deviation values'] = 0\n",
    "    # so was the 2015-01-01 row (index 539) was causing issues in the smoothing (later) as the sum of standard deviation values was -1, so we set it equal to zero\n",
    "    df.loc['2015-01-01', 'Sum of standard deviation values'] = 0\n",
    "    # so was the 1996-02-01 row (index 312) was causing issues in the smoothing (later) as the sum of recession/expansion values was 0, so we set it equal to -1\n",
    "    df.loc['1996-02-01', 'Sum of recession/expansion values'] = -1\n",
    "    if save_excel == \"yes\":\n",
    "        df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return df\n",
    "\n",
    "#combine_cycles_and_stds_trend()"
   ]
  }
