{
   "cell_type": "code",
   "execution_count": 166,
   "metadata": {},
   "outputs": [],
   "source": [
    "def two_indices_periods_changes(smooth_filter='yes', svgal_window=50, polyorder=3, smooth_both_columns='no', index_which_column_to_smooth=1, inflexion_or_zero = 'zero', high_orange_low_orange_blue='yes', index1='S&P 500 (Stock Index)', index2='MSCI world (Stock Index)'):\n",
    "    matches = match_dates(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, high_orange_low_orange_blue=high_orange_low_orange_blue)\n",
    "    dfs_count = 0\n",
    "    dfs_list = []\n",
    "    for i in range(len(dict_of_df)):\n",
    "        df_name = f'df{i+1}'\n",
    "        if df_name in globals():\n",
    "            the_df = globals()[df_name]\n",
    "            if index1 in the_df or index2 in the_df:\n",
    "                for columns in the_df:\n",
    "                    dates_matches = []\n",
    "                    if index1 in columns or index2 in columns:\n",
    "                        dfs_count+=1\n",
    "                        for match in matches:\n",
    "                            tuple_std, tuple_market = match\n",
    "                            if inflexion_or_zero == 'zero':\n",
    "                                date2_tuple_std = tuple_std[3]\n",
    "                            elif inflexion_or_zero == 'inflexion':\n",
    "                                current_period = tuple_std[1]\n",
    "                                beginning = tuple_std[2]\n",
    "                                ending = tuple_std[3]\n",
    "                                timestamp = []\n",
    "                                current = beginning\n",
    "                                while current <= ending:\n",
    "                                    timestamp.append(current)\n",
    "                                    current += relativedelta(months=1)\n",
    "\n",
    "                                values_list = tuple_std[4]\n",
    "                                if current_period == 'above_zero':\n",
    "                                    max_value = max(values_list)\n",
    "                                    max_index = values_list.index(max_value)\n",
    "                                    date2_tuple_std = timestamp[max_index]\n",
    "                                elif current_period == 'below_or_at_zero':\n",
    "                                    min_value = min(values_list)\n",
    "                                    min_index = values_list.index(min_value)\n",
    "                                    date2_tuple_std = timestamp[min_index]\n",
    "                                \n",
    "                            date2_tuple_market = tuple_market[3]\n",
    "                            type_match = tuple_std[1]\n",
    "                            date_diff = (date2_tuple_market - date2_tuple_std).days\n",
    "                            closest_date_std_index = abs((the_df.index - date2_tuple_std)).argmin()\n",
    "                            closest_date_market_index = abs((the_df.index - date2_tuple_market)).argmin()\n",
    "                            value_date_std = the_df.iloc[closest_date_std_index][columns]\n",
    "                            value_date_market = the_df.iloc[closest_date_market_index][columns]\n",
    "                            dates_matches.append([date2_tuple_std, float(value_date_std), type_match, columns])\n",
    "                            dates_matches.append([date2_tuple_market, float(value_date_market), type_match, columns])\n",
    "                dfs_list.append(dates_matches)\n",
    "            else:\n",
    "                continue\n",
    "    #print(dfs_count)\n",
    "\n",
    "    return dfs_list\n",
    "\n",
    "#two_indices_periods_changes(inflexion_or_zero='zero')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [],
   "source": [
    "def list_the_indices_periods_changes_by_date(smooth_filter='yes', svgal_window=50, polyorder=3, smooth_both_columns='no', index_which_column_to_smooth=1, inflexion_or_zero = 'zero', high_orange_low_orange_blue='yes', index1='S&P 500 (Stock Index)', index2='MSCI world (Stock Index)'):\n",
    "    my_list = two_indices_periods_changes(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, inflexion_or_zero=inflexion_or_zero, high_orange_low_orange_blue=high_orange_low_orange_blue, index1=index1, index2=index2)\n",
    "    to_return = []\n",
    "    for data in my_list:\n",
    "        # Convert the date strings to Timestamp objects\n",
    "        for sublist in data:\n",
    "            sublist[0] = pd.to_datetime(sublist[0])\n",
    "\n",
    "        # Sort each sublist by the first element (date)\n",
    "        data.sort(key=lambda x: x[0])\n",
    "        to_return.append(data)\n",
    "\n",
    "    return to_return\n",
    "\n",
    "#list_the_indices_periods_changes_by_date(inflexion_or_zero='zero')[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "metadata": {},
   "outputs": [],
   "source": [
    "def put_the_periods_as_pctg_change(smooth_filter='yes', svgal_window=50, polyorder=3, smooth_both_columns='no', index_which_column_to_smooth=1, inflexion_or_zero='inflexion', high_orange_low_orange_blue='yes', index1='S&P 500 (Stock Index)', index2='MSCI world (Stock Index)'):\n",
    "    my_list = list_the_indices_periods_changes_by_date(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, inflexion_or_zero=inflexion_or_zero, high_orange_low_orange_blue=high_orange_low_orange_blue, index1=index1, index2=index2)\n",
    "    matches = match_dates(smooth_filter=smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns=smooth_both_columns, index_which_column_to_smooth=index_which_column_to_smooth, high_orange_low_orange_blue=high_orange_low_orange_blue)\n",
    "\n",
    "    flattened_data1 = [item for item in my_list[0]]\n",
    "    flattened_data2 = [item for item in my_list[1]]\n",
    "\n",
    "    dates1 = [item[0] for item in flattened_data1]\n",
    "    data_values1 = [item[1:] for item in flattened_data1]\n",
    "\n",
    "    dates2 = [item[0] for item in flattened_data2]\n",
    "    data_values2 = [item[1:] for item in flattened_data2]\n",
    "\n",
    "    assert dates1 == dates2\n",
    "\n",
    "    combined_data = [data1 + data2 for data1, data2 in zip(data_values1, data_values2)]\n",
    "\n",
    "    df = pd.DataFrame(data=combined_data, index=pd.to_datetime(dates1), columns=[f'{data_values1[0][2]}', 'category', f'{data_values1[0][2]}', f'{data_values2[0][2]}', 'category', f'{data_values2[0][2]}'])\n",
    "\n",
    "    df_selected = df.iloc[:, [0, 3]]\n",
    "\n",
    "    new_changes = []\n",
    "    for cols in df_selected:\n",
    "        percentage_changes = []\n",
    "        for i in range(0, len(df_selected),2):\n",
    "            previous_value = df_selected[cols].iloc[i]\n",
    "            current_value = df_selected[cols].iloc[i+1]\n",
    "            pct_change = float(((current_value - previous_value) / previous_value) * 100)\n",
    "            percentage_changes.append(pct_change)\n",
    "        new_changes.append(percentage_changes)\n",
    "\n",
    "    new_index = []\n",
    "    for i in range(1, len(df_selected), 2):\n",
    "        index_label = f\"{df_selected.index[i-1].date()} -- {df_selected.index[i].date()}\"\n",
    "        new_index.append(index_label)\n",
    "    transposed_list = list(map(list, zip(*new_changes)))\n",
    "    final_df = pd.DataFrame(transposed_list, index=new_index, columns=[f'{data_values1[0][2]}', f'{data_values2[0][2]}'])\n",
    "\n",
    "    list_of_dates_difference_in_days = calculate_date_differences(matches=matches)\n",
    "    values = [sublist[0] for sublist in list_of_dates_difference_in_days]\n",
    "    strings = [sublist[1] for sublist in list_of_dates_difference_in_days]\n",
    "    final_df['Time difference between extreme perf and market tendency'] = values\n",
    "    final_df['Direction of the trend'] = strings\n",
    "    final_df['Direction of the trend'] = final_df['Direction of the trend'].replace({'below_or_at_zero':'below zero', 'above_zero':'above zero'})\n",
    "    final_df.rename(columns={'Direction of the trend': 'Is the market tendency line currently above or below zero'}, inplace=True)\n",
    "    avg_values = []\n",
    "    for values in matches:\n",
    "        ss = sum(values[1][4])\n",
    "        ll = len(values[1][4])\n",
    "        avg = round(ss/ll)\n",
    "        avg_values.append(avg)\n",
    "    final_df['Average value of the market tendency during that time'] = avg_values\n",
    "\n",
    "    avg_xtr = []\n",
    "    for values in matches:\n",
    "        ss = sum(values[0][4])\n",
    "        ll = len(values[0][4])\n",
    "        avg = round(ss/ll)\n",
    "        avg_xtr.append(avg)\n",
    "    final_df['Average value of the extreme performances during that time'] = avg_xtr\n",
    "        \n",
    "\n",
    "    return final_df\n",
    "\n",
    "#put_the_periods_as_pctg_change(inflexion_or_zero='zero', index2='NASDAQ (Stock Index)')"
   ]
  }
