"def decide_median_value(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window = 75, polyorder = 3, save_excel='no', excel_name='Median Values', cell_width=75):\n",
    "    df_list = normalize_y_axis(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window = svgal_window, polyorder = polyorder)\n",
    "    median_values = []\n",
    "    \n",
    "    for df_item in df_list:\n",
    "        df = df_item[1]\n",
    "        max1, max2 = df.max()\n",
    "        min1, min2 = df.min()\n",
    "        diff1 = max1 - min1\n",
    "        diff2 = max2 - min2\n",
    "        mean1, mean2 = df.mean()\n",
    "        median_value1, median_value2 = df.median()\n",
    "        \n",
    "        if diff1 > diff2:\n",
    "            chosen_median = median_value1\n",
    "            column_name = df_item[0][0]\n",
    "        elif diff2 > diff1:\n",
    "            chosen_median = median_value2\n",
    "            column_name = df_item[0][1]\n",
    "        else:\n",
    "            if mean1 > mean2:\n",
    "                chosen_median = median_value1\n",
    "                column_name = df_item[0][0]\n",
    "            elif mean2 > mean1:\n",
    "                chosen_median = median_value2\n",
    "                column_name = df_item[0][1]\n",
    "            else:\n",
    "                chosen_median = median_value1\n",
    "                column_name = df_item[0][0]\n",
    "\n",
    "        median_values.append([df_item[0], df_item[1], column_name, chosen_median])\n",
    "    if save_excel == \"yes\":\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = 'Median Values'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        for i, median_value in enumerate(median_values, start=1):\n",
    "            ws[f'A{i}'] = median_value[0]\n",
    "            ws[f'B{i}'] = median_value[2]\n",
    "            ws[f'C{i}'] = median_value[3]\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return median_values\n",
    "\n",
    "#median_values = decide_median_value()\n",
    "#pprint(median_values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_series_with_median(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3, folder_name='median_plots', image_format='png'):\n",
    "    median_values = decide_median_value(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    for median_item in median_values:\n",
    "        df = median_item[1]\n",
    "        column_name = median_item[2]\n",
    "        chosen_median = median_item[3]\n",
    "\n",
    "        plt.figure(figsize=(10, 6))\n",
    "        plt.plot(df.iloc[:, 0], label=f'{df.columns[0]}')\n",
    "        plt.plot(df.iloc[:, 1], label=f'{df.columns[1]}')\n",
    "        plt.axhline(y=chosen_median, color='r', linestyle='--', label=f'{column_name} Median = {chosen_median}')\n",
    "        \n",
    "        plt.title(f'{median_item[0]} with Median Line')\n",
    "        plt.xlabel('Year')\n",
    "        plt.ylabel('Values')\n",
    "        plt.legend()\n",
    "\n",
    "        # Save the plot with a dynamic filename\n",
    "        file_name = f\"{median_item[0]}_median_plot.{image_format}\"\n",
    "        file_path = os.path.join(folder_name, file_name)\n",
    "        plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "        plt.close()\n",
    "\n",
    "    return f\"Images successfully saved in the '{folder_name}' folder.\"\n",
    "#plot_series_with_median()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Find all periods in a dataframe's column where the data doesn't pass through the median"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_periods_above_below_median(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    median_values = decide_median_value(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    all_periods = []\n",
    "    \n",
    "    for median_item in median_values:\n",
    "        columns = median_item[0]\n",
    "        df = median_item[1]\n",
    "        median_column_name = median_item[2]\n",
    "        median_value = median_item[3]\n",
    "        \n",
    "        periods = []\n",
    "        column_periods = {col: [] for col in columns}\n",
    "        \n",
    "        # Initialize variables to track periods\n",
    "        above_median = {col: df.iloc[0][col] > median_value for col in columns}\n",
    "        current_period = {col: [df.index[0], None, above_median[col]] for col in columns}\n",
    "        \n",
    "        # Iterate through the DataFrame\n",
    "        for index, row in df.iterrows():\n",
    "            for col in columns:\n",
    "                value = row[col]\n",
    "                \n",
    "                if value > median_value and not above_median[col]:\n",
    "                    current_period[col][1] = index\n",
    "                    column_periods[col].append(current_period[col] + [col])\n",
    "                    current_period[col] = [index, None, True]\n",
    "                    above_median[col] = True\n",
    "                elif value < median_value and above_median[col]:\n",
    "                    current_period[col][1] = index\n",
    "                    column_periods[col].append(current_period[col] + [col])\n",
    "                    current_period[col] = [index, None, False]\n",
    "                    above_median[col] = False\n",
    "        \n",
    "        # Finalize the last period for each column\n",
    "        for col in columns:\n",
    "            if current_period[col][1] is None:\n",
    "                current_period[col][1] = df.index[-1]\n",
    "                column_periods[col].append(current_period[col] + [col])\n",
    "        \n",
    "        # Analyze and store period information\n",
    "        for col in columns:\n",
    "            for period in column_periods[col]:\n",
    "                start_index, end_index, above_median, col_name = period\n",
    "                period_data = df.loc[start_index:end_index]\n",
    "                if above_median:\n",
    "                    extreme_value = period_data[col_name].max()\n",
    "                else:\n",
    "                    extreme_value = period_data[col_name].min()\n",
    "                period.extend([period_data, extreme_value, columns])\n",
    "        \n",
    "        # Combine all periods for this dataframe into a list\n",
    "        dataframe_periods = []\n",
    "        for col_periods in column_periods.values():\n",
    "            dataframe_periods.extend(col_periods)\n",
    "        \n",
    "        # Append the list of periods from this dataframe to the global list\n",
    "        all_periods.append(dataframe_periods)\n",
    "    \n",
    "    return all_periods\n",
    "\n",
    "#find_periods_above_below_median()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [],
   "source": [
    "#x=find_periods_above_below_median()\n",
    "#y = decide_median_value()\n",
    "#z = extreme_values_of_all_dfs()\n",
    "#p = leading_on_avg()\n",
    "#a = all_corr_parametrized()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [],
   "source": [
    "#x[0][0][5]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [],
   "source": [
    "#v = 0\n",
    "#for i in range(len(x)):\n",
    "#    found_match = False  # Flag to track if a match is found for x[i]\n",
    "    \n",
    "    # Extract variable names from a.index[i]\n",
    "#    a_str = a.index[i].strip(': ')\n",
    "#    a_variables = [var.strip() for var in a_str.split(', ')]\n",
    "\n",
    "#    for j in range(len(p)):\n",
    "        # Extract variable names from p[j][0]\n",
    "#        p_variables = list(p[j][0])\n",
    "\n",
    "        # Compare lists to check if they match\n",
    "#        if a_variables == p_variables:\n",
    "#            v += 1\n",
    "#            found_match = True\n",
    "#            break  # Exit the inner loop once a match is found\n",
    "    \n",
    "#    if found_match:\n",
    "#        continue  # Move to the next i without executing the else block\n",
    "#    else:\n",
    "        # Handle case where no match was found for x[i]\n",
    "#        continue\n",
    "\n",
    "#print(v)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extreme_values_of_all_dfs(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    list_final = []\n",
    "    median_values = decide_median_value(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    periods_list = find_periods_above_below_median(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    for j in range(len(periods_list)):\n",
    "        list_of_lists = []\n",
    "        for z in range(len(periods_list[j])):\n",
    "            for i in range(len(median_values)):\n",
    "                if periods_list[j][z][4].columns.equals(median_values[i][1].columns):  # Ensure you're comparing the correct columns\n",
    "                    if not periods_list[j][z][2]:  # Below median\n",
    "                        min_value1, min_value2 = periods_list[j][z][4].min()\n",
    "                        min_value = periods_list[j][z][4].min()\n",
    "                        min_date = periods_list[j][z][4].idxmin()\n",
    "                        below = 'Below median'\n",
    "                        if (min_value1 <= float(periods_list[j][z][5])) and (min_value2 <= float(periods_list[j][z][5])):\n",
    "                            x = [periods_list[j][z][0], periods_list[j][z][1], below, min_value, min_date, periods_list[j][z][6], median_values[i][3]]\n",
    "                            list_of_lists.append(x)\n",
    "                    else:  # Above median\n",
    "                        max_value1, max_value2 = periods_list[j][z][4].max()\n",
    "                        max_value = periods_list[j][z][4].max()\n",
    "                        max_date = periods_list[j][z][4].idxmax()\n",
    "                        above = 'Above median'\n",
    "                        if (max_value1 >= float(periods_list[j][z][5])) and (max_value2 >= float(periods_list[j][z][5])):\n",
    "                            y = [periods_list[j][z][0], periods_list[j][z][1], above, max_value, max_date, periods_list[j][z][6], median_values[i][3]]\n",
    "                            list_of_lists.append(y)\n",
    "        list_final.append(list_of_lists)\n",
    "    \n",
    "    return list_final\n",
    "\n",
    "#extreme_values_of_all_dfs()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Graph it, with the extremes pointed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_columns_with_median_and_extremes(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3, folder_name='extreme_plots', image_format='png'):\n",
    "    df_list = normalize_y_axis(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    extreme_values = extreme_values_of_all_dfs(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    # Ensure the output directory exists\n",
    "    if not os.path.exists(folder_name):\n",
    "        os.makedirs(folder_name)\n",
    "\n",
    "    x = 0\n",
    "    colors = ['blue', 'orange']\n",
    "    dot_colors = ['blue', 'orange']  # List of two colors for alternating dots\n",
    "\n",
    "    for df_item in df_list:\n",
    "        [df_name_x, df_name_y], df = df_item\n",
    "        \n",
    "        # Find the median value for the current DataFrame pair\n",
    "        median_value = None\n",
    "        for extremes in extreme_values:\n",
    "            for extreme in extremes:\n",
    "                if (df_name_x, df_name_y) == (extreme[5][0], extreme[5][1]):\n",
    "                    median_value = extreme[6]\n",
    "                    break\n",
    "            if median_value is not None:\n",
    "                break\n",
    "        \n",
    "        if median_value is None:\n",
    "            continue  # Skip if no median value is found\n",
    "        x += 1\n",
    "        title = f'{x}. {df_name_x} and {df_name_y} with Median Line and Extremes'\n",
    "        print(title)\n",
    "        \n",
    "        plt.figure(figsize=(12, 6))\n",
    "        plt.axhline(y=median_value, color='red', linestyle='--', label=f'Median = {median_value}')        \n",
    "        \n",
    "        # Plot each column in the DataFrame\n",
    "        for col_idx, col in enumerate(df.columns):\n",
    "            color = colors[col_idx % len(colors)]\n",
    "            plt.plot(df.index, df[col], label=f'{col}', color=color, linewidth=1.5)\n",
    "\n",
    "        # Find and mark the extreme values for each pair of columns\n",
    "        dot_color_idx = 0  # Index to alternate between dot colors\n",
    "        for extremes in extreme_values:\n",
    "            for extreme in extremes:\n",
    "                if (df_name_x, df_name_y) == (extreme[5][0], extreme[5][1]):\n",
    "                    extreme_values_list = list(extreme[3])\n",
    "                    extreme_dates_list = list(extreme[4])\n",
    "\n",
    "                    # Check if both values are above or below the median\n",
    "                    for extreme_date, extreme_value in zip(extreme_dates_list, extreme_values_list):\n",
    "                        if extreme_value > median_value and all(value > median_value for value in extreme_values_list):\n",
    "                            plt.scatter(extreme_date, extreme_value, color=dot_colors[dot_color_idx], edgecolor='black', zorder=5, label='Extreme Value' if col not in locals() else \"\")\n",
    "                            locals()[col] = True\n",
    "                        elif extreme_value < median_value and all(value < median_value for value in extreme_values_list):\n",
    "                            plt.scatter(extreme_date, extreme_value, color=dot_colors[dot_color_idx], edgecolor='black', zorder=5, label='Extreme Value' if col not in locals() else \"\")\n",
    "                            locals()[col] = True\n",
    "                        dot_color_idx = 1 - dot_color_idx  # Toggle between 0 and 1\n",
    "            \n",
    "        plt.title(title)\n",
    "        plt.xlabel('Date')\n",
    "        plt.ylabel('Value')\n",
    "        plt.legend()\n",
    "\n",
    "        # Save the plot with a dynamic filename\n",
    "        file_name = f\"{df_name_x}_{df_name_y}_median_extremes_plot.{image_format}\"\n",
    "        file_path = os.path.join(folder_name, file_name)\n",
    "        plt.savefig(file_path, format=image_format, bbox_inches='tight')\n",
    "\n",
    "        plt.close()\n",
    "\n",
    "    return f\"Images successfully saved in the '{folder_name}' folder.\"\n",
    "\n",
    "#plot_columns_with_median_and_extremes(threshold_big=0, threshold_small=0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Leading Coefficients"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Find which coefficient is ahead of the other on average"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [],
   "source": [
    "def leading_on_avg(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    extreme_values = extreme_values_of_all_dfs(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    median_values = decide_median_value(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    list_of_pairs = []\n",
    "\n",
    "    for j in range(len(median_values)):\n",
    "        v1 = 0\n",
    "        v2 = 0\n",
    "        v3 = 0\n",
    "        for i in range(len(extreme_values)):\n",
    "            for period in extreme_values[i]:\n",
    "                if period[5] == median_values[j][0]:\n",
    "                    t1, t2 = period[4]\n",
    "                    m1, m2 = period[3]\n",
    "                    median = period[6]\n",
    "                    if t1 < t2:\n",
    "                        if ((m1 <= median) and (m2 <= median)) or ((m1 >= median) and (m2 >= median)):\n",
    "                            v1 += 1\n",
    "                        else:\n",
    "                            continue\n",
    "                    elif t2 < t1:\n",
    "                        if ((m1 <= median) and (m2 <= median)) or ((m1 >= median) and (m2 >= median)):\n",
    "                            v2 += 1\n",
    "                        else:\n",
    "                            continue\n",
    "                    elif t1 == t2:\n",
    "                        v3+=1\n",
    "        sum_of_pair = v1 + v2 +v3\n",
    "        pair = [median_values[j][1].columns, v1, v2, v3, sum_of_pair]\n",
    "        list_of_pairs.append(pair)\n",
    "\n",
    "    return list_of_pairs\n",
    "\n",
    "#leading_on_avg()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Put it all in a dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_leading_coef(save_excel = 'no', cell_width = 50, excel_name = 'Leading coefficient', number=2, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window = 75, polyorder = 3):\n",
    "    leading = leading_on_avg(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window = svgal_window, polyorder = polyorder)\n",
    "    corr_df = all_corr_parametrized(number = number, window = window, threshold_small = threshold_small, threshold_big = threshold_big, decimal = decimal)\n",
    "\n",
    "    data = {\n",
    "        \"Pairs\": [],\n",
    "        \"Leading Factor\": [],\n",
    "        \"Lagging Factor\": [],\n",
    "        \"Percentage Superior (%)\": [],\n",
    "        \"Total Counts\": [],\n",
    "        \"Counts Leading\": [],\n",
    "        \"Counts Lagging\": [],\n",
    "        \"Counts Equal\": []\n",
    "    }\n",
    "    \n",
    "    for i in range(len(leading)):\n",
    "        factor_1, factor_2 = leading[i][0][0], leading[i][0][1]\n",
    "        counts1, counts2, counts_equal = leading[i][1], leading[i][2], leading[i][3]\n",
    "        total_comparisons = leading[i][4]\n",
    "        \n",
    "        if leading[i][1] > leading[i][2]:\n",
    "            leading_factor = factor_1\n",
    "            lagging_factor = factor_2\n",
    "            leading_counts = counts1\n",
    "            lagging_counts = counts2\n",
    "            percentage = round(100 * (leading[i][1] / total_comparisons), 2)\n",
    "        elif leading[i][1] < leading[i][2]:\n",
    "            leading_factor = factor_2\n",
    "            lagging_factor = factor_1\n",
    "            leading_counts = counts2\n",
    "            lagging_counts = counts1\n",
    "            percentage = round(100 * (leading[i][2] / total_comparisons), 2)\n",
    "        else:\n",
    "            leading_factor = \"Undetermined\"\n",
    "            lagging_factor = \"Undetermined\"\n",
    "            percentage = -10\n",
    "            leading_counts = lagging_counts = counts1\n",
    "        \n",
    "        pair_name = f\"{factor_1}, {factor_2}:\"\n",
    "        data[\"Pairs\"].append(pair_name)\n",
    "        data[\"Leading Factor\"].append(leading_factor)\n",
    "        data[\"Lagging Factor\"].append(lagging_factor)\n",
    "        data[\"Percentage Superior (%)\"].append(percentage)\n",
    "        data[\"Total Counts\"].append(total_comparisons)\n",
    "        data[\"Counts Leading\"].append(leading_counts)\n",
    "        data[\"Counts Lagging\"].append(lagging_counts)\n",
    "        data[\"Counts Equal\"].append(counts_equal)\n",
    "    \n",
    "    # Create a DataFrame from the data dictionary.\n",
    "    df = pd.DataFrame(data)\n",
    "    df.set_index(\"Pairs\", inplace=True)\n",
    "\n",
    "    new_corr_index = []\n",
    "    for idx in corr_df.index:\n",
    "        # Extract variable names from index and strip them\n",
    "        variables = [var.strip() for var in idx.strip(': ').split(', ')]\n",
    "        new_index = ', '.join(variables) + ':'\n",
    "        new_corr_index.append(new_index)\n",
    "\n",
    "    corr_df.index = new_corr_index\n",
    "    \n",
    "    merged_df = df.merge(corr_df, left_index = True, right_index=True, how='inner')\n",
    "\n",
    "    merged_df.index = [f\"{i + 1}. {pair}\" for i, pair in enumerate(merged_df.index)]\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        merged_df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "\n",
    "            # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "            # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return merged_df\n",
    "\n",
    "#return_leading_coef(number=10, threshold_small=0, threshold_big=0)"
   ]
  }
