
  {
   "cell_type": "code",
   "execution_count": 145,
   "metadata": {},
   "outputs": [],
   "source": [
    "def lin_regression_sklearn______________(std_limit, variable_to_apply_regression_on):\n",
    "    original_df = find_dates_above_below_stds(std_limit=std_limit)\n",
    "    linear_regression_df = filter_the_original_df(original_df)\n",
    "    Y = linear_regression_df[variable_to_apply_regression_on] \n",
    "    variables_list = []\n",
    "    for i in range(len(linear_regression_df.columns)):\n",
    "        if variable_to_apply_regression_on == linear_regression_df.columns[i]:\n",
    "            continue\n",
    "        else:\n",
    "            variables_list.append(linear_regression_df.columns[i])\n",
    "    X = linear_regression_df[variables_list]  \n",
    "    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)\n",
    "    model = LinearRegression()\n",
    "    model.fit(X_train, Y_train)\n",
    "    Y_pred = model.predict(X_test)\n",
    "    mse = mean_squared_error(Y_test, Y_pred)\n",
    "    r2 = r2_score(Y_test, Y_pred)\n",
    "    print(f\"Mean Squared Error: {mse}\")\n",
    "    print(f\"R^2 Score: {r2}\")\n",
    "    print(\"Coefficients:\", model.coef_)\n",
    "    print(\"Intercept:\", model.intercept_)\n",
    "\n",
    "#lin_regression_sklearn(2, variable_to_apply_regression_on='Adjusted Retail Sales Less Aut MoM (Details selling)')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Find the dataframes which match our needs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [],
   "source": [
    "list_of_needed_dataframes = ['(GDP)', '(Employment)', '(Inflation)', '(Economic Dynamic)', '(Business Conditions)', '(Housing)', '(Details selling)', '(Household)', '(Customer Trust)']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 147,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_dataframes_with_specific_name______________(name):\n",
    "    return {df_name:df for df_name, df in dict_of_df.items() if any(name in col for col in df.columns)}\n",
    "\n",
    "#return_dataframes_with_specific_name(name='GDP')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 148,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_columns_with_specific_names______________(name, df):\n",
    "    return [col for col in df.columns if name in col]\n",
    "\n",
    "#return_columns_with_specific_names('GDP', df1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Create new subdataframe for each of our needs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 149,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_sub_dataframe_further_analysis______________():\n",
    "    global GDP_df, Employment_df, Inflation_df, Economic_Dynamic_df, Business_Conditions_df, Housing_df, Details_Selling_df, Household_df, Customer_Trust_df\n",
    "\n",
    "    list_of_needed_dataframes = ['(GDP)', '(Employment)', '(Inflation)', '(Economic Dynamic)', '(Business Conditions)', '(Housing)', '(Details selling)', '(Household)', '(Customer Trust)']\n",
    "    \n",
    "    GDP_data = {}\n",
    "    Employment_data = {}\n",
    "    Inflation_data = {}\n",
    "    Economic_Dynamic_data = {}\n",
    "    Business_Conditions_data = {}\n",
    "    Housing_data = {}\n",
    "    Details_Selling_data = {}\n",
    "    Household_data = {}\n",
    "    Customer_Trust_data = {}\n",
    "\n",
    "    # Iterate through the global variables\n",
    "    for i in range(1, count_dfs(df) + 2):\n",
    "        df_name = f'df{i}'\n",
    "        if df_name in globals():\n",
    "            df = globals()[df_name]\n",
    "            date_col = df.index.name if df.index.name else f'{df_name}_date'\n",
    "            df = df.reset_index().rename(columns={'index': date_col})\n",
    "            for cols in df.columns:\n",
    "                if cols == date_col:\n",
    "                    continue\n",
    "                for name in list_of_needed_dataframes:\n",
    "                    if name in cols:\n",
    "                        if name == '(GDP)':\n",
    "                            GDP_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            GDP_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Employment)':\n",
    "                            Employment_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Employment_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Inflation)':\n",
    "                            Inflation_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Inflation_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Economic Dynamic)':\n",
    "                            Economic_Dynamic_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Economic_Dynamic_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Business Conditions)':\n",
    "                            Business_Conditions_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Business_Conditions_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Housing)':\n",
    "                            Housing_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Housing_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Details selling)':\n",
    "                            Details_Selling_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Details_Selling_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Household)':\n",
    "                            Household_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Household_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Customer Trust)':\n",
    "                            Customer_Trust_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Customer_Trust_data[f'{cols}'] = df[cols]\n",
    "\n",
    "    # Convert dictionaries to dataframes\n",
    "    GDP_df = pd.DataFrame(GDP_data)\n",
    "    Employment_df = pd.DataFrame(Employment_data)\n",
    "    Inflation_df = pd.DataFrame(Inflation_data)\n",
    "    Economic_Dynamic_df = pd.DataFrame(Economic_Dynamic_data)\n",
    "    Business_Conditions_df = pd.DataFrame(Business_Conditions_data)\n",
    "    Housing_df = pd.DataFrame(Housing_data)\n",
    "    Details_Selling_df = pd.DataFrame(Details_Selling_data)\n",
    "    Household_df = pd.DataFrame(Household_data)\n",
    "    Customer_Trust_df = pd.DataFrame(Customer_Trust_data)\n",
    "\n",
    "#create_sub_dataframe_further_analysis()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 150,
   "metadata": {},
   "outputs": [],
   "source": [
    "#list_of_new_dfs = ['GDP_df', 'Employment_df', 'Inflation_df', 'Economic_Dynamic_df', 'Business_Conditions_df', 'Housing_df', 'Details_Selling_df', 'Household_df', 'Customer_Trust_df']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### GDP Analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We remember that:\n",
    "\n",
    "* GDP > 0 : Expansion \n",
    "\n",
    "* GDP < 0 : recession\n",
    "\n",
    "* Pivot : 0\n",
    "\n",
    "* Dynamique --> 3-4 derniers trimestres, est ce haussier ou baissier ?\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Find periods of expansion and recession"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Function to find these periods"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 151,
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_expansion_recession______________(df, name='GDP', threshold=0):\n",
    "    all_periods = []\n",
    "\n",
    "    columns_names = [col for col in df.columns if name in col and pd.api.types.is_numeric_dtype(df[col])]\n",
    "    for col in columns_names:\n",
    "        periods = []\n",
    "        above_threshold = df.iloc[0][col] > threshold\n",
    "        current_period = [df.index[0], None, above_threshold]\n",
    "\n",
    "        for index, value in df[col].items():\n",
    "            if value > threshold and not above_threshold:\n",
    "                current_period[1] = index\n",
    "                periods.append(current_period + [col])\n",
    "                current_period = [index, None, True]\n",
    "                above_threshold = True\n",
    "            elif value < threshold and above_threshold:\n",
    "                current_period[1] = index\n",
    "                periods.append(current_period + [col])\n",
    "                current_period = [index, None, False]\n",
    "                above_threshold = False\n",
    "\n",
    "        if current_period[1] is None:\n",
    "            current_period[1] = df.index[-1]\n",
    "            periods.append(current_period + [col])\n",
    "\n",
    "        for period in periods:\n",
    "            start_index, end_index, above_threshold, col_name = period\n",
    "            period_data = df.loc[start_index:end_index]\n",
    "            extreme_value = period_data[col_name].max() if above_threshold else period_data[col_name].min()\n",
    "            period.extend([period_data, extreme_value])\n",
    "\n",
    "        all_periods.append(periods)\n",
    "\n",
    "    return all_periods\n",
    "\n",
    "#x = find_expansion_recession(GDP_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Graph them"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 152,
   "metadata": {},
   "outputs": [],
   "source": [
    "def graph_expansion_recession_past_dynamic______________(weeks, name, threshold=0):\n",
    "    df_dict = return_dataframes_with_specific_name(name=name)\n",
    "\n",
    "    for df_name, df in df_dict.items():\n",
    "        columns_names = return_columns_with_specific_names(name=name, df=df)\n",
    "        periods = find_expansion_recession(df, name=name, threshold=threshold)\n",
    "        \n",
    "        for column in columns_names:\n",
    "            a = 0\n",
    "            b = 0\n",
    "            plt.figure(figsize=(24, 12))\n",
    "            plt.plot(df.index, df[column], label=f'{df_name} - {column}')  # Plotting with DataFrame and column\n",
    "            \n",
    "            # Shade the periods above or below the threshold\n",
    "            for period_group in periods:\n",
    "                for period in period_group:\n",
    "                    if period[3] == column:\n",
    "                        start_index, end_index, above_threshold, col_name, period_data, extreme_value = period\n",
    "                        if above_threshold:\n",
    "                            a += 1\n",
    "                            plt.fill_between(df.loc[start_index:end_index].index, threshold, df.loc[start_index:end_index][column], color='green', alpha=0.3)\n",
    "                        else:\n",
    "                            b += 1\n",
    "                            plt.fill_between(df.loc[start_index:end_index].index, df.loc[start_index:end_index][column], threshold, color='red', alpha=0.3)\n",
    "\n",
    "            # Adding horizontal line at the threshold\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=2, label='Threshold')\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=0, label=f'{a} periods of expansion')\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=0, label=f'{b} periods of recession')\n",
    "\n",
    "            # Adding vertical line 'weeks' before the most recent date\n",
    "            if len(df.index) > 0:\n",
    "                most_recent_date = df.index[-1]\n",
    "                weeks_before = most_recent_date - pd.DateOffset(weeks=weeks)\n",
    "                plt.axvline(x=weeks_before, color='r', linestyle='--', linewidth=2, label=f'Last {weeks} weeks')\n",
    "\n",
    "            plt.xlabel('Time')\n",
    "            plt.ylabel('Value')\n",
    "            plt.title(f'{column} Over Time')\n",
    "            plt.legend()\n",
    "            plt.show()\n",
    "\n",
    "# Example usage:\n",
    "#graph_expansion_recession_past_dynamic(17*3, 'GDP', threshold=0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Find the dynamic of the last 3-4 trimesters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 153,
   "metadata": {},
   "outputs": [],
   "source": [
    "def past_trimesters_dynamic______________(weeks, name):\n",
    "    df_dict = return_dataframes_with_specific_name(name=name)\n",
    "    name_and_characteristics = []\n",
    "    \n",
    "    for df_name, df in df_dict.items():\n",
    "        columns_names = return_columns_with_specific_names(name=name, df=df)\n",
    "        \n",
    "        for column in columns_names:\n",
    "            # Extract the relevant rows based on the index condition\n",
    "            df_filtered = df[df.index >= df.index[-1] - pd.DateOffset(weeks=weeks)]\n",
    "            \n",
    "            if df_filtered.empty:\n",
    "                continue\n",
    "            \n",
    "            values = df_filtered[column]\n",
    "            \n",
    "            # Calculate required statistics\n",
    "            max_value = values.max()\n",
    "            min_value = values.min()\n",
    "            average_value = values.mean()\n",
    "            median_value = values.median()\n",
    "            slope, intercept, r_value, p_value, std_err = linregress(df_filtered.index.map(pd.Timestamp.toordinal), values)\n",
    "            dispersion = values.std()\n",
    "            \n",
    "            characteristics = {\n",
    "                'Dataframe': df_name,\n",
    "                'Column': column,\n",
    "                'Max': float(max_value),\n",
    "                'Min': float(min_value),\n",
    "                'Average': float(average_value),\n",
    "                'Median': float(median_value),\n",
    "                'Slope': float(slope),\n",
    "                'Standard deviation': float(dispersion)\n",
    "            }\n",
    "            \n",
    "            name_and_characteristics.append(characteristics)\n",
    "    \n",
    "    return name_and_characteristics\n",
    "\n",
    "#past_trimesters_dynamic(3*17, 'GDP')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### We are currently in a period of slow economic growth, where growth is slowing down. However, we are yet to turn in a period of recession"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Employment Analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We remember that:\n",
    "\n",
    "* There is no pivot point for unemployment\n",
    "    * We define the mins and maxs according to the recession and high expansion periods (flotting GDP pivot)\n",
    "* Find the dynamic of the trimesters after the pivot point\n",
    "    * What is the lapse of time such that the pivot of unemployment changes ?\n",
    "    * What is the historical average to change this tendency ?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Finding the relation between unemployment and GDP"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "metadata": {},
   "outputs": [],
   "source": [
    "def normalize_y_axis_threshold______________(svgal_window=75, polyorder=3, number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3):\n",
    "    l = list_of_global_all_corr_parametrized(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    smoothed_df = smooth_dataframe(svgal_window=svgal_window, polyorder=polyorder, number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    results = []\n",
    "    for i in range(len(dict_of_df)):\n",
    "        for j in range(len(dict_of_df)):\n",
    "            dfx_name = f'df{i+1}'\n",
    "            dfy_name = f'df{j+1}'\n",
    "            if dfx_name in globals() and dfy_name in globals():\n",
    "                dfx, dfy = smoothed_df[i], smoothed_df[j]\n",
    "                for x in range(len(l)):\n",
    "                    for y in range(len(dfx.columns)):\n",
    "                        for z in range(len(dfy.columns)):\n",
    "                            if (l[x][0] == dfx.columns[y]) and (l[x][1] == dfy.columns[z]):\n",
    "                                normalized_df = normalize_columns(dfy, dfx, dfx.columns[y], dfy.columns[z])\n",
    "                                results.append(([dfx.columns[y], dfy.columns[z]], normalized_df))\n",
    "    return results\n",
    "\n",
    "#normalize_y_axis_threshold()"

  {
   "cell_type": "code",
   "execution_count": 142,
   "metadata": {},
   "outputs": [],
   "source": [
    "l1 = [\n",
    "    \"Chicago Fed National Activity (Business Conditions)\",\n",
    "    \"Conference Board US Leading In (Business Conditions)\",\n",
    "    \"ISM Manufacturing PMI SA (Business Conditions)\",\n",
    "    \"ISM Services PMI (Business Conditions)\",\n",
    "    \"Market News International Chic (Business Conditions)\",\n",
    "    \"Philadelphia Fed Business Outl (Business Conditions)\",\n",
    "    \"Richmond Manufacturing Survey (Business Conditions)\",\n",
    "    \"US Composite PMI SA (Business Conditions)\",\n",
    "    \"US Empire State Manufacturing (Business Conditions)\",\n",
    "    \"US Manufacturing PMI SA (Business Conditions)\",\n",
    "    \"US Services PMI Business Activ (Business Conditions)\",\n",
    "    \"Conference Board Consumer Conf (Customer Trust)\",\n",
    "    \"University of Michigan Consume (Customer Trust)\",\n",
    "    \"Adjusted Retail Sales Less Aut MoM (Details selling)\",\n",
    "    \"Adjusted Retail Sales Less Aut YoY (Details selling)\",\n",
    "    \"US Auto Sales Total Annualized (Details selling)\",\n",
    "    \"US Capacity Utilization % of T (Economic Dynamic)\",\n",
    "    \"US Durable Goods New Orders To (Economic Dynamic)\",\n",
    "    \"US Industrial Production YOY S (Economic Dynamic)\",\n",
    "    \"ADP National Employment Report (Employment)\",\n",
    "    \"Conference Board US Leading In (Employment)\",\n",
    "    \"U-3 US Unemployment Rate Total (Employment)\",\n",
    "    \"US Employees on Nonfarm Payrol (Employment)\",\n",
    "    \"GDP US Chained Dollars QoQ SAA (GDP)\",\n",
    "    \"GDP US Chained Dollars YoY SA (GDP)\",\n",
    "    \"US GDP Nominal Dollars YoY SA (GDP)\",\n",
    "    \"US GDP Price Index QoQ SAAR (GDP)\",\n",
    "    \"US Personal Consumption Expend % (Household)\",\n",
    "    \"US Personal Consumption Expend (Household)\",\n",
    "    \"US Personal Income YoY SA (Household)\",\n",
    "    \"Private Housing Authorized by (Housing)\",\n",
    "    \"US NAR Total Existing Homes Sa (Housing)\",\n",
    "    \"US Avg Hourly Earnings Private (Inflation)\",\n",
    "    \"US CPI Urban Consumers Less Fo (Inflation)\",\n",
    "    \"US PPI Finished Goods Less Foo (Inflation)\",\n",
    "    \"US Personal Consumption Expend (Inflation)\",\n",
    "    \"Generic 1st 'CL' Future (Materials)\",\n",
    "    \"Gold Spot   $/Oz (Materials)\",\n",
    "    \"Iron Ore Spot Price Index 62% (Materials)\",\n",
    "    \"LME COPPER    3MO ($) (Materials)\"\n",
    "]"
   ]
  }

  {
   "cell_type": "code",
   "execution_count": 155,
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_periods_above_below_threshold______________(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    df_list = normalize_y_axis_threshold(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    all_periods = []\n",
    "    \n",
    "    for df_item in df_list:\n",
    "        columns = df_item[0]\n",
    "        df = df_item[1]\n",
    "        periods = []\n",
    "        \n",
    "        for col in columns:\n",
    "            if \"(GDP)\" in col:\n",
    "                threshold = 0\n",
    "                above_threshold = df.iloc[0][col] > threshold\n",
    "                current_period = [df.index[0], None, above_threshold]\n",
    "                \n",
    "                for index, row in df.iterrows():\n",
    "                    value = row[col]\n",
    "                    \n",
    "                    if value > threshold and not above_threshold:\n",
    "                        current_period[1] = index\n",
    "                        periods.append((current_period[0], current_period[1], current_period[2], col, df))\n",
    "                        current_period = [index, None, True]\n",
    "                        above_threshold = True\n",
    "                    elif value < threshold and above_threshold:\n",
    "                        current_period[1] = index\n",
    "                        periods.append((current_period[0], current_period[1], current_period[2], col, df))\n",
    "                        current_period = [index, None, False]\n",
    "                        above_threshold = False\n",
    "                \n",
    "                if current_period[1] is None:\n",
    "                    current_period[1] = df.index[-1]\n",
    "                    periods.append((current_period[0], current_period[1], current_period[2], col, df))\n",
    "        \n",
    "        all_periods.append(periods)\n",
    "    \n",
    "    return all_periods\n",
    "\n",
    "#find_periods_above_below_threshold()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 156,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extreme_values_of_all_dfs_threshold______________(number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    list_final = []\n",
    "    periods_list = find_periods_above_below_threshold(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    \n",
    "    for periods in periods_list:\n",
    "        list_of_lists = []\n",
    "        for period in periods:\n",
    "            start_index, end_index, above_threshold, col_name, df = period\n",
    "            period_data = df.loc[start_index:end_index]\n",
    "            \n",
    "            if above_threshold:\n",
    "                max_value = period_data[col_name].max()\n",
    "                max_date = period_data[col_name].idxmax()\n",
    "                above = 'Above threshold'\n",
    "                x = [start_index, end_index, above, max_value, max_date, [col_name]]\n",
    "                list_of_lists.append(x)\n",
    "            else:\n",
    "                min_value = period_data[col_name].min()\n",
    "                min_date = period_data[col_name].idxmin()\n",
    "                below = 'Below threshold'\n",
    "                y = [start_index, end_index, below, min_value, min_date, [col_name]]\n",
    "                list_of_lists.append(y)\n",
    "        list_final.append(list_of_lists)\n",
    "    \n",
    "    return list_final\n",
    "\n",
    "#extreme_values_of_all_dfs_threshold()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 157,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_columns_with_threshold_and_extremes______________(number=2, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3, svgal_window=75, polyorder=3):\n",
    "    df_list = normalize_y_axis(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    extreme_values = extreme_values_of_all_dfs_threshold(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal, svgal_window=svgal_window, polyorder=polyorder)\n",
    "    x = 0\n",
    "\n",
    "    colors = ['blue', 'orange']\n",
    "    dot_colors = ['blue', 'orange']\n",
    "\n",
    "    for df_item in df_list:\n",
    "        [df_name_x, df_name_y], df = df_item\n",
    "        if ('(GDP)' in df_name_x or '(GDP)' in df_name_y) and ('(Employment)' in df_name_x or '(Employment)' in df_name_y):\n",
    "            x += 1\n",
    "            title = f'{x}. {df_name_x} and {df_name_y} with Threshold Line and Extremes'\n",
    "            print(title)\n",
    "            \n",
    "            plt.figure(figsize=(12, 6))\n",
    "            plt.axhline(y=0, color='red', linestyle='--', label='Threshold = 0')\n",
    "            \n",
    "            for col_idx, col in enumerate(df.columns):\n",
    "                color = colors[col_idx % len(colors)]\n",
    "                plt.plot(df.index, df[col], label=f'{col}', color=color, linewidth=1.5)\n",
    "\n",
    "            dot_color_idx = 0\n",
    "            for extremes in extreme_values:\n",
    "                for extreme in extremes:\n",
    "                    if df_name_x in extreme[5] or df_name_y in extreme[5]:\n",
    "                        extreme_values_list = [extreme[3]]\n",
    "                        extreme_dates_list = [extreme[4]]\n",
    "\n",
    "                        for extreme_date, extreme_value in zip(extreme_dates_list, extreme_values_list):\n",
    "                            plt.scatter(extreme_date, extreme_value, color=dot_colors[dot_color_idx], edgecolor='black', zorder=5, label='Extreme Value' if col not in locals() else \"\")\n",
    "                            locals()[col] = True\n",
    "                            dot_color_idx = 1 - dot_color_idx\n",
    "                \n",
    "            plt.title(title)\n",
    "            plt.xlabel('Date')\n",
    "            plt.ylabel('Value')\n",
    "            plt.legend()\n",
    "            plt.show()\n",
    "        else:\n",
    "            continue\n",
    "\n",
    "#plot_columns_with_threshold_and_extremes(threshold_big=0, threshold_small=0)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Smooth the data"
   ]
  },
  
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Put all the pairs in a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 159,
   "metadata": {},
   "outputs": [],
   "source": [
    "def put_pairs_in_list______________(dfx, dfy):\n",
    "    indexes_list = []\n",
    "    for i in range(0, len(dfx.columns), 2):\n",
    "        for j in range(0, len(dfy.columns), 2):\n",
    "            if \"Dates for\" in dfx.columns[i] and \"Dates for\" in dfy.columns[j]:\n",
    "                pairs = [dfx.columns[i], dfx.columns[i+1], dfy.columns[j], dfy.columns[j+1]]\n",
    "                indexes_list.append(pairs)\n",
    "    return indexes_list\n",
    "\n",
    "#put_pairs_in_list(GDP_df, Employment_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Create a sub dataframe for every variable in the pair"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 160,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_pair_dataframes______________(pair_list):\n",
    "    pair_dfs = []\n",
    "    for pair in pair_list:\n",
    "        dates1_col, var1_col, dates2_col, var2_col = pair\n",
    "        \n",
    "        # Retrieve dataframes and columns from globals\n",
    "        df1 = next((globals()[df] for df in globals() if isinstance(globals()[df], pd.DataFrame) and dates1_col in globals()[df].columns), None)\n",
    "        df2 = next((globals()[df] for df in globals() if isinstance(globals()[df], pd.DataFrame) and dates2_col in globals()[df].columns), None)\n",
    "        \n",
    "        if df1 is not None and df2 is not None:\n",
    "            # Create new dataframes for the pairs\n",
    "            df_pair1 = df1[[dates1_col, var1_col]].set_index(dates1_col)\n",
    "            df_pair2 = df2[[dates2_col, var2_col]].set_index(dates2_col)\n",
    "            \n",
    "            pair_dfs.append([df_pair1, df_pair2])\n",
    "        \n",
    "    return pair_dfs\n",
    "\n",
    "#create_pair_dataframes(put_pairs_in_list(GDP_df, Employment_df))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 161,
   "metadata": {},
   "outputs": [],
   "source": [
    "def normalize_columns_new______________(df1, df2):\n",
    "    scaler = MinMaxScaler()\n",
    "\n",
    "    # Ensure indices are unique\n",
    "    df1 = df1.reset_index().drop_duplicates().set_index(df1.index.name)\n",
    "    df2 = df2.reset_index().drop_duplicates().set_index(df2.index.name)\n",
    "\n",
    "    combined = pd.concat([df1, df2], axis=1)\n",
    "    normalized_values = scaler.fit_transform(combined)\n",
    "    normalized_df = pd.DataFrame(normalized_values, columns=combined.columns, index=combined.index)\n",
    "    \n",
    "    return normalized_df[df1.columns], normalized_df[df2.columns]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 162,
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_and_plot_pairs______________(pair_dataframes, svgal_window=300, polyorder=2):\n",
    "    for idx, (df_pair1, df_pair2) in enumerate(pair_dataframes):\n",
    "        smoothed_df1 = smooth_the_dataframe(df_pair1, svgal_window, polyorder)\n",
    "        smoothed_df2 = smooth_the_dataframe(df_pair2, svgal_window, polyorder)\n",
    "        normalized_df1, normalized_df2 = normalize_columns(smoothed_df1, smoothed_df2)\n",
    "        \n",
    "        # Find the overlapping date range\n",
    "        common_index = normalized_df1.index.intersection(normalized_df2.index)\n",
    "        normalized_df1 = normalized_df1.loc[common_index]\n",
    "        normalized_df2 = normalized_df2.loc[common_index]\n",
    "        \n",
    "        # Calculate the median\n",
    "        median_df1 = normalized_df1.median().median()\n",
    "        median_df2 = normalized_df2.median().median()\n",
    "\n",
    "        # Plot the data\n",
    "        plt.figure(figsize=(10, 6))\n",
    "        plt.plot(normalized_df1.index, normalized_df1[normalized_df1.columns[0]], label=normalized_df1.columns[0])\n",
    "        if len(normalized_df1.columns) > 1:\n",
    "            plt.plot(normalized_df1.index, normalized_df1[normalized_df1.columns[1]], label=normalized_df1.columns[1])\n",
    "        plt.plot(normalized_df2.index, normalized_df2[normalized_df2.columns[0]], label=normalized_df2.columns[0])\n",
    "        if len(normalized_df2.columns) > 1:\n",
    "            plt.plot(normalized_df2.index, normalized_df2[normalized_df2.columns[1]], label=normalized_df2.columns[1])\n",
    "\n",
    "        # Plot median lines\n",
    "        plt.axhline(y=median_df1, color='blue', linestyle='--', label=f'Median {normalized_df1.columns[0]}')\n",
    "        plt.axhline(y=median_df2, color='green', linestyle='--', label=f'Median {normalized_df2.columns[0]}')\n",
    "\n",
    "        plt.legend()\n",
    "        plt.xlabel('Date')\n",
    "        plt.ylabel('Normalized Values')\n",
    "        plt.title(f'Normalized and Smoothed Plot: Pair {idx + 1}')\n",
    "        plt.show()\n",
    "\n",
    "#process_and_plot_pairs(create_pair_dataframes(put_pairs_in_list(GDP_df, Employment_df)))"
   ]
  }


