{
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Filter the df, only keep indicators, remove all indices, crypto, etc..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [],
   "source": [
    "def filter_the_original_df(std_limit, save_excel='no', cell_width=50, excel_name=\"0's and 1's sheet\"):\n",
    "    df = find_dates_above_below_stds(std_limit=std_limit)\n",
    "    mask = df.index.to_frame().apply(lambda x: x.astype(str).str.contains('Crypto|FED|Stock Index|Sub S&P500 Indicator|Materials').any(), axis=1)\n",
    "    df = df.astype(str)\n",
    "    replacements = {'a': std_limit, 'b': -std_limit, 'ab': 0, '': 0, None: 0}\n",
    "    df = df[~mask]\n",
    "    pd.set_option(\"future.no_silent_downcasting\", True)\n",
    "    df = df.replace(replacements)\n",
    "    df = df.apply(pd.to_numeric, errors = 'coerce')\n",
    "    df = df.loc[:, (df != 0).any(axis=0)]\n",
    "    df = df.transpose()\n",
    "    if save_excel=='yes':\n",
    "        df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "\n",
    "            # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "            # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return df\n",
    "\n",
    "#filter_the_original_df(2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Combine numerous standard deviations into a single dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [],
   "source": [
    "def combine_1_and_2_stds(save_excel='no', cell_width=50, excel_name=\"Combined 1's and 2's sheet\"):\n",
    "    std_1 = filter_the_original_df(1).transpose()\n",
    "    std_2 = filter_the_original_df(2).transpose()\n",
    "    merged_df = pd.concat([std_1, std_2], axis=1)\n",
    "    merged_df = merged_df.T.groupby(merged_df.T.index).sum().T\n",
    "    replacements = {3:2, -3:-2}\n",
    "    merged_df = merged_df.replace(replacements)\n",
    "    merged_df = merged_df.transpose()\n",
    "    new_index = [datetime(year=idx[0], month=idx[1], day=1) for idx in merged_df.index]\n",
    "    merged_df.index = new_index\n",
    "    merged_df = merged_df.transpose()\n",
    "    if save_excel=='yes':\n",
    "        merged_df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "\n",
    "            # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "            # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return merged_df\n",
    "\n",
    "#combine_1_and_2_stds(save_excel=\"yes\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_combined_1_and_2_stds(save_excel='no', cell_width=50, excel_name=\"Sum of 1's and 2's sheet\"):\n",
    "    merged_df = combine_1_and_2_stds()\n",
    "    merged_df = merged_df.sum()\n",
    "    if save_excel=='yes':\n",
    "        merged_df.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "\n",
    "            # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "            # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "    return merged_df\n",
    "#sum_combined_1_and_2_stds(save_excel=\"yes\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Do a multivariate linear regression and keep only the 5 most relevant positive and negative values for each indicator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [],
   "source": [
    "def lin_regression_stats_model(std_limit, variable_to_apply_regression_on, save_excel='no', cell_width=50, excel_name=\"Linear Regression Stats\"):\n",
    "    linear_regression_df = filter_the_original_df(std_limit=std_limit)\n",
    "    Y = linear_regression_df[variable_to_apply_regression_on]\n",
    "    variables_list = []\n",
    "    for i in range(len(linear_regression_df.columns)):\n",
    "        if variable_to_apply_regression_on == linear_regression_df.columns[i]:\n",
    "            continue\n",
    "        else:\n",
    "            variables_list.append(linear_regression_df.columns[i])\n",
    "    X = linear_regression_df[variables_list]\n",
    "    X = sm.add_constant(X)\n",
    "    model = sm.OLS(Y, X).fit()\n",
    "    #print(model.summary())\n",
    "    summary_stats = model.summary2().tables[0]  # Model statistics\n",
    "    summary_table = model.summary2().tables[1]  # Summary2 has a cleaner table format\n",
    "    combined_summary = pd.concat([summary_stats, summary_table], axis=0)\n",
    "    if save_excel == 'yes':\n",
    "        combined_summary.to_excel(f\"{excel_name}.xlsx\")\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return model.summary()\n",
    "\n",
    "#lin_regression_stats_model(save_excel='yes', std_limit=1, variable_to_apply_regression_on='Adjusted Retail Sales Less Aut MoM (Details selling)')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [],
   "source": [
    "def retain_5_highest_and_lowest(std_limit, variable_to_apply_regression_on, save_excel='no', cell_width=50, excel_name=\"5 Highest and Lowest Coefficients\"):\n",
    "    df = lin_regression_stats_model(std_limit=std_limit, variable_to_apply_regression_on=variable_to_apply_regression_on)\n",
    "    \n",
    "    # Extract the coefficients table from the summary object\n",
    "    coeff_table = df.tables[1]\n",
    "    \n",
    "    # Extract rows from the coefficient table and convert them into a DataFrame\n",
    "    coeff_data = []\n",
    "    for row in coeff_table.data[1:]:  # Skip the header row\n",
    "        coeff_data.append([row[0], float(row[1])])  # Assuming 'coef' is the second column\n",
    "\n",
    "    coeff_df = pd.DataFrame(coeff_data, columns=['Variable', 'coef'])\n",
    "    \n",
    "    # Sort by the coef column to get the highest and lowest values\n",
    "    sorted_coeff_df = coeff_df.sort_values(by='coef')\n",
    "    \n",
    "    # Get the 5 lowest coefficients\n",
    "    lowest_5 = sorted_coeff_df.head(5).values.tolist()\n",
    "    \n",
    "    # Get the 5 highest coefficients\n",
    "    highest_5 = sorted_coeff_df.tail(5).values.tolist()\n",
    "\n",
    "    combined_list = [variable_to_apply_regression_on, lowest_5, highest_5]\n",
    "\n",
    "    if save_excel == \"yes\":\n",
    "        # Create a new workbook\n",
    "        wb = Workbook()\n",
    "        ws = wb.active\n",
    "        ws.title = '5 Highest and Lowest Coefficients'\n",
    "\n",
    "        # Write the results to the worksheet\n",
    "        ws[f'A1'] = 'Variable'\n",
    "        ws[f'B1'] = 'Coefficient'\n",
    "\n",
    "        for i, (variable, coef) in enumerate(lowest_5, start=2):\n",
    "            ws[f'A{i}'] = variable\n",
    "            ws[f'B{i}'] = coef\n",
    "\n",
    "        ws[f'A8'] = 'Variable'\n",
    "        ws[f'B8'] = 'Coefficient'\n",
    "\n",
    "        for i, (variable, coef) in enumerate(highest_5, start=9):\n",
    "            ws[f'A{i}'] = variable\n",
    "            ws[f'B{i}'] = coef\n",
    "\n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "\n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return combined_list\n",
    "\n",
    "#retain_5_highest_and_lowest(1, 'Chicago Fed National Activity (Business Conditions)')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [],
   "source": [
    "def all_variables_highest_lowest(std_limit):\n",
    "    x = filter_the_original_df(std_limit=std_limit)\n",
    "    data = []\n",
    "    for variable in x.columns:\n",
    "        data.append(retain_5_highest_and_lowest(std_limit=std_limit, variable_to_apply_regression_on=variable))\n",
    "    transformed_data = []\n",
    "\n",
    "# Iterate over each element in the list of lists\n",
    "    for entry in data:\n",
    "        variable = entry[0]\n",
    "        corresponding_variables = entry[1]\n",
    "        anti_variables = entry[2]\n",
    "        \n",
    "        # Iterate over corresponding variables and append to the transformed data\n",
    "        for var, value in corresponding_variables:\n",
    "            transformed_data.append([variable, var, value])\n",
    "        \n",
    "        # Iterate over anti-variables and append to the transformed data\n",
    "        for var, value in anti_variables:\n",
    "            transformed_data.append([variable, var, value])\n",
    "\n",
    "    # Convert the transformed data into a DataFrame\n",
    "    df = pd.DataFrame(transformed_data, columns=[\"Variable\", \"SubVariable\", \"Correlation Value\"])\n",
    "    df.set_index(\"Variable\", inplace=True)\n",
    "    return df\n",
    "\n",
    "#all_variables_highest_lowest(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [],
   "source": [
    "def export_highest_lowest_to_xlsx(std_limit, excel_filename=\"highlighted_dataframe\", cell_width=50):\n",
    "    dataframe = all_variables_highest_lowest(std_limit=std_limit)\n",
    "    dataframe.to_excel(f\"{excel_filename}.xlsx\", engine='openpyxl')\n",
    "\n",
    "    wb = Workbook()\n",
    "    wb = load_workbook(f\"{excel_filename}.xlsx\")\n",
    "    ws = wb.active\n",
    "\n",
    "    # Define the fill styles for highlighting\n",
    "    red_fill = PatternFill(start_color=\"FF9999\", end_color=\"FF9999\", fill_type=\"solid\")\n",
    "    green_fill = PatternFill(start_color=\"99FF99\", end_color=\"99FF99\", fill_type=\"solid\")\n",
    "\n",
    "    # Iterate over the rows in groups of 5 and apply alternating colors\n",
    "    for i, row in enumerate(ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=ws.max_column)):\n",
    "        fill = red_fill if (i // 5) % 2 == 0 else green_fill\n",
    "        for cell in row:\n",
    "            cell.fill = fill\n",
    "\n",
    "    # Save the workbook with the applied styles\n",
    "    wb.save(f\"{excel_filename}.xlsx\")\n",
    "\n",
    "    wb = load_workbook(f\"{excel_filename}.xlsx\")\n",
    "    adjust_dimensions(wb, max_column_width=cell_width)\n",
    "    wb.save(f\"{excel_filename}.xlsx\")\n",
    "\n",
    "#export_highest_lowest_to_xlsx(1)"
   ]
  }
