"def create_corr_matrix(dataframe):\n",
    "    corr_matrix = dataframe.corr()\n",
    "    sns.heatmap(corr_matrix, annot= True)\n",
    "    plt.xticks(rotation = 90)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "    return corr_matrix"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Lineplots and normalization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "def standard_lineplot(dataframe):\n",
    "    dataframe.plot()\n",
    "    plt.xlabel('Time')\n",
    "    plt.ylabel('Value')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    return dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_column_names(dataframe):\n",
    "    column_names = dataframe.columns.tolist()\n",
    "    return column_names"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown', 'darkblue', 'magenta', 'violet', 'chocolate', 'darkgreen', 'yellow']\n",
    "\n",
    "def plot_all_of_a_df(dataframe):\n",
    "    column_names = return_column_names(dataframe)\n",
    "\n",
    "    fig, ax1 = plt.subplots(figsize=(20, 10))\n",
    "\n",
    "    # Plot the first axis\n",
    "    ax1.set_xlabel('Time')\n",
    "    ax1.set_ylabel(f'{column_names[0]}', color=colors[0])\n",
    "    ax1.plot(dataframe.index, dataframe[column_names[0]], color=colors[0], label=column_names[0])\n",
    "    ax1.tick_params(axis='y', labelcolor=colors[0])\n",
    "\n",
    "    # Initialize the current axis for further twinx\n",
    "    current_ax = ax1\n",
    "\n",
    "    # Loop through the remaining columns to create twin axes\n",
    "    for i in range(1, len(column_names)):\n",
    "        new_ax = ax1.twinx()\n",
    "        new_ax.spines['right'].set_position(('outward', 60 * i))\n",
    "        new_ax.set_ylabel(f'{column_names[i]}', color=colors[i % len(colors)])\n",
    "        new_ax.plot(dataframe.index, dataframe[column_names[i]], color=colors[i % len(colors)], label=column_names[i])\n",
    "        new_ax.tick_params(axis='y', labelcolor=colors[i % len(colors)])\n",
    "        current_ax = new_ax\n",
    "\n",
    "    # Combine legends from all axes\n",
    "    lines = []\n",
    "    labels = []\n",
    "    for ax in fig.axes:\n",
    "        ax_lines, ax_labels = ax.get_legend_handles_labels()\n",
    "        lines.extend(ax_lines)\n",
    "        labels.extend(ax_labels)\n",
    "\n",
    "    ax1.legend(lines, labels, loc='best')\n",
    "    ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=15))  # Adjust nbins as needed for density\n",
    "    ax1.tick_params(axis='x', rotation=20)  # Adjust rotation angle as needed\n",
    "\n",
    "    fig.tight_layout()\n",
    "    plt.title('Evolution of index values over time')\n",
    "    plt.show()\n",
    "\n",
    "#plot_all_of_a_df(df4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Individual Comparisons"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###### GRAPHS\n",
    "\n",
    "Graph each variables against every other variable individually\n",
    "\n",
    "This will return $ \\sum_{i=1}^{n} (i-1) $ graphs, where n is the number of columns of the dataframe\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "def two_variables_over_time(dataframe):\n",
    "    column_names = return_column_names(dataframe)\n",
    "    compared_pairs = set()  # Set to store already compared pairs\n",
    "\n",
    "    for i in range(len(column_names)):\n",
    "        for j in range(i + 1, len(column_names)):  # Iterate from i+1 to len(column_names) to avoid duplicates\n",
    "            pair = (column_names[i], column_names[j])\n",
    "            if pair not in compared_pairs:\n",
    "                fig, ax1 = plt.subplots(figsize=(20, 10))\n",
    "\n",
    "                ax1.set_xlabel('Time')\n",
    "                ax1.set_ylabel(f'{column_names[i]}', color='blue')\n",
    "                ax1.plot(dataframe.index, dataframe[f'{column_names[i]}'], color='blue', label=f'{column_names[i]}')\n",
    "                ax1.tick_params(axis='y', labelcolor='blue')\n",
    "\n",
    "                ax2 = ax1.twinx()\n",
    "                ax2.set_ylabel(f'{column_names[j]}', color='red')\n",
    "                ax2.plot(dataframe.index, dataframe[f'{column_names[j]}'], color='red', label=f'{column_names[j]}')\n",
    "                ax2.tick_params(axis='y', labelcolor='red')\n",
    "\n",
    "                ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=30))  # Adjust nbins as needed for density\n",
    "                ax1.tick_params(axis='x', rotation=20)  # Adjust rotation angle as needed\n",
    "\n",
    "                plt.title(f'{column_names[i]} and {column_names[j]} over time')\n",
    "                plt.show()\n",
    "\n",
    "                compared_pairs.add(pair)  # Add the pair to the set of compared pairs\n",
    "\n",
    "#two_variables_over_time(df4)"


  {
   "cell_type": "code",
   "execution_count": 111,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_combined_cycles_and_stds(df, dont_plot_series = 'no', plot_both_series = 'yes', index_which_series_to_plot = 1, smooth_filter = 'no', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, nbins=30, rotation=90, normalize_series ='no', plot_economic_cycle = 'no', smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, plot_fed_funds = 'no', smooth_fed = 'no', fed_as_pctg = 'no', svgal_fed_cycle = 150, fed_poly = 3, plot_sp500 = 'no', sp_as_pctg = 'no', smooth_sp500 = 'no', plot_msci = 'no', msci_as_pctg = 'no', smooth_msci = 'no', plot_nasdaq = 'no', nasdaq_as_pctg = 'no', smooth_nasdaq = 'no', indices_window = 500, indices_order = 5, plot_predictions = 'no', plot_ci = 'no'):\n",
    "    start_time = min(df.index)\n",
    "    end_time = max(df.index)\n",
    "    def align_zero(ax1, ax2):\n",
    "                    y1_min, y1_max = ax1.get_ylim()\n",
    "                    y2_min, y2_max = ax2.get_ylim()\n",
    "                    y1_zero_offset = (0 - y1_min) / (y1_max - y1_min)\n",
    "                    y2_zero_offset = (0 - y2_min) / (y2_max - y2_min)\n",
    "                    new_y2_min = y2_min + y2_zero_offset * (y2_max - y2_min) - y1_zero_offset * (y2_max - y2_min)\n",
    "                    new_y2_max = y2_max + y2_zero_offset * (y2_max - y2_min) - y1_zero_offset * (y2_max - y2_min)\n",
    "                    ax2.set_ylim(new_y2_min, new_y2_max)\n",
    "    if plot_both_series == 'no':\n",
    "        if index_which_series_to_plot == 1:\n",
    "            df[df.columns[0]] = 0\n",
    "        elif index_which_series_to_plot == 0:\n",
    "            df[df.columns[1]] = 0\n",
    "    if dont_plot_series == 'yes':\n",
    "        names_list = [\"Predictions\", \"Lower Bound\", \"Upper Bound\"]\n",
    "        for col in df.columns:\n",
    "            if col not in names_list:\n",
    "                df[col].values[:] = 0\n",
    "\n",
    "    if smooth_filter == 'no':\n",
    "        fig, ax1 = plt.subplots(figsize=(12, 6))\n",
    "        sns.lineplot(data=df[df.columns[0]], ax=ax1, label=df.columns[0])\n",
    "        ax1.set_xlabel('Date')\n",
    "        ax1.set_ylabel(df.columns[0])\n",
    "        ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=nbins))\n",
    "        ax1.tick_params(axis='x', rotation=rotation)\n",
    "        ax1.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "        if normalize_series.lower() == 'no':\n",
    "            sns.lineplot(data=df[df.columns[1]], ax=ax1, label=df.columns[1])\n",
    "        elif normalize_series.lower() == 'yes':\n",
    "            ax2 = ax1.twinx()\n",
    "            sns.lineplot(data=df[df.columns[1]], ax=ax2, color='orange', label=df.columns[1])\n",
    "            ax2.set_ylabel(df.columns[1])\n",
    "            align_zero(ax1, ax2)\n",
    "            ax2.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "            ax2.spines['right'].set_position(('outward', 0))\n",
    "    elif smooth_filter == 'yes':\n",
    "        if smooth_both_columns == 'no':\n",
    "            smoothed_df = df.copy()\n",
    "            smoothed_values = savgol_filter(df[df.columns[index_which_column_to_smooth]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[index_which_column_to_smooth]] = smoothed_values\n",
    "            fig, ax1 = plt.subplots(figsize=(12, 6))\n",
    "            sns.lineplot(data=smoothed_df[df.columns[0]], ax=ax1, label=df.columns[0])\n",
    "            ax1.set_xlabel('Date')\n",
    "            ax1.set_ylabel(df.columns[0])\n",
    "            ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=nbins))\n",
    "            ax1.tick_params(axis='x', rotation=rotation)\n",
    "            ax1.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "            if normalize_series == 'no':\n",
    "                sns.lineplot(data=smoothed_df[df.columns[1]], ax=ax1, label=df.columns[1])\n",
    "            elif normalize_series == 'yes':\n",
    "                ax2 = ax1.twinx()\n",
    "                sns.lineplot(data=smoothed_df[df.columns[1]], ax=ax2, color='orange', label=df.columns[1])\n",
    "                ax2.set_ylabel(df.columns[1])\n",
    "                ax2.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "                ax2.spines['right'].set_position(('outward', 0))\n",
    "                align_zero(ax1, ax2)\n",
    "        elif smooth_both_columns == 'yes':\n",
    "            smoothed_df = pd.DataFrame(index=df.index)\n",
    "            smoothed_values_1 = savgol_filter(df[df.columns[0]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[0]] = smoothed_values_1\n",
    "            smoothed_values_2 = savgol_filter(df[df.columns[1]], svgal_window, polyorder)\n",
    "            smoothed_df[df.columns[1]] = smoothed_values_2\n",
    "            fig, ax1 = plt.subplots(figsize=(12, 6))\n",
    "            sns.lineplot(data=smoothed_df[df.columns[0]], ax=ax1, label=df.columns[0])\n",
    "            ax1.set_xlabel('Date')\n",
    "            ax1.set_ylabel(df.columns[0])\n",
    "            ax1.xaxis.set_major_locator(plt.MaxNLocator(nbins=nbins))\n",
    "            ax1.tick_params(axis='x', rotation=rotation)\n",
    "            ax1.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "            if normalize_series.lower() == 'no':\n",
    "                sns.lineplot(data=smoothed_df[df.columns[1]], ax=ax1, label=df.columns[1])\n",
    "            else:\n",
    "                ax2 = ax1.twinx()\n",
    "                sns.lineplot(data=smoothed_df[df.columns[1]], ax=ax2, color='orange', label=df.columns[1])\n",
    "                ax2.set_ylabel(df.columns[1])\n",
    "                ax2.axhline(y=0, color='black', linestyle='--', linewidth=1)\n",
    "                ax2.spines['right'].set_position(('outward', 0))\n",
    "                align_zero(ax1, ax2)\n",
    "    \n",
    "    if plot_economic_cycle == 'yes':\n",
    "                economy_df = pd.DataFrame(list(numerical_dict_of_recessions_and_expansions_periods.items()), columns=['Date', 'Value'])\n",
    "                economy_df['Date'] = pd.to_datetime(economy_df['Date'])\n",
    "                economy_df['Value'] = pd.to_numeric(economy_df['Value'])\n",
    "                economy_df.set_index('Date', inplace=True)\n",
    "                ax3 = ax1.twinx()\n",
    "                if smooth_economic_cycle == 'no':\n",
    "                    sns.lineplot(data=economy_df['Value'], ax=ax3, color='red', label='Economic cycle')\n",
    "                    ax3.set_ylabel('Economic cycle')\n",
    "                    ax3.spines['right'].set_position(('outward', 60))  # Shift the secondary y-axis outward\n",
    "                    ax3.set_ylim(0,economy_df[\"Value\"].max()+5)\n",
    "                    align_zero(ax1, ax3)\n",
    "                elif smooth_economic_cycle == 'yes':\n",
    "                    smooth_economy = economy_df.copy()\n",
    "                    smooth_values = savgol_filter(smooth_economy[smooth_economy.columns[0]], svgal_eco_cycle, eco_poly)\n",
    "                    smooth_economy[smooth_economy.columns[0]] = smooth_values\n",
    "                    sns.lineplot(data=smooth_economy['Value'], ax=ax3, color='red', label='Economic cycle')\n",
    "                    ax3.set_ylabel('Economic cycle')\n",
    "                    ax3.spines['right'].set_position(('outward', 60))  # Shift the secondary y-axis outward\n",
    "                    align_zero(ax1, ax3)\n",
    "    if plot_fed_funds == 'yes':\n",
    "        for i in range(len(dict_of_df)):\n",
    "            df_name = f'df{i+1}'\n",
    "            if df_name in globals():\n",
    "                our_df = globals()[df_name]\n",
    "                if \"FED FUNDS (FED)\" in our_df:\n",
    "                    fed_df = our_df[[\"FED FUNDS (FED)\"]]\n",
    "        if fed_as_pctg == 'yes':\n",
    "             fed_df = fed_df.pct_change()*100\n",
    "        ax4 = ax1.twinx()\n",
    "        if smooth_fed == 'no':\n",
    "            sns.lineplot(data=fed_df['FED FUNDS (FED)'], ax=ax4, color='purple', label='FED FUNDS')\n",
    "        elif smooth_fed == 'yes':\n",
    "            smoothing_fed = fed_df.copy()\n",
    "            smooth_fed_values = savgol_filter(smoothing_fed[smoothing_fed.columns[0]], svgal_fed_cycle, fed_poly)\n",
    "            smoothing_fed[smoothing_fed.columns[0]] = smooth_fed_values\n",
    "            sns.lineplot(data=smoothing_fed['FED FUNDS (FED)'], ax=ax4, color='purple', label='FED FUNDS')\n",
    "        ax4.set_ylabel('FED FUNDS')\n",
    "        ax4.set_ylim(0, (fed_df['FED FUNDS (FED)'].max()+15))\n",
    "        ax4.spines['right'].set_position(('outward', 120))  # Shift the secondary y-axis outward\n",
    "        align_zero(ax1, ax4)\n",
    "\n",
    "    if plot_sp500 == 'yes':\n",
    "        for i in range(len(dict_of_df)):\n",
    "            df_name = f'df{i}'\n",
    "            if df_name in globals():\n",
    "                the_df = globals()[df_name]\n",
    "                if \"S&P 500 (Stock Index)\" in the_df.columns:\n",
    "                    sp500_df = the_df[[\"S&P 500 (Stock Index)\"]]\n",
    "        if sp_as_pctg == 'yes':\n",
    "            sp500_df = sp500_df.pct_change()*100\n",
    "            sp500_df = sp500_df.dropna()\n",
    "\n",
    "        ax5 = ax1.twinx()\n",
    "        if smooth_sp500 == 'no':\n",
    "            sns.lineplot(data=sp500_df[\"S&P 500 (Stock Index)\"], ax=ax5, color='pink', label= 'S&P 500')\n",
    "        elif smooth_sp500 == 'yes':\n",
    "            smoothing_sp500 = sp500_df.copy()\n",
    "            smoothed_sp500_values = savgol_filter(smoothing_sp500[\"S&P 500 (Stock Index)\"], indices_window, indices_order)\n",
    "            smoothing_sp500[\"S&P 500 (Stock Index)\"] = smoothed_sp500_values\n",
    "            sns.lineplot(data=smoothing_sp500[\"S&P 500 (Stock Index)\"], ax=ax5, color='pink', label=\"S&P 500\")\n",
    "            ax5.set_ylim(0,smoothing_sp500[\"S&P 500 (Stock Index)\"].max()+1)\n",
    "        ax5.set_ylabel(\"S&P 500\")\n",
    "        ax5.spines['right'].set_position((\"outward\", 180))\n",
    "        align_zero(ax1, ax5)\n",
    "    \n",
    "    if plot_msci == 'yes':\n",
    "        for i in range(len(dict_of_df)):\n",
    "            df_name = f'df{i}'\n",
    "            if df_name in globals():\n",
    "                the_df = globals()[df_name]\n",
    "                if \"MSCI world (Stock Index)\" in the_df.columns:\n",
    "                    msci_df = the_df[[\"MSCI world (Stock Index)\"]]\n",
    "        if msci_as_pctg == 'yes':\n",
    "            msci_df = msci_df.pct_change()*100\n",
    "            msci_df = msci_df.dropna()\n",
    "        ax6 = ax1.twinx()\n",
    "        if smooth_msci == 'no':\n",
    "            sns.lineplot(data=sp500_df[\"MSCI world (Stock Index)\"], ax=ax6, color='lightgreen', label= 'MSCI World')\n",
    "        elif smooth_msci == 'yes':\n",
    "            smoothing_msci = msci_df.copy()\n",
    "            smoothed_msci_values = savgol_filter(smoothing_msci[\"MSCI world (Stock Index)\"], indices_window, indices_order)\n",
    "            smoothing_msci[\"MSCI world (Stock Index)\"] = smoothed_msci_values\n",
    "            sns.lineplot(data=smoothing_msci[\"MSCI world (Stock Index)\"], ax=ax6, color='lightgreen', label=\"MSCI World\")\n",
    "            ax6.set_ylim(0,smoothing_msci[\"MSCI world (Stock Index)\"].max()+1)\n",
    "        ax6.set_ylabel(\"MSCI world\")\n",
    "        ax6.spines['right'].set_position((\"outward\", 240))\n",
    "        align_zero(ax1, ax6)\n",
    "    \n",
    "    if plot_nasdaq == 'yes':\n",
    "        for i in range(len(dict_of_df)):\n",
    "            df_name = f'df{i}'\n",
    "            if df_name in globals():\n",
    "                the_df = globals()[df_name]\n",
    "                if \"NASDAQ (Stock Index)\" in the_df.columns:\n",
    "                    nasdaq_df = the_df[[\"NASDAQ (Stock Index)\"]]\n",
    "        if nasdaq_as_pctg == 'yes':\n",
    "            nasdaq_df = nasdaq_df.pct_change()*100\n",
    "            nasdaq_df = nasdaq_df.dropna()\n",
    "        ax7 = ax1.twinx()\n",
    "        if smooth_nasdaq == 'no':\n",
    "            sns.lineplot(data=nasdaq_df[\"NASDAQ (Stock Index)\"], ax=ax7, color='grey', label= 'NASDAQ')\n",
    "            ax7.set_ylim(0,nasdaq_df[\"NASDAQ (Stock Index)\"].max()+1)\n",
    "        elif smooth_nasdaq == 'yes':\n",
    "            smoothing_nasdaq = nasdaq_df.copy()\n",
    "            smoothed_nasdaq_values = savgol_filter(smoothing_nasdaq[\"NASDAQ (Stock Index)\"], indices_window, indices_order)\n",
    "            smoothing_nasdaq[\"NASDAQ (Stock Index)\"] = smoothed_nasdaq_values\n",
    "            sns.lineplot(data=smoothing_nasdaq[\"NASDAQ (Stock Index)\"], ax=ax7, color='grey', label=\"NASDAQ\")\n",
    "            ax7.set_ylim(0,smoothing_nasdaq[\"NASDAQ (Stock Index)\"].max()+1)\n",
    "        ax7.set_ylabel(\"NASDAQ\")\n",
    "        ax7.spines['right'].set_position((\"outward\", 300))\n",
    "        align_zero(ax1, ax7)\n",
    "    \n",
    "    if plot_predictions == 'yes':\n",
    "        ax8 = ax1.twinx()\n",
    "        sns.lineplot(data=df[\"Predictions\"], ax=ax8, color='Green', label= 'Predictions')\n",
    "        if plot_ci == 'yes':\n",
    "            sns.lineplot(data=df[\"Lower Bound\"], ax=ax8, color='Black', label= 'Lower Bound')\n",
    "            sns.lineplot(data=df[\"Upper Bound\"], ax=ax8, color='Black', label= 'Upper Bound')\n",
    "        ax8.set_ylabel(\"Predictions\")\n",
    "        ax8.spines['right'].set_position((\"outward\", 360))\n",
    "        align_zero(ax1, ax8)\n",
    "\n",
    "\n",
    "    plt.xlim(start_time, end_time)\n",
    "\n",
    "    fig.legend(loc=\"lower left\", bbox_to_anchor=(1,1), bbox_transform=ax1.transAxes)    \n",
    "    plt.title('Values Over Time')\n",
    "    plt.show()\n",
    "\n",
    "#plot_combined_cycles_and_stds(df = combine_cycles_and_stds_trend(), nbins = 40, dont_plot_series='yes', indices_window=500, indices_order=5, plot_nasdaq='no', nasdaq_as_pctg='yes', smooth_nasdaq='yes', fed_as_pctg='no', plot_fed_funds='yes', smooth_fed='no', plot_economic_cycle='yes', smooth_economic_cycle='no')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Find the periods during which the std and the market tendency cut through 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Compare these periods with the performances of the big indices (S&P500, MSCI World)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Find the performance during the lag time"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Return statistics for all economic cycles"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Model 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 133,
   "metadata": {},
   "outputs": [],
   "source": [
    "def model_2_prediction(plot_perfs = 'no', save_model = 'yes', what_to_predict = 'Economic cycle', help_to_predict1 = 'Sum of standard deviation values',help_to_predict2 = 'Sum of recession/expansion values', smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W', sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes'):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth, smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly, smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly, sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci, nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window, indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "    X = df[[f'{help_to_predict1}', f'{help_to_predict2}']]\n",
    "    y = df[f'{what_to_predict}']\n",
    "\n",
    "    # Experiment with higher-degree polynomials\n",
    "    poly = PolynomialFeatures(degree=3, interaction_only=False, include_bias=False)\n",
    "    X_poly = poly.fit_transform(X)\n",
    "\n",
    "    # Feature scaling\n",
    "    scaler = StandardScaler()\n",
    "    X_poly_scaled = scaler.fit_transform(X_poly)\n",
    "\n",
    "    # Optional: Dimensionality reduction\n",
    "    pca = PCA(n_components=0.95)  # retain 95% variance\n",
    "    X_poly_scaled = pca.fit_transform(X_poly_scaled)\n",
    "\n",
    "    # Split the data\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X_poly_scaled, y, test_size=0.2, random_state=42)\n",
    "\n",
    "    # Manually tune hyperparameters\n",
    "    rf_model = RandomForestRegressor(\n",
    "        n_estimators=250,  # increased number of trees for better averaging\n",
    "        max_depth=12,      # increased depth for more complex patterns\n",
    "        min_samples_split=5,\n",
    "        min_samples_leaf=2,\n",
    "        max_features='sqrt',\n",
    "        random_state=42\n",
    "    )\n",
    "\n",
    "    # Fit the model\n",
    "    rf_model.fit(X_train, y_train)\n",
    "\n",
    "    # Predict and evaluate\n",
    "    y_pred = rf_model.predict(X_test)\n",
    "    mse = mean_squared_error(y_test, y_pred)\n",
    "    r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "    if plot_perfs =='yes':\n",
    "\n",
    "        print(f'Mean Squared Error: {mse}')\n",
    "        print(f'R-squared: {r2}')\n",
    "\n",
    "        # Plotting results\n",
    "        plt.figure(figsize=(12, 6))\n",
    "        plt.plot(y_test.values, label='Actual', marker='o')\n",
    "        plt.plot(y_pred, label='Predicted', marker='x')\n",
    "        plt.legend()\n",
    "        plt.show()\n",
    "\n",
    "    # Save the model and preprocessing objects\n",
    "    if save_model=='yes':\n",
    "        model_dir = f'model_2_for_{what_to_predict}'\n",
    "        os.makedirs(model_dir, exist_ok=True)\n",
    "        joblib.dump(rf_model, os.path.join(model_dir, f'model_2_for_{what_to_predict}.pkl'))\n",
    "        joblib.dump(poly, os.path.join(model_dir, 'poly_transformer.pkl'))\n",
    "        joblib.dump(scaler, os.path.join(model_dir, 'scaler.pkl'))\n",
    "        joblib.dump(pca, os.path.join(model_dir, 'pca_transformer.pkl'))\n",
    "\n",
    "# Train the model and save it\n",
    "#(plot_perfs='yes', what_to_predict='S&P 500 (Stock Index)', save_model=\"yes\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 134,
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_values_model_2(new_model = 'no', what_to_predict = 'Economic cycle', help_to_predict1 = 'Sum of standard deviation values',\n",
    "                           help_to_predict2 = 'Sum of recession/expansion values', plot = 'yes', return_predictions = 'yes',\n",
    "                           return_dataframe = 'no', confidence_level=0.95, smooth_filter = 'yes', svgal_window=50, polyorder=3,\n",
    "                           smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no',\n",
    "                           svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150,\n",
    "                           fed_poly = 3, sp_as_pctg = 'yes', smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes',\n",
    "                           nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', indices_window = 500, indices_order = 5, freq = 'W',\n",
    "                           sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes', save_excel = 'no', excel_name = 'predictions_model_2', cell_width = 50):\n",
    "    \n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder,\n",
    "                                            smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth,\n",
    "                                            smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly,\n",
    "                                            smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly,\n",
    "                                            sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci,\n",
    "                                            nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window,\n",
    "                                            indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "\n",
    "    model_dir = f'model_2_for_{what_to_predict}'\n",
    "\n",
    "    model_path = os.path.join(model_dir, f'model_2_for_{what_to_predict}.pkl')\n",
    "    if not os.path.exists(model_path):\n",
    "        model_2_prediction(save_model = 'yes', what_to_predict = what_to_predict, help_to_predict1 = help_to_predict1,\n",
    "                           help_to_predict2 = help_to_predict2, smooth_filter = smooth_filter, svgal_window=svgal_window,\n",
    "                           polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth,\n",
    "                           smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly,\n",
    "                           smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly,\n",
    "                           sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci,\n",
    "                           nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window,\n",
    "                           indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "    \n",
    "    if new_model == 'yes':\n",
    "        model_2_prediction(save_model = 'yes', what_to_predict = what_to_predict, help_to_predict1 = help_to_predict1,\n",
    "                           help_to_predict2 = help_to_predict2, smooth_filter = smooth_filter, svgal_window=svgal_window,\n",
    "                           polyorder=polyorder, smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth,\n",
    "                           smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly,\n",
    "                           smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly,\n",
    "                           sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci,\n",
    "                           nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window,\n",
    "                           indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "\n",
    "    best_rf_model = joblib.load(os.path.join(model_dir, f'model_2_for_{what_to_predict}.pkl'))\n",
    "    poly = joblib.load(os.path.join(model_dir, 'poly_transformer.pkl'))\n",
    "    scaler = joblib.load(os.path.join(model_dir, 'scaler.pkl'))\n",
    "    pca = joblib.load(os.path.join(model_dir, 'pca_transformer.pkl'))\n",
    "\n",
    "    # Ensure the DataFrame contains the necessary columns\n",
    "    if not {f'{help_to_predict1}', f'{help_to_predict2}'}.issubset(df.columns):\n",
    "        raise ValueError(f\"DataFrame must contain '{help_to_predict1}' and '{help_to_predict2}' columns.\")\n",
    "\n",
    "    # Transform the data using the polynomial features transformer\n",
    "    new_X_poly = poly.transform(df[[f'{help_to_predict1}', f'{help_to_predict2}']])\n",
    "\n",
    "    # Scale the polynomial features\n",
    "    new_X_scaled = scaler.transform(new_X_poly)\n",
    "\n",
    "    # Apply PCA transformation\n",
    "    new_X_pca = pca.transform(new_X_scaled)\n",
    "\n",
    "    # Make predictions with the loaded model\n",
    "    new_predictions = best_rf_model.predict(new_X_pca)\n",
    "\n",
    "    # Calculate residuals using the model\n",
    "    X = df[[help_to_predict1, help_to_predict2]]\n",
    "    y = df[what_to_predict]\n",
    "    X_poly = poly.transform(X)\n",
    "    X_scaled = scaler.transform(X_poly)\n",
    "    X_pca = pca.transform(X_scaled)\n",
    "    y_pred = best_rf_model.predict(X_pca)\n",
    "    residuals = y - y_pred\n",
    "\n",
    "    # Compute confidence intervals\n",
    "    lower_bound, upper_bound = compute_confidence_interval(new_predictions, residuals, confidence_level=confidence_level)\n",
    "\n",
    "    df_with_predictions = df.copy()\n",
    "    df_with_predictions['Predictions'] = new_predictions\n",
    "    df_with_predictions['Lower Bound'] = lower_bound\n",
    "    df_with_predictions['Upper Bound'] = upper_bound\n",
    "\n",
    "    if plot == 'yes':\n",
    "        sns.lineplot(x=df_with_predictions.index, y=f'{help_to_predict1}', data=df_with_predictions, label=f'{help_to_predict1}')\n",
    "        sns.lineplot(x=df_with_predictions.index, y=f'{help_to_predict2}', data=df_with_predictions, label=f'{help_to_predict2}')\n",
    "        sns.lineplot(x=df_with_predictions.index, y='Predictions', data=df_with_predictions, label=f'Predictions for {what_to_predict}')\n",
    "        sns.lineplot(x=df_with_predictions.index, y=f'{what_to_predict}', data=df_with_predictions, label=f'Actual value for {what_to_predict}')\n",
    "        sns.lineplot(x=df_with_predictions.index, y='Lower Bound', data=df_with_predictions, label='Lower Bound', linestyle='--')\n",
    "        sns.lineplot(x=df_with_predictions.index, y='Upper Bound', data=df_with_predictions, label='Upper Bound', linestyle='--')\n",
    "        plt.xlabel('Index')\n",
    "        plt.ylabel('Values')\n",
    "        plt.legend()\n",
    "        plt.title('Predictions, Actual Values, and Confidence Intervals')\n",
    "        plt.show()\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        # Save to Excel\n",
    "        df_with_predictions.to_excel(f\"{excel_name}.xlsx\", index=False)\n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")\n",
    "        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    if return_predictions == 'yes':\n",
    "        return new_predictions, lower_bound, upper_bound\n",
    "    elif return_dataframe == 'yes':\n",
    "        return df_with_predictions\n",
    "\n",
    "# Example usage\n",
    "#predict_values_model_2(plot='no', return_predictions='no', return_dataframe='yes', what_to_predict=\"Economic cycle\")"
   ]
  },
  
  {
   "cell_type": "code",
   "execution_count": 136,
   "metadata": {},
   "outputs": [],
   "source": [
    "def box_plot_in_alternations_sheet(excel_name, minmax='no', file_format='jpeg', wrap_length=15, save_plots='yes', folder_name_save='box_plots'):\n",
    "    file_path = f'{excel_name}.xlsx'\n",
    "    sheet_name = 'Alternations'\n",
    "    df = pd.read_excel(file_path, sheet_name=sheet_name)\n",
    "    \n",
    "    # Define the indices and time periods\n",
    "    indices = ['S&P 500', 'MSCI', 'NASDAQ']\n",
    "    time_periods = [\"6 months\", \"12 months\", \"18 months\"]\n",
    "    \n",
    "    # Extract and sort change_types based on the change from start to end\n",
    "    df[['start', 'end']] = df['change_type'].str.split(' to ', expand=True)\n",
    "\n",
    "    # Convert to float, handling conversion errors if any\n",
    "    df['start'] = df['start'].astype(float, errors='raise')\n",
    "    df['end'] = df['end'].astype(float, errors='raise')\n",
    "\n",
    "    # Calculate the change\n",
    "    df['change'] = df['end'] - df['start']\n",
    "\n",
    "    # Sort by change (smallest to largest)\n",
    "    sorted_change_types = df.sort_values(by=['change'], ascending=True)['change_type'].unique()\n",
    "\n",
    "    # Filter columns based on index and time period\n",
    "    def filter_columns(index):\n",
    "        if minmax == 'yes':\n",
    "            return {period: [col for col in df.columns if '%' in col and 'after' in col and index in col and period in col] for period in time_periods}\n",
    "        elif minmax == 'no':\n",
    "            return {period: [col for col in df.columns if '%' in col and 'after' in col and index in col and period in col and 'Max' not in col and 'Min' not in col] for period in time_periods}\n",
    "\n",
    "    # Directory to save the plots\n",
    "    plot_dir = f'{folder_name_save}'\n",
    "    if save_plots == \"yes\":    \n",
    "        if not os.path.exists(plot_dir):\n",
    "            os.makedirs(plot_dir)\n",
    "\n",
    "    # Group by 'change_type'\n",
    "    grouped = df.groupby('change_type')\n",
    "\n",
    "    plot_filenames = []\n",
    "\n",
    "    # Plot data for each index\n",
    "    for index in indices:\n",
    "        period_columns = filter_columns(index)\n",
    "\n",
    "        for period, columns in period_columns.items():\n",
    "            plt.figure(figsize=(12, 8))\n",
    "            labels = []\n",
    "            data_to_plot = []\n",
    "            box_colors = []\n",
    "            means = []\n",
    "\n",
    "            for change_type in sorted_change_types:\n",
    "                if change_type in grouped.groups:\n",
    "                    group = grouped.get_group(change_type)\n",
    "                    # Collect the data for the current change_type and period\n",
    "                    data_to_plot.append(group[columns].values.flatten())  # Flatten to make it 1D\n",
    "                    labels.append(change_type)  # Add change_type as the label\n",
    "\n",
    "                    # Calculate the mean of the data\n",
    "                    mean_value = group[columns].values.flatten().mean()\n",
    "                    means.append(mean_value)\n",
    "\n",
    "                    # Determine color based on whether the change is positive or negative\n",
    "                    change = group['end'].iloc[0] - group['start'].iloc[0]  # Calculate the change for color coding\n",
    "                    color = 'orange' if change < 0 else 'blue'\n",
    "                    box_colors.append(color)\n",
    "\n",
    "            # Plot the data with change_type as the x-axis label\n",
    "            sns.boxplot(data=data_to_plot, palette=box_colors)\n",
    "            \n",
    "            # Set x-axis labels to change types\n",
    "            plt.xticks(ticks=range(len(labels)), labels=labels, rotation=0)\n",
    "\n",
    "            # Add means as yellow lines with annotations\n",
    "            ax = plt.gca()\n",
    "            for i, mean_value in enumerate(means):\n",
    "                ax.axhline(y=mean_value, color='yellow', linestyle='-', linewidth=2, xmin=i/(len(labels)), xmax=(i+1)/(len(labels)))\n",
    "                ax.text(i, mean_value, f'{mean_value:.2f}', color='yellow', ha='center', va='bottom')\n",
    "\n",
    "            # Calculate min and max values for setting y-axis limits\n",
    "            min_y = df[columns].min().min()\n",
    "            max_y = df[columns].max().max()\n",
    "\n",
    "            # Ensure the zero axis is in the middle and set y-axis limits\n",
    "            center_y = max(abs(min_y), abs(max_y))  # This ensures zero is in the middle\n",
    "            plt.ylim(-center_y, center_y)\n",
    "\n",
    "            # Add a dotted red line at zero\n",
    "            ax.axhline(0, color='red', linestyle='--', linewidth=1)  # Dotted red line at zero\n",
    "\n",
    "            ax.yaxis.set_major_locator(MaxNLocator(integer=True))  # Use integer ticks\n",
    "\n",
    "            plt.title(f'{index} over {period}')\n",
    "            plt.tight_layout()\n",
    "\n",
    "            if save_plots == \"yes\":\n",
    "                # Save each plot with the correct file format\n",
    "                plot_filename = f\"{plot_dir}/box_plot_{index}_{period}.{file_format}\"\n",
    "                plt.savefig(plot_filename, format=file_format)\n",
    "                plot_filenames.append(plot_filename)\n",
    "            plt.close()\n",
    "\n",
    "    return f\"Box plots saved in '{plot_dir}' directory.\" if save_plots == \"yes\" else plot_filenames\n",
    "\n",
    "#box_plot_in_alternations_sheet(\"Test fréquence code couleur microcycles\", save_plots = \"yes\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 137,
   "metadata": {},
   "outputs": [],
   "source": [
    "#alternations_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "metadata": {},
   "outputs": [],
   "source": [
    "def indexes_perfs(smooth_filter = 'yes', svgal_window=50, polyorder=3,\n",
    "                  smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no',\n",
    "                  svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'no', fed_as_pctg = 'no', svgal_fed_cycle = 150,\n",
    "                  fed_poly = 3, sp_as_pctg = 'no', smooth_sp500 = 'no', msci_as_pctg = 'no', smooth_msci = 'no',\n",
    "                  nasdaq_as_pctg = 'no', smooth_nasdaq = 'no', indices_window = 500, indices_order = 5, freq = 'W',\n",
    "                  sp_sub_ind_as_pctg = 'no', smooth_sp_sub_ind = 'no', save_excel = 'no', excel_name = 'indexes perfs', cell_width = 50):\n",
    "    df = put_all_in_dataframe_for_eco_cycle(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder,\n",
    "                                            smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth,\n",
    "                                            smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly,\n",
    "                                            smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly,\n",
    "                                            sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci,\n",
    "                                            nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window,\n",
    "                                            indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "    filtered_df = df.filter(like='(Stock Index)', axis=1)\n",
    "    percentage_changes = []\n",
    "\n",
    "    # Initialize variables to keep track of the start of a new period\n",
    "    start_idx = 0\n",
    "\n",
    "    # Iterate over the DataFrame to identify periods using 'Economic cycle'\n",
    "    for i in range(1, len(df)):\n",
    "        if df['Economic cycle'].iloc[i] != df['Economic cycle'].iloc[i-1]:\n",
    "            # We've encountered the end of a period\n",
    "            \n",
    "            # Extract the current period\n",
    "            period_df = filtered_df.iloc[start_idx:i]\n",
    "            \n",
    "            # Calculate percentage change for each column in the period\n",
    "            period_pct_change = ((period_df.iloc[-1] - period_df.iloc[0]) / period_df.iloc[0]) * 100\n",
    "            \n",
    "            # Add the period index (based on the first index in the period) for reference\n",
    "            period_pct_change.name = df['Economic cycle'].iloc[start_idx]\n",
    "            \n",
    "            # Add dates_change information\n",
    "            start_date = df.index[start_idx].strftime('%Y-%m-%d')\n",
    "            end_date = df.index[i-1].strftime('%Y-%m-%d')\n",
    "            period_pct_change['Period'] = f\"From {start_date} to {end_date}\"            \n",
    "            # Append the result to the list\n",
    "            percentage_changes.append(period_pct_change)\n",
    "            \n",
    "            # Update the start of the next period\n",
    "            start_idx = i\n",
    "\n",
    "    # Handle the last period\n",
    "    period_df = filtered_df.iloc[start_idx:]\n",
    "    period_pct_change = ((period_df.iloc[-1] - period_df.iloc[0]) / period_df.iloc[0]) * 100\n",
    "    period_pct_change.name = df['Economic cycle'].iloc[start_idx]\n",
    "    start_date = df.index[start_idx].strftime('%Y-%m-%d')\n",
    "    end_date = df.index[-1].strftime('%Y-%m-%d')\n",
    "    period_pct_change['Period'] = f\"From {start_date} to {end_date}\"\n",
    "    percentage_changes.append(period_pct_change)\n",
    "\n",
    "    # Create a new DataFrame from the percentage change data\n",
    "    percentage_changes_df = pd.DataFrame(percentage_changes)\n",
    "\n",
    "    # Save to Excel\n",
    "    if save_excel == 'yes':\n",
    "        with pd.ExcelWriter(f\"{excel_name}.xlsx\", engine='openpyxl') as writer:\n",
    "                    percentage_changes_df.to_excel(writer, sheet_name='Percentage changes', index=False)        \n",
    "        \n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return percentage_changes_df\n",
    "\n",
    "#indexes_perfs(save_excel=\"yes\", excel_name=\"indexes_perfs\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "metadata": {},
   "outputs": [],
   "source": [
    "def simulation_of_investments_perf(smooth_filter = 'yes', svgal_window=50, polyorder=3,\n",
    "                  smooth_both_columns = 'no', index_which_column_to_smooth = 1, smooth_economic_cycle = 'no',\n",
    "                  svgal_eco_cycle = 75, eco_poly = 6, smooth_fed = 'no', fed_as_pctg = 'no', svgal_fed_cycle = 150,\n",
    "                  fed_poly = 3, sp_as_pctg = 'no', smooth_sp500 = 'no', msci_as_pctg = 'no', smooth_msci = 'no',\n",
    "                  nasdaq_as_pctg = 'no', smooth_nasdaq = 'no', indices_window = 500, indices_order = 5, freq = 'W',\n",
    "                  sp_sub_ind_as_pctg = 'no', smooth_sp_sub_ind = 'no', save_excel = 'no', excel_name = 'Investment simulation', cell_width = 50,\n",
    "                  expansion_invest = 1, moderate_invest = 0.7, slow_invest = 0.3, recession_invest = 0):\n",
    "    df = indexes_perfs(smooth_filter = smooth_filter, svgal_window=svgal_window, polyorder=polyorder,\n",
    "                                            smooth_both_columns = smooth_both_columns, index_which_column_to_smooth = index_which_column_to_smooth,\n",
    "                                            smooth_economic_cycle = smooth_economic_cycle, svgal_eco_cycle = svgal_eco_cycle, eco_poly = eco_poly,\n",
    "                                            smooth_fed = smooth_fed, fed_as_pctg = fed_as_pctg, svgal_fed_cycle = svgal_fed_cycle, fed_poly = fed_poly,\n",
    "                                            sp_as_pctg = sp_as_pctg, smooth_sp500 = smooth_sp500, msci_as_pctg = msci_as_pctg, smooth_msci = smooth_msci,\n",
    "                                            nasdaq_as_pctg = nasdaq_as_pctg, smooth_nasdaq = smooth_nasdaq, indices_window = indices_window,\n",
    "                                            indices_order = indices_order, freq = freq, sp_sub_ind_as_pctg = sp_sub_ind_as_pctg, smooth_sp_sub_ind = smooth_sp_sub_ind)\n",
    "\n",
    "    original_df = df.copy()\n",
    "\n",
    "    coefficients = {-2: recession_invest, -1: slow_invest, 1: moderate_invest, 2: expansion_invest}\n",
    "\n",
    "    # Get the list of columns that contain \"(Stock Index)\"\n",
    "    sti_columns = [col for col in df.columns if \"(Stock Index)\" in col]\n",
    "\n",
    "    # Iterate over each column of interest\n",
    "    for col in sti_columns:\n",
    "        base_value = 1  # Initialize the base value for the first row\n",
    "        prev_result = None  # To store the result of the previous row\n",
    "\n",
    "        # Iterate over the DataFrame by row number and actual index\n",
    "        for i in range(len(df)):\n",
    "            index_value = df.index[i]  # Get the index value for the current row\n",
    "            coefficient = coefficients.get(index_value)\n",
    "            \n",
    "            if coefficient is None:\n",
    "                # Handle the case where there is no coefficient for the index value\n",
    "                raise ValueError(f\"No coefficient found for index value {index_value}\")\n",
    "\n",
    "            df.loc[df[col] < -100, col] = -100\n",
    "\n",
    "            if i == 0:\n",
    "                # For the first row, use base_value\n",
    "                result = ((base_value * coefficient * df.iloc[i][col]))/100 + base_value\n",
    "            else:\n",
    "                # For other rows, use the result from the previous row\n",
    "                result = ((prev_result * coefficient * df.iloc[i][col]))/100 + prev_result\n",
    "            \n",
    "            # Update the DataFrame with the calculated result\n",
    "            df.iloc[i, df.columns.get_loc(col)] = round(result,2)\n",
    "            \n",
    "            # Store the result for use in the next iteration\n",
    "            prev_result = result\n",
    "\n",
    "\n",
    "    if save_excel == 'yes':\n",
    "        with pd.ExcelWriter(f\"{excel_name}.xlsx\", engine='openpyxl') as writer:\n",
    "                    df.to_excel(writer, sheet_name='Investment Simulation', index=True) \n",
    "                    original_df.to_excel(writer, sheet_name='Original Data', index=True)       \n",
    "        \n",
    "        wb = load_workbook(f\"{excel_name}.xlsx\")        \n",
    "        # Adjust dimensions automatically\n",
    "        adjust_dimensions(wb, max_column_width=cell_width)\n",
    "        \n",
    "        # Save the workbook with the adjusted dimensions\n",
    "        wb.save(f\"{excel_name}.xlsx\")\n",
    "\n",
    "    return df\n",
    "\n",
    "#simulation_of_investments_perf(save_excel='yes')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Performances graphs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 140,
   "metadata": {},
   "outputs": [],
   "source": [
    "#plot_combined_cycles_and_stds(df = predict_values_model_1(new_model='no', what_to_predict = 'Economic cycle', help_to_predict1 = 'Sum of standard deviation values',\n",
    "#                                                          help_to_predict2 = 'Sum of recession/expansion values', plot = 'no', return_predictions = 'no',\n",
    "#                                                          return_dataframe = 'yes', smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no',\n",
    "#                                                          index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6,\n",
    "#                                                          smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes',\n",
    "#                                                          smooth_sp500 = 'no', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes',\n",
    "#                                                          indices_window = 500, indices_order = 5, freq = 'W', sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes'),\n",
    "#                              dont_plot_series='yes', plot_both_series='yes', normalize_series='no', smooth_filter='no',\n",
    "#                              plot_economic_cycle='yes', plot_predictions='yes',\n",
    "#                              plot_sp500='yes', sp_as_pctg='no', smooth_sp500='no',\n",
    "#                              plot_msci='no', msci_as_pctg='yes', smooth_msci='yes',\n",
    "#                              plot_nasdaq='no', smooth_nasdaq='yes', nasdaq_as_pctg='yes',\n",
    "#                              nbins = 35, plot_ci= \"no\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 141,
   "metadata": {},
   "outputs": [],
   "source": [
    "#plot_combined_cycles_and_stds(df = predict_values_model_2(new_model='yes', what_to_predict = 'Economic cycle', help_to_predict1 = 'Sum of standard deviation values',\n",
    "#                                                          help_to_predict2 = 'Sum of recession/expansion values', plot = 'no', return_predictions = 'no', \n",
    "#                                                          return_dataframe = 'yes', smooth_filter = 'yes', svgal_window=50, polyorder=3, smooth_both_columns = 'no', \n",
    "#                                                          index_which_column_to_smooth = 1, smooth_economic_cycle = 'no', svgal_eco_cycle = 75, eco_poly = 6, \n",
    "#                                                          smooth_fed = 'yes', fed_as_pctg = 'yes', svgal_fed_cycle = 150, fed_poly = 3, sp_as_pctg = 'yes', \n",
    "#                                                          smooth_sp500 = 'yes', msci_as_pctg = 'yes', smooth_msci = 'yes', nasdaq_as_pctg = 'yes', smooth_nasdaq = 'yes', \n",
    "#                                                          indices_window = 500, indices_order = 5, freq = 'W', sp_sub_ind_as_pctg = 'yes', smooth_sp_sub_ind = 'yes',\n",
    "#                                                          confidence_level=0.8),\n",
    "#                              dont_plot_series='yes', plot_both_series='yes', normalize_series='yes', smooth_filter='no',\n",
    "#                              plot_economic_cycle='no', plot_predictions='yes',\n",
    "#                              plot_sp500='no', sp_as_pctg='yes', smooth_sp500='yes',\n",
    "#                              plot_msci='no', msci_as_pctg='yes', smooth_msci='yes',\n",
    "#                              plot_nasdaq='no', smooth_nasdaq='yes', nasdaq_as_pctg='yes',\n",
    "#                              plot_ci='no', nbins=35)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## To be hidden for now"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 142,
   "metadata": {},
   "outputs": [],
   "source": [
    "l1 = [\n",
    "    \"Chicago Fed National Activity (Business Conditions)\",\n",
    "    \"Conference Board US Leading In (Business Conditions)\",\n",
    "    \"ISM Manufacturing PMI SA (Business Conditions)\",\n",
    "    \"ISM Services PMI (Business Conditions)\",\n",
    "    \"Market News International Chic (Business Conditions)\",\n",
    "    \"Philadelphia Fed Business Outl (Business Conditions)\",\n",
    "    \"Richmond Manufacturing Survey (Business Conditions)\",\n",
    "    \"US Composite PMI SA (Business Conditions)\",\n",
    "    \"US Empire State Manufacturing (Business Conditions)\",\n",
    "    \"US Manufacturing PMI SA (Business Conditions)\",\n",
    "    \"US Services PMI Business Activ (Business Conditions)\",\n",
    "    \"Conference Board Consumer Conf (Customer Trust)\",\n",
    "    \"University of Michigan Consume (Customer Trust)\",\n",
    "    \"Adjusted Retail Sales Less Aut MoM (Details selling)\",\n",
    "    \"Adjusted Retail Sales Less Aut YoY (Details selling)\",\n",
    "    \"US Auto Sales Total Annualized (Details selling)\",\n",
    "    \"US Capacity Utilization % of T (Economic Dynamic)\",\n",
    "    \"US Durable Goods New Orders To (Economic Dynamic)\",\n",
    "    \"US Industrial Production YOY S (Economic Dynamic)\",\n",
    "    \"ADP National Employment Report (Employment)\",\n",
    "    \"Conference Board US Leading In (Employment)\",\n",
    "    \"U-3 US Unemployment Rate Total (Employment)\",\n",
    "    \"US Employees on Nonfarm Payrol (Employment)\",\n",
    "    \"GDP US Chained Dollars QoQ SAA (GDP)\",\n",
    "    \"GDP US Chained Dollars YoY SA (GDP)\",\n",
    "    \"US GDP Nominal Dollars YoY SA (GDP)\",\n",
    "    \"US GDP Price Index QoQ SAAR (GDP)\",\n",
    "    \"US Personal Consumption Expend % (Household)\",\n",
    "    \"US Personal Consumption Expend (Household)\",\n",
    "    \"US Personal Income YoY SA (Household)\",\n",
    "    \"Private Housing Authorized by (Housing)\",\n",
    "    \"US NAR Total Existing Homes Sa (Housing)\",\n",
    "    \"US Avg Hourly Earnings Private (Inflation)\",\n",
    "    \"US CPI Urban Consumers Less Fo (Inflation)\",\n",
    "    \"US PPI Finished Goods Less Foo (Inflation)\",\n",
    "    \"US Personal Consumption Expend (Inflation)\",\n",
    "    \"Generic 1st 'CL' Future (Materials)\",\n",
    "    \"Gold Spot   $/Oz (Materials)\",\n",
    "    \"Iron Ore Spot Price Index 62% (Materials)\",\n",
    "    \"LME COPPER    3MO ($) (Materials)\"\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 143,
   "metadata": {},
   "outputs": [],
   "source": [
    "#for y in l1:\n",
    "#    if y not in pivot_values_dict:\n",
    "#        print(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 144,
   "metadata": {},
   "outputs": [],
   "source": [
    "def retain_highest_relevance______________(std_limit, variable_to_apply_regression_on, coef_need = None, std_error = None, t_value = None, p_value = None):\n",
    "    list_needed = []\n",
    "    df = lin_regression_stats_model(std_limit = std_limit, variable_to_apply_regression_on=variable_to_apply_regression_on)\n",
    "    for i in range(1, len(df.tables[1])):\n",
    "        if coef_need is not None and abs(float(df.tables[1][i][1].data)) >= coef_need:\n",
    "            list_needed.append(df.tables[1][i][0].data)\n",
    "        if std_error is not None and abs(float(df.tables[1][i][2].data)) >= std_error:\n",
    "            list_needed.append(df.tables[1][i][0].data)\n",
    "        if t_value is not None and abs(float(df.tables[1][i][3].data)) >= t_value:\n",
    "            list_needed.append(df.tables[1][i][0].data)\n",
    "        if p_value is not None and abs(float(df.tables[1][i][4].data)) >= p_value:\n",
    "            list_needed.append(df.tables[1][i][0].data)\n",
    "    list_needed = list(set(list_needed))        \n",
    "\n",
    "    return list_needed\n",
    "\n",
    "#len(retain_highest_relevance(2, 'Adjusted Retail Sales Less Aut MoM (Details selling)', coef_need=0.2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 145,
   "metadata": {},
   "outputs": [],
   "source": [
    "def lin_regression_sklearn______________(std_limit, variable_to_apply_regression_on):\n",
    "    original_df = find_dates_above_below_stds(std_limit=std_limit)\n",
    "    linear_regression_df = filter_the_original_df(original_df)\n",
    "    Y = linear_regression_df[variable_to_apply_regression_on] \n",
    "    variables_list = []\n",
    "    for i in range(len(linear_regression_df.columns)):\n",
    "        if variable_to_apply_regression_on == linear_regression_df.columns[i]:\n",
    "            continue\n",
    "        else:\n",
    "            variables_list.append(linear_regression_df.columns[i])\n",
    "    X = linear_regression_df[variables_list]  \n",
    "    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)\n",
    "    model = LinearRegression()\n",
    "    model.fit(X_train, Y_train)\n",
    "    Y_pred = model.predict(X_test)\n",
    "    mse = mean_squared_error(Y_test, Y_pred)\n",
    "    r2 = r2_score(Y_test, Y_pred)\n",
    "    print(f\"Mean Squared Error: {mse}\")\n",
    "    print(f\"R^2 Score: {r2}\")\n",
    "    print(\"Coefficients:\", model.coef_)\n",
    "    print(\"Intercept:\", model.intercept_)\n",
    "\n",
    "#lin_regression_sklearn(2, variable_to_apply_regression_on='Adjusted Retail Sales Less Aut MoM (Details selling)')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Find the dataframes which match our needs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [],
   "source": [
    "list_of_needed_dataframes = ['(GDP)', '(Employment)', '(Inflation)', '(Economic Dynamic)', '(Business Conditions)', '(Housing)', '(Details selling)', '(Household)', '(Customer Trust)']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 147,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_dataframes_with_specific_name______________(name):\n",
    "    return {df_name:df for df_name, df in dict_of_df.items() if any(name in col for col in df.columns)}\n",
    "\n",
    "#return_dataframes_with_specific_name(name='GDP')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 148,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_columns_with_specific_names______________(name, df):\n",
    "    return [col for col in df.columns if name in col]\n",
    "\n",
    "#return_columns_with_specific_names('GDP', df1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Create new subdataframe for each of our needs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 149,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_sub_dataframe_further_analysis______________():\n",
    "    global GDP_df, Employment_df, Inflation_df, Economic_Dynamic_df, Business_Conditions_df, Housing_df, Details_Selling_df, Household_df, Customer_Trust_df\n",
    "\n",
    "    list_of_needed_dataframes = ['(GDP)', '(Employment)', '(Inflation)', '(Economic Dynamic)', '(Business Conditions)', '(Housing)', '(Details selling)', '(Household)', '(Customer Trust)']\n",
    "    \n",
    "    GDP_data = {}\n",
    "    Employment_data = {}\n",
    "    Inflation_data = {}\n",
    "    Economic_Dynamic_data = {}\n",
    "    Business_Conditions_data = {}\n",
    "    Housing_data = {}\n",
    "    Details_Selling_data = {}\n",
    "    Household_data = {}\n",
    "    Customer_Trust_data = {}\n",
    "\n",
    "    # Iterate through the global variables\n",
    "    for i in range(1, count_dfs(df) + 2):\n",
    "        df_name = f'df{i}'\n",
    "        if df_name in globals():\n",
    "            df = globals()[df_name]\n",
    "            date_col = df.index.name if df.index.name else f'{df_name}_date'\n",
    "            df = df.reset_index().rename(columns={'index': date_col})\n",
    "            for cols in df.columns:\n",
    "                if cols == date_col:\n",
    "                    continue\n",
    "                for name in list_of_needed_dataframes:\n",
    "                    if name in cols:\n",
    "                        if name == '(GDP)':\n",
    "                            GDP_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            GDP_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Employment)':\n",
    "                            Employment_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Employment_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Inflation)':\n",
    "                            Inflation_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Inflation_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Economic Dynamic)':\n",
    "                            Economic_Dynamic_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Economic_Dynamic_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Business Conditions)':\n",
    "                            Business_Conditions_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Business_Conditions_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Housing)':\n",
    "                            Housing_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Housing_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Details selling)':\n",
    "                            Details_Selling_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Details_Selling_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Household)':\n",
    "                            Household_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Household_data[f'{cols}'] = df[cols]\n",
    "                        elif name == '(Customer Trust)':\n",
    "                            Customer_Trust_data[f'Dates for {df_name}: {cols}'] = df[date_col]\n",
    "                            Customer_Trust_data[f'{cols}'] = df[cols]\n",
    "\n",
    "    # Convert dictionaries to dataframes\n",
    "    GDP_df = pd.DataFrame(GDP_data)\n",
    "    Employment_df = pd.DataFrame(Employment_data)\n",
    "    Inflation_df = pd.DataFrame(Inflation_data)\n",
    "    Economic_Dynamic_df = pd.DataFrame(Economic_Dynamic_data)\n",
    "    Business_Conditions_df = pd.DataFrame(Business_Conditions_data)\n",
    "    Housing_df = pd.DataFrame(Housing_data)\n",
    "    Details_Selling_df = pd.DataFrame(Details_Selling_data)\n",
    "    Household_df = pd.DataFrame(Household_data)\n",
    "    Customer_Trust_df = pd.DataFrame(Customer_Trust_data)\n",
    "\n",
    "#create_sub_dataframe_further_analysis()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 150,
   "metadata": {},
   "outputs": [],
   "source": [
    "#list_of_new_dfs = ['GDP_df', 'Employment_df', 'Inflation_df', 'Economic_Dynamic_df', 'Business_Conditions_df', 'Housing_df', 'Details_Selling_df', 'Household_df', 'Customer_Trust_df']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### GDP Analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We remember that:\n",
    "\n",
    "* GDP > 0 : Expansion \n",
    "\n",
    "* GDP < 0 : recession\n",
    "\n",
    "* Pivot : 0\n",
    "\n",
    "* Dynamique --> 3-4 derniers trimestres, est ce haussier ou baissier ?\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Find periods of expansion and recession"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Function to find these periods"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 151,
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_expansion_recession______________(df, name='GDP', threshold=0):\n",
    "    all_periods = []\n",
    "\n",
    "    columns_names = [col for col in df.columns if name in col and pd.api.types.is_numeric_dtype(df[col])]\n",
    "    for col in columns_names:\n",
    "        periods = []\n",
    "        above_threshold = df.iloc[0][col] > threshold\n",
    "        current_period = [df.index[0], None, above_threshold]\n",
    "\n",
    "        for index, value in df[col].items():\n",
    "            if value > threshold and not above_threshold:\n",
    "                current_period[1] = index\n",
    "                periods.append(current_period + [col])\n",
    "                current_period = [index, None, True]\n",
    "                above_threshold = True\n",
    "            elif value < threshold and above_threshold:\n",
    "                current_period[1] = index\n",
    "                periods.append(current_period + [col])\n",
    "                current_period = [index, None, False]\n",
    "                above_threshold = False\n",
    "\n",
    "        if current_period[1] is None:\n",
    "            current_period[1] = df.index[-1]\n",
    "            periods.append(current_period + [col])\n",
    "\n",
    "        for period in periods:\n",
    "            start_index, end_index, above_threshold, col_name = period\n",
    "            period_data = df.loc[start_index:end_index]\n",
    "            extreme_value = period_data[col_name].max() if above_threshold else period_data[col_name].min()\n",
    "            period.extend([period_data, extreme_value])\n",
    "\n",
    "        all_periods.append(periods)\n",
    "\n",
    "    return all_periods\n",
    "\n",
    "#x = find_expansion_recession(GDP_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Graph them"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 152,
   "metadata": {},
   "outputs": [],
   "source": [
    "def graph_expansion_recession_past_dynamic______________(weeks, name, threshold=0):\n",
    "    df_dict = return_dataframes_with_specific_name(name=name)\n",
    "\n",
    "    for df_name, df in df_dict.items():\n",
    "        columns_names = return_columns_with_specific_names(name=name, df=df)\n",
    "        periods = find_expansion_recession(df, name=name, threshold=threshold)\n",
    "        \n",
    "        for column in columns_names:\n",
    "            a = 0\n",
    "            b = 0\n",
    "            plt.figure(figsize=(24, 12))\n",
    "            plt.plot(df.index, df[column], label=f'{df_name} - {column}')  # Plotting with DataFrame and column\n",
    "            \n",
    "            # Shade the periods above or below the threshold\n",
    "            for period_group in periods:\n",
    "                for period in period_group:\n",
    "                    if period[3] == column:\n",
    "                        start_index, end_index, above_threshold, col_name, period_data, extreme_value = period\n",
    "                        if above_threshold:\n",
    "                            a += 1\n",
    "                            plt.fill_between(df.loc[start_index:end_index].index, threshold, df.loc[start_index:end_index][column], color='green', alpha=0.3)\n",
    "                        else:\n",
    "                            b += 1\n",
    "                            plt.fill_between(df.loc[start_index:end_index].index, df.loc[start_index:end_index][column], threshold, color='red', alpha=0.3)\n",
    "\n",
    "            # Adding horizontal line at the threshold\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=2, label='Threshold')\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=0, label=f'{a} periods of expansion')\n",
    "            plt.axhline(y=threshold, color='blue', linestyle='-', linewidth=0, label=f'{b} periods of recession')\n",
    "\n",
    "            # Adding vertical line 'weeks' before the most recent date\n",
    "            if len(df.index) > 0:\n",
    "                most_recent_date = df.index[-1]\n",
    "                weeks_before = most_recent_date - pd.DateOffset(weeks=weeks)\n",
    "                plt.axvline(x=weeks_before, color='r', linestyle='--', linewidth=2, label=f'Last {weeks} weeks')\n",
    "\n",
    "            plt.xlabel('Time')\n",
    "            plt.ylabel('Value')\n",
    "            plt.title(f'{column} Over Time')\n",
    "            plt.legend()\n",
    "            plt.show()\n",
    "\n",
    "# Example usage:\n",
    "#graph_expansion_recession_past_dynamic(17*3, 'GDP', threshold=0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Find the dynamic of the last 3-4 trimesters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 153,
   "metadata": {},
   "outputs": [],
   "source": [
    "def past_trimesters_dynamic______________(weeks, name):\n",
    "    df_dict = return_dataframes_with_specific_name(name=name)\n",
    "    name_and_characteristics = []\n",
    "    \n",
    "    for df_name, df in df_dict.items():\n",
    "        columns_names = return_columns_with_specific_names(name=name, df=df)\n",
    "        \n",
    "        for column in columns_names:\n",
    "            # Extract the relevant rows based on the index condition\n",
    "            df_filtered = df[df.index >= df.index[-1] - pd.DateOffset(weeks=weeks)]\n",
    "            \n",
    "            if df_filtered.empty:\n",
    "                continue\n",
    "            \n",
    "            values = df_filtered[column]\n",
    "            \n",
    "            # Calculate required statistics\n",
    "            max_value = values.max()\n",
    "            min_value = values.min()\n",
    "            average_value = values.mean()\n",
    "            median_value = values.median()\n",
    "            slope, intercept, r_value, p_value, std_err = linregress(df_filtered.index.map(pd.Timestamp.toordinal), values)\n",
    "            dispersion = values.std()\n",
    "            \n",
    "            characteristics = {\n",
    "                'Dataframe': df_name,\n",
    "                'Column': column,\n",
    "                'Max': float(max_value),\n",
    "                'Min': float(min_value),\n",
    "                'Average': float(average_value),\n",
    "                'Median': float(median_value),\n",
    "                'Slope': float(slope),\n",
    "                'Standard deviation': float(dispersion)\n",
    "            }\n",
    "            \n",
    "            name_and_characteristics.append(characteristics)\n",
    "    \n",
    "    return name_and_characteristics\n",
    "\n",
    "#past_trimesters_dynamic(3*17, 'GDP')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### We are currently in a period of slow economic growth, where growth is slowing down. However, we are yet to turn in a period of recession"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Employment Analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We remember that:\n",
    "\n",
    "* There is no pivot point for unemployment\n",
    "    * We define the mins and maxs according to the recession and high expansion periods (flotting GDP pivot)\n",
    "* Find the dynamic of the trimesters after the pivot point\n",
    "    * What is the lapse of time such that the pivot of unemployment changes ?\n",
    "    * What is the historical average to change this tendency ?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Finding the relation between unemployment and GDP"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "metadata": {},
   "outputs": [],
   "source": [
    "def normalize_y_axis_threshold______________(svgal_window=75, polyorder=3, number=1, window=104, threshold_small=0.5, threshold_big=0.7, decimal=3):\n",
    "    l = list_of_global_all_corr_parametrized(number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    smoothed_df = smooth_dataframe(svgal_window=svgal_window, polyorder=polyorder, number=number, window=window, threshold_small=threshold_small, threshold_big=threshold_big, decimal=decimal)\n",
    "    results = []\n",
    "    for i in range(len(dict_of_df)):\n",
    "        for j in range(len(dict_of_df)):\n",
    "            dfx_name = f'df{i+1}'\n",
    "            dfy_name = f'df{j+1}'\n",
    "            if dfx_name in globals() and dfy_name in globals():\n",
    "                dfx, dfy = smoothed_df[i], smoothed_df[j]\n",
    "                for x in range(len(l)):\n",
    "                    for y in range(len(dfx.columns)):\n",
    "                        for z in range(len(dfy.columns)):\n",
    "                            if (l[x][0] == dfx.columns[y]) and (l[x][1] == dfy.columns[z]):\n",
    "                                normalized_df = normalize_columns(dfy, dfx, dfx.columns[y], dfy.columns[z])\n",
    "                                results.append(([dfx.columns[y], dfy.columns[z]], normalized_df))\n",
    "    return results\n",
    "\n",
    "#normalize_y_axis_threshold()"
    
